### ISSUE TITLE
Incorrect exterior surface convective heat transfer rate reporting during rain under active Present Weather Observation override in Version 8.9

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8621] opened 2021-03-16 00:11 UTC
EnergyPlus 8.9 has shows problematic (unrealistic) exterior surface convective heat transfer rate (W/m2) during a Present Weather Observation override to have rain (1-moderate rain), shown as:  

![image](https://user-images.githubusercontent.com/64040111/111236415-ce857580-85c0-11eb-961a-064dcefdda96.png)

The convective heat transfer rate is above 2000--3000 W/m2 for a roof surface during a night period with no solar radiations, which seems to be quite unrealistic. 

The problem was reported with EnergyPlus v8.9. In more recent versions such as v9.4 and v9.5 pre-release, the report seems to be normal corrected already: 

![image](https://user-images.githubusercontent.com/64040111/111236656-6a16e600-85c1-11eb-9920-7980a06a6e04.png)

It might be fixed somewhere in the middle of the development; however the exact issue post could not be found after some search. Therefore a new issue is posted for this one. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v8.9 (seems to be normal in v9.4 and v9.5 pre-release)
 - Helpdesk ticket number 15654

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2021-03-16 16:38
Duplicate of #6939, fixed in #7504 (v9.2).

**Closed as completed by mjwitte** 2021-03-16 16:38 UTC
