### ISSUE TITLE
RunPeriod - Day of Week for Start Day -and RunPeriodControl:SpecialDays

### ISSUE THREAD

**Issue by Lefort-Antoine** [NREL/EnergyPlus#5818] opened 2016-08-17 19:24 UTC
## Issue overview

The 'Start Date' of 'RunPeriodControl:SpecialDays' is not respected when:
- the 'Start Date' form type is : '3rd Monday in January'
- and the 'UseWeatherFile' is specified for "Day of Week for Start Day" of the 'Run Period'
  while schedule weekdays are correct.

Comparaison have been done specifying the 'Sunday' for "Day of Week for Start Day" of the 'Run Period' (similar to the weekday specified for start day in the epw's header).
### Details

Some additional details for this issue (if relevant):
- Platform (OSX 10.10.5)
- Version of EnergyPlus 8.5.0-c87e61b44b
- USA_CO_Golden-NREL.724666_TMY3.epw
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2017-02-24 22:46
Looks like this is similar to #5862

**Comment by Myoldmopar** [comment] 2018-09-24 21:15
@jasondegraw is this something your run period work has addressed?

**Comment by jasondegraw** [comment] 2018-09-24 21:20
Not directly, so I'd need to investigate. You can assign it to me and I can look into it post release.

**Comment by jasondegraw** [comment] 2019-03-05 16:53
@Lefort-Antoine @Myoldmopar I'm not able to reproduce this on 9.0.1, possibly because `UseWeatherFile` is no longer supported as a way to specify the starting week day. I tried two different weather files (including the one noted in the report) and a number of different scenarios (no starting weekday specified, starting weekday specified, etc.) and have always gotten `Holiday` in the ESO for the days I specified (e.g. 3rd Monday in January). It's possible that the code removed to eliminate `UseWeatherFile` also fixed the issue, so unless there's further information that could help me reproduce this in 9.0.1, I'd say this issue should be closed.

**Comment by jasondegraw** [comment] 2019-03-12 17:21
Closing, reopen if the problem reappears.

**Closed as completed by jasondegraw** 2019-03-12 17:21 UTC
Labels: SeverityMedium, PriorityLow

**Comment by Lefort-Antoine** [comment] 2019-03-12 17:26
Thanks for your reply. I will inform you if I found similar problem on 9.0.1.

**Comment by EnergyArchmage** [comment] 2019-08-01 20:23
I have been comparing 8.9 to 9.1 and found that earlier version was not accurately applying holiday rules, e.g. Memorial day came out on a Wednesday and now on a Monday.  So something did get fixed here with the run period work I think.
