### ISSUE TITLE
The SQLite database failed to open.

### ISSUE THREAD

**Issue by guyue5** [NREL/EnergyPlus#7512] opened 2019-09-19 09:11 UTC
Issue overview
--------------
when i run it in ray,
**FATAL:The SQLite database failed to open.

### Details
(pid=26824) Processing Input File
(pid=26824) **FATAL:The SQLite database failed to open.
(pid=26824) EnergyPlus Run Time=00hr 00min  0.22sec
(pid=26829) Program terminated: EnergyPlus Terminated--Error(s) Detected.

**Comment by Myoldmopar** [comment] 2019-09-20 16:58
We would need more information to help with this.  The [issue template](https://github.com/NREL/EnergyPlus/blob/develop/.github/issue_template.md) asked for information regarding your run configuration, platform, version of EnergyPlus, etc.  Please provide more information including whether you are running EnergyPlus remotely, on a network share, etc.

**Comment by jmarrec** [comment] 2020-01-07 08:32
@guyue5 Are you able to provide more information please? Otherwise we'll have to close this issue because we cannot replicate.

**Comment by jmarrec** [comment] 2020-05-19 09:47
Considering the lack of information needed to reproduce, I'm closing this one. It's likely user had the SQL file open somewhere else. Happy to reopen if more information comes along though.

**Closed as completed by jmarrec** 2020-05-19 09:47 UTC
