### ISSUE TITLE
Documentation 2023-2024

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9972] opened 2023-04-20 13:32 UTC
A place to keep an ongoing list of documentation issues.

**Comment by JasonGlazer** [comment] 2023-04-20 13:33
- [x]  In the IOref 1.11.28 References should probably be 1.11.27.7

**Comment by rraustad** [comment] 2023-06-14 12:44
- [x]  IO Ref does not describe output reports Zone Phase Change Material Melting Enthalpy and Zone Phase Change Material Freezing Enthalpy found in HeatBalanceAirManager around line 320.

**Comment by eringold** [comment] 2023-06-28 20:50
- [x] IO Ref Refrigeration:System field 'Refrigeration System Working Fluid Type' says "Valid choices are R11, R123, R134A, R12, R22, R404A, R507A, or R410A." though the IDD has no restrictions:

https://github.com/NREL/EnergyPlus/blob/3ce85f9cde01190b8ee923e56f7b9606350fd53a/doc/input-output-reference/src/overview/group-refrigeration.tex#L1339-L1341

```
  A6 ,  \field Refrigeration System Working Fluid Type
        \note Fluid property data for the refrigerant must be entered.
        \note The fluid property data, including the objects:
        \note FluidProperties:Name, FluidProperties:Temperatures,
        \note FluidProperties:Saturated and FluidProperties:Superheated
        \note can be copied from the FluidPropertiesRefData.idf dataset
        \required-field
        \type object-list
        \object-list FluidNames
```

**Comment by shorowit** [comment] 2023-08-02 15:42
- [ ] https://github.com/NREL/EnergyPlus/issues/9800

**Comment by mjwitte** [comment] 2023-09-28 13:10
From helpdesk ticket 16495:
 
> On page 61: talking about 'Shading Calculation Method' it says: "Unlike PolygonClipping, PixelCounting has no limitations related to zone concavity when used with any “FullInterior” solar distribution options (i.e., it can accommodate both concave and convex zones equally)."  Therefore, if I would like to include Concave Zones, I would conclude that I should use 'FullInteriorAndExterior' as the value for the SolarDistribution property on the Building object.
On page 49: talking about the 'SolarDistribution' property on Building, it says: "If the zone’s surfaces do not enclose a space or if the zone is not convex you should use Solar Distribution = FullExterior instead of FullInteriorAndExterior."  This two entries contradict each other.  Which is correct?

- [x] The Solar Distribution section on FullInteriorExterior should be updated to reference the ShadowCalculation object and say that the convex requirement only applies when using PolygonClipping, or something to that effect. The fully enclosed requirement still stands.

**Comment by shorowit** [comment] 2023-10-06 12:48
- [x] [This Unmet Hours post](https://unmethours.com/question/97096/peak-flow-rate-of-wateruseequipment/) suggests that [Peak Flow Rate of WaterUse:Equipment](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-water-systems.html#field-peak-flow-rate-000) should not have a reference to “hot” water.

**Comment by aaron-boranian** [comment] 2023-10-06 13:37
- [x] [Heat recovery for air-cooled chillers has been enabled](https://github.com/NREL/EnergyPlus/pull/10240), but IO Ref section for *Design Heat Recovery Water Flow Rate* input field of `Chiller:Electric:EIR` still mentions this is not possible. See related comment [here](https://github.com/NREL/EnergyPlus/pull/10240#discussion_r1346554724).

**Comment by jcyuan2020** [comment] 2023-10-31 15:27
- [x] A user (Helpdesk Ticket 16513) pointed out that the following equation in the EcoRoof model is incorrect in Engineering Reference (pp.189, Eq 4.11, v23.2):

![image](https://github.com/NREL/EnergyPlus/assets/64040111/b63535b3-36d7-4cbd-965f-f69515fbb88a)

The correct form should be "0.9 - 0.7 * exp(-0.75 * LAI)" instead.

The EnergyPlus source code is checked and the implementation there is correct. This is confirmed to be just a documentation issue.

**Comment by shorowit** [comment] 2024-02-21 18:09
- [x] Document Heat Index vs. Heat Index OccupantHour vs. Heat Index OccupiedHour (see [Unmet Hours question](https://unmethours.com/question/98280/heat-index-vs-heat-index-occupanthour-vs-heat-index-occupiedhour/))

HeatBalanceSurfaceManager (what's the difference in the last 2 reports?):

    state.dataHeatBalFanSys->ZoneHeatIndexHourBinsRepPeriod(ZoneNum, ReportPeriodIdx)[0] += state.dataGlobal->TimeStepZone;
    state.dataHeatBalFanSys->ZoneHeatIndexOccuHourBinsRepPeriod(ZoneNum, ReportPeriodIdx)[0] +=
                            NumOcc * state.dataGlobal->TimeStepZone;
    state.dataHeatBalFanSys->ZoneHeatIndexOccupiedHourBinsRepPeriod(ZoneNum, ReportPeriodIdx)[0] +=
                            (NumOcc > 0) * state.dataGlobal->TimeStepZone;

**Comment by shorowit** [comment] 2024-02-25 17:36
- [x] There are still references to `DistrictHeating` (which was renamed to `DistrictHeatingWater` in E+ 23.2). For example, in the last paragraph [here](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-hvac-templates.html#hvactemplatezoneidealloadsairsystem). All *.tex files should be audited because I'm seeing additional references. Noted in this [Unmet Hours post](https://unmethours.com/question/98303/hvac-idealloadsairsystem-output-metric/).

**Comment by mjwitte** [comment] 2024-03-21 15:56
- [x] The Input Output Reference description for SetpointManager:MixedAir only mentions using it for controlling outdoor air economizers. It should also explain that it's used to adjust temperature setpoints for any component with a control node that is upstream of the fan.

![image](https://github.com/NREL/EnergyPlus/assets/4991075/a7c4099a-0eb5-4d07-baa2-3d9a6aad4758)

(ref helpdesk ticket 16610)

**Comment by aaron-boranian** [comment] 2024-04-11 16:47
- [x] The output variables listed for `Steam:Humidifier:Gas` still mention previous "Gas" options instead of "NaturalGas". For example, [output variable](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-humidifiers-and-dehumidifiers.html#humidifier-gas-use-rate-w) is labelled as "Humidifier **Gas Use** Rate" instead of "Humidifier **NaturalGas** Rate". 

Should likely check other output variable references to be updated from "Gas" to "NaturalGas".

**Comment by mjwitte** [comment] 2024-05-01 15:21
- [x] In the I/O Reference, for HybridModel:Zone "Calculate Zone Internal Thermal Mass", there is no mention of where to find the output for average thermal mass. It is reported in the table report "Input Verification and Results Summary" subtable "Hybrid Model: Internal Thermal Mass". From example file HybridZoneModel.idf (which currently doesn't have an Output:Table:SummaryReports object):

![image](https://github.com/NREL/EnergyPlus/assets/4991075/f91bb392-ece8-4ab9-ac58-79e0109ceaa2)

Also should update the example file to generate this report.
Ref helpdesk ticket 16643.

**Comment by RKStrand** [comment] 2024-05-02 14:59
- [x] In I/O Ref, page 2426 in V24.1, Table 1.61, there is an overlapping of columns that should be fixed:

![image](https://github.com/NREL/EnergyPlus/assets/5804989/a89a4b99-0e7b-43e0-97c7-08f42f5ee19f)

**Comment by JasonGlazer** [comment] 2024-05-20 14:22
Change the Output meter name field description in UtilityCost:Tariff to reference ElectricityPurchased:Facility instead of Electricity:Purchased. See help desk ticket #16659. Maybe make same change for the gas meter. Probably should update the IDD to be consistent also.

**Comment by jmarrec** [comment] 2024-06-07 14:57
* [x] HeatExchanger:AirToAir:SensibleAndLatent docs outdated

There are no at 75% numeric fields anymore

https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-heat-recovery.html#field-sensible-effectiveness-at-75-cooling-air-flow

https://github.com/NREL/EnergyPlus/blob/cb9e70f16540f0dca5c979f106d985dd8d301d6d/doc/input-output-reference/src/overview/group-heat-recovery.tex#L267-L270

**Comment by aaron-boranian** [comment] 2024-06-14 16:33
- [x] Object type description for Refrigeration:AirChiller [mentions "the rated operating temperature" as an input field](https://github.com/NREL/EnergyPlus/blob/6b6918482fa176d8b8b5814c2a8d928a6f978d4f/doc/input-output-reference/src/overview/group-refrigeration.tex#L3983), but that input field does not exist for this object type. Perhaps a copy/past error from the [object type description for Refrigeration:WalkIn](https://github.com/NREL/EnergyPlus/blob/6b6918482fa176d8b8b5814c2a8d928a6f978d4f/doc/input-output-reference/src/overview/group-refrigeration.tex#L966), which does have an [Operating Temperature input field](https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-refrigeration.html#field-operating-temperature). 

Object type description for Refrigeration:AirChiller should have "the rated operating temperature" removed.

**Comment by RKStrand** [comment] 2024-07-01 11:11
- [x] In I/O Ref, page 698 in V24.1, Table 1.46, there is an overlapping of columns/columns that go past the margin on the left that should be fixed:

![image](https://github.com/NREL/EnergyPlus/assets/5804989/124e7950-7d0b-44fb-baff-c8cb88faec9f)

**Comment by Myoldmopar** [comment] 2024-07-03 14:44
- [x] Here's a few typos in the parametric object docs:

- https://github.com/NREL/EnergyPlus/blob/e2c430549a6c69dd555668fa10b0fdc18883a873/doc/input-output-reference/src/parametric-objects.tex#L46
  - substation -> substitution
- https://github.com/NREL/EnergyPlus/blob/e2c430549a6c69dd555668fa10b0fdc18883a873/doc/input-output-reference/src/parametric-objects.tex#L54
  - theses -> these
- https://github.com/NREL/EnergyPlus/blob/e2c430549a6c69dd555668fa10b0fdc18883a873/doc/input-output-reference/src/parametric-objects.tex#L100
  - needed -> needs

@JasonGlazer @mjwitte @RKStrand @jmarrec @rraustad @tanaya-mankad would one of you be able to tackle all the cleanups in this issue in your current defect bundle?  If not, I'll tackle it sometime soon.  Thanks!

**Comment by RKStrand** [comment] 2024-07-03 15:02
@Myoldmopar I can do these as I’ve got space in my defects works to do this. I’ll assign myself and work on this sometime soon.

**Comment by aaron-boranian** [comment] 2024-07-08 21:59
- [x] `Curve:QuadLinear` IO Ref section is missing field descriptions of *Minimum Curve Output* and *Maximum Curve Output*. This inputs should be after *[Maximum Value of z](https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-performance-curves.html#field-maximum-value-of-z)* and before *[Input Unit Type for w](https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-performance-curves.html#field-input-unit-type-for-w)* (see IDD snippet below).
```
Curve:QuadLinear,
...
  N14, \field Maximum Value of z
       \required-field
       \type real
       \unitsBasedOnField A5
  N15, \field Minimum Curve Output
       \type real
       \note Specify the minimum value calculated by this curve object
       \unitsBasedOnField A4
  N16, \field Maximum Curve Output
       \type real
       \note Specify the maximum value calculated by this curve object
       \unitsBasedOnField A4
  A2 , \field Input Unit Type for w
...
```

- [ ] Same issue for `Curve:QuintLinear` IO Ref section missing field descriptions of *Minimum Curve Output* and *Maximum Curve Output*. These inputs should be after *[Maximum Value of z](https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-performance-curves.html#field-maximum-value-of-z-3)* and before *[Input Unit Type for v](https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-performance-curves.html#field-input-unit-type-for-v)* (see IDD snippet below).
```
Curve:QuintLinear,
...
  N16, \field Maximum Value of z
       \required-field
       \type real
       \unitsBasedOnField A5
  N17, \field Minimum Curve Output
       \type real
       \note Specify the minimum value calculated by this curve object
       \unitsBasedOnField A4
  N18, \field Maximum Curve Output
       \type real
       \note Specify the maximum value calculated by this curve object
       \unitsBasedOnField A4
  A2 , \field Input Unit Type for v
...
```

**Comment by RKStrand** [comment] 2024-07-11 14:45
> * [x]  Document Heat Index vs. Heat Index OccupantHour vs. Heat Index OccupiedHour (see [Unmet Hours question](https://unmethours.com/question/98280/heat-index-vs-heat-index-occupanthour-vs-heat-index-occupiedhour/))
> 
> HeatBalanceSurfaceManager (what's the difference in the last 2 reports?):
> 
> ```
> state.dataHeatBalFanSys->ZoneHeatIndexHourBinsRepPeriod(ZoneNum, ReportPeriodIdx)[0] += state.dataGlobal->TimeStepZone;
> state.dataHeatBalFanSys->ZoneHeatIndexOccuHourBinsRepPeriod(ZoneNum, ReportPeriodIdx)[0] +=
>                         NumOcc * state.dataGlobal->TimeStepZone;
> state.dataHeatBalFanSys->ZoneHeatIndexOccupiedHourBinsRepPeriod(ZoneNum, ReportPeriodIdx)[0] +=
>                         (NumOcc > 0) * state.dataGlobal->TimeStepZone;
> ```

The difference in the last two is that (NumOcc > 0) either evaluates to 1 when NumOcc is greater than zero or 0 when it isn't.  So, if NumOcc is 10, the second output will have 10*TimeStepZone to it while the third will only have TimeStepZone added.  The difference between the first and third is then all hours vs. occupied hours.  To clarify this, I'm going to put some additional text in this part of the documentation to clarify this.

**Comment by mjwitte** [comment] 2024-07-12 14:01
@RKStrand Adding one more small one here.
 - [x] In the I/O Ref, for Generator:Photovoltaic, the description for "Surface Name" should be more clear on how it's used. From helpdesk ticket 16703.
 
Current text:
1.54.29.1.2 Field: Surface Name
This field is the name of a surface that defines the location and geometry of the array.

Suggested text (taken from the overview paragraph and the idd memo):
1.54.29.1.2 Field: Surface Name
This field is the name of a surface that defines the location and geometry of the array. Array tilt, azimuth, and gross area are taken from the referenced building surface or shading surface. This will define the orientation of the solar
panel for the detailed models and also the area of the solar panel for the simple model.

**Comment by Myoldmopar** [comment] 2024-07-12 14:52
@mjwitte since @RKStrand already pushed his branch, and the fixes look fine and ready to go, I'll pull this tweak into his branch myself and do a quick merge of it.  After that we should probably just move on to the next new doc tracking issue.

**Comment by RKStrand** [comment] 2024-07-12 14:58
@Myoldmopar Oops...I missed this.  I just made another commit with the fix as per @mjwitte.

**Closed as completed by RKStrand** 2024-07-12 14:58 UTC
Labels: Documentation, LowComplexityApproved
