### ISSUE TITLE
CO2-Based Proportional Demand Controlled Ventilation based on Design Occupancy Level

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5086] opened 2015-08-11 14:16 UTC
The existing CO2 based proportional demand controlled ventilation is based on scheduled occupancy. Carrier requires that CO2 based proportional demand controlled ventilation is based on design occupancy level due to practical applications. The detailed description is provided in an enhancement item: AirLoop_ProportionalControlDCV_2014-Carrier.docx.

**Comment by Myoldmopar** [comment] 2015-08-11 14:25
Duplicate of #5031.

**Closed as completed by Myoldmopar** 2015-08-11 14:25 UTC
Labels: SeverityHigh, PriorityLow, NewFeature
