### ISSUE TITLE
FaultModel is not working as expected. 

### ISSUE THREAD

**Issue by tidecoder** [NREL/EnergyPlus#6457] opened 2018-02-01 15:43 UTC
[faultNotworking.zip](https://github.com/NREL/EnergyPlus/files/1686131/faultNotworking.zip)
Issue overview
--------------
I am doing fault simulation by FaultModels in EnergyPlus. I found two fault models are not working correctly: FaultModel:TemperatureSensorOffset:OutdoorAir, FaultModel:TemperatureSensorOffset:ReturnAir. 
My baseline model is from the reference building library(fault-free, ASHRAE90.1_MediumOffice_STD2013_Chicago),

fault-free: EnergyPlus V8.7, the simulated total source energy(html file): 5890.77GJ.

fault1: OA sensor offset; i vary the sensor offset to be 0, 1, 2, 5, 8, degreeC. The simulated total source energy: 5884.79GJ, for all offset values (EnergyPlus V8.8). 
But for EnergyPlus V8.7, the simulated total source energy: 5890.77GJ, for all offset values. (The same to fault-free model)

fault2: RA sensor offset; i vary the sensor offset to be 0, 1, 2, 5, 8, degreeC The simulated total source energy: 5884.79GJ, for offset values (EnergyPlus V8.8). 
But for EnergyPlus V8.7, the simulated total source energy: 5890.77GJ, for all offset values. (The same to fault-free model)

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows
 - Version of EnergyPlus (V8.7, V8.8)
 - Unmethours link or helpdesk ticket number: 
https://unmethours.com/question/29581/faultmodel-is-not-working-as-expected-for-v87-and-v88/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2018-02-01 18:10
Probably a duplicate of #6422.

**Comment by jmarrec** [comment] 2020-01-28 16:09
Will close this one since it's getting stale and no one responded that it wasn't a duplicate of #6422 (which was fixed)

**Closed as completed by jmarrec** 2020-01-28 16:09 UTC
Labels: PriorityHigh
