### ISSUE TITLE
ZoneMixing report variables not set unless ZoneAirMassFlowConservation used

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#5042] opened 2015-07-23 15:31 UTC
The output variables "Zone Mixing Receiving Air Mass Flow Rate" and "Zone Mixing Source Air Mass Flow Rate" do not seem to be populated unless the ZoneAirMassFlowConservation object is present with "Adjust Zone Mixing For Zone Air Mass Flow Balance" set to "Yes".

**Comment by Nigusse** [comment] 2015-07-27 13:48
@macumber It is by design that the "Zone Mixing Receiving Air Mass Flow Rate" and "Zone Mixing Source Air Mass Flow Rate" are not reported (set to zero) unless the  ZoneAirMassFlowConservation object is present with "Adjust Zone Mixing For Zone Air Mass Flow Balance" input field set to "Yes".

The variables to look at when the ZoneAirMassFlowConservation object is not present is "Zone Mixing Mass Flow Rate".

**Comment by macumber** [comment] 2015-07-28 16:06
Thanks @Nigusse .  I think the confusing thing is that those variables are listed under ZoneAirMassFlowConservation's outputs but there is no documentation that they will be 0 if the "Adjust Zone Mixing For Zone Air Mass Flow Balance" is set to "No".  At a minimum we should document that these reports are not generated if the field is set to "No". 

http://bigladdersoftware.com/epx/docs/8-3/input-output-reference/group-airflow.html#outputs-7

**Comment by Myoldmopar** [comment] 2015-08-13 21:24
@mjwitte Try to address with link infiltration work

**Comment by mjwitte** [comment] 2015-09-04 02:58
@macumber I see three options here.  What would be your preference?
1. Leave as-is and just clarify the documentation.
2. Do not setup these variables if ZoneAirMassFlowConservation is not active.
3.  Attempt to populate these variables even when ZoneAirMassFlowConservation is not active.

**Comment by macumber** [comment] 2015-09-04 16:12
In OpenStudio, I made the 'Adjust Zone Mixing For Zone Air Mass Flow Balance' field have only one value which is 'Yes'.  To me it doesn't make sense to have an on/off button on this object, if it is in the file then it is active, if it is not in the file then it is not.  To me, a lot of confusion would be removed by removing this redundant field (or making it only have one value of 'Yes').

**Comment by mjwitte** [comment] 2015-09-04 16:18
@macumber My perspective on that type of switch is that it allows the object to stay intact in the idf while letting me turn on/off the action and see what changes.  So, I like fields like that.

But in this case, that object is changing soon.  The mixing and infiltration fields will have independent on/off controls.  See #5123 

I would still like your input on how to handle the output variables.  I plan to address this issue as part of that pull request (today).

**Comment by macumber** [comment] 2015-09-04 16:32
Well to me those switches are just redundant, especially for an object that doesn't have a lot of fields that you want to preserve when turning on/off.  But if that is off the table, I would prefer clarifying the documentation at a minimum and not generating the reports when the object is turned off.  Are there other objects like this where certain report variables give bad values when the object is off?

**Comment by macumber** [comment] 2015-09-04 16:32
Seems like you could just say "Output report X is only generated if the object is turned on" in the IO reference

**Comment by mjwitte** [comment] 2015-09-04 16:40
@macumber I see your point as well about the switch fields.  I'm not a big fan of all these little control objects, anyway.  I'd prefer to lump them together a bit.  Anyways, I will disable these outputs when the mass flow balance is not active.  I'm also thinking these should all be renamed to start with "Zone Air Mass Balance . . . " to make it clear these are only the values that are included in the mass balance.

**Comment by macumber** [comment] 2015-09-04 16:46
Lumping them together into a bigger control object would make sense.  You'd still have the issue where certain reports are only generated when fields have a given value but if that is documented well them I am good with it :-)

**Comment by mjwitte** [comment] 2015-09-04 16:48
Someday maybe (lumping).  Anyway, for now, I'll clean up this one.

**Comment by mjwitte** [comment] 2015-09-14 17:07
Closed via #5123

**Closed as completed by mjwitte** 2015-09-14 17:07 UTC
Labels: Defect
