### ISSUE TITLE
Data in Equipment Summary (HTML) is missing

### ISSUE THREAD

**Issue by weilix88** [NREL/EnergyPlus#6945] opened 2018-09-06 15:43 UTC
Issue overview
--------------
It looks like I have to add "Maximum Number of HVAC Sizing Simulation Passes" to the SimulationControl class to make the data available under Equipment Summary. 

added Maximum number of HVAC Sizing Simulation Passes
<img width="1237" alt="has_data" src="https://user-images.githubusercontent.com/25957083/45168340-0b3ead80-b1c9-11e8-8566-f800e19e19ea.png">

Delete Maximum number of HVAC Sizing Simulation Passes
<img width="1237" alt="has_data" src="https://user-images.githubusercontent.com/25957083/45168371-1eea1400-b1c9-11e8-8aff-6ccaf26c4c20.png">

The test files can be accessed here: https://www.dropbox.com/s/b9din6ghbijmaud/Archive.zip?dl=0

### Details
Some additional details for this issue (if relevant):
 - Platform:
Mac OS, Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA)
8.9 
 - Unmethours link or helpdesk ticket number
NA

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ Yes ] Defect file added (https://www.dropbox.com/s/b9din6ghbijmaud/Archive.zip?dl=0)
 - [ No] Ticket added to Pivotal for defect (development team task)
 - [ No ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2020-07-24 14:48
#8146 happens to be a duplicate of this issue. This was addressed in #8159.

**Closed as completed by mjwitte** 2020-07-24 14:48 UTC
