### ISSUE TITLE
JSON followup issues

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6486] opened 2018-02-21 17:03 UTC
Issue overview
--------------
- [ ] Visual Studio dependency issues - GenerateEmbeddedEpJSONSchema always appears out of date, thinks for about 10 seconds then does nothing with it and moves on with the rest of the build.
- [ ] Better error messages for input errors. (see more details below).

An ill formed input file terminates via the idfParser without any indication of why. Users won't know why their input file is failing. Some form of message should report the object name and possibly the input field name expected, or something along those lines to give users direction of where to look.

Take 1ZoneEvapCooler and change this:

    ZoneHVAC:EquipmentList,
      Main Zone Equipment,     !- Name
      SequentialLoad,          !- Load Distribution Scheme
      AirTerminal:SingleDuct:Uncontrolled,  !- Zone Equipment 1 Object Type
      Main Zone Direct Air,    !- Zone Equipment 1 Name
      1,                       !- Zone Equipment 1 Cooling Sequence
      2,                       !- Zone Equipment 1 Heating or No-Load Sequence
      ZoneHVAC:Baseboard:Convective:Electric,  !- Zone Equipment 2 Object Type
      Main Zone Baseboard,     !- Zone Equipment 2 Name
      2,                       !- Zone Equipment 2 Cooling Sequence
      1;                       !- Zone Equipment 2 Heating or No-Load Sequence

to this:

    ZoneHVAC:EquipmentList,
      Main Zone Equipment,     !- Name
      AirTerminal:SingleDuct:Uncontrolled,  !- Zone Equipment 1 Object Type
      Main Zone Direct Air,    !- Zone Equipment 1 Name
      1,                       !- Zone Equipment 1 Cooling Sequence
      2,                       !- Zone Equipment 1 Heating or No-Load Sequence
      ZoneHVAC:Baseboard:Convective:Electric,  !- Zone Equipment 2 Object Type
      Main Zone Baseboard,     !- Zone Equipment 2 Name
      2,                       !- Zone Equipment 2 Cooling Sequence
      1;                       !- Zone Equipment 2 Heating or No-Load Sequence

If a user copy\pastes an object from an old file (or makes any other simple mistake) and runs it, they won't have a clue as to why it failed.

Error file results:

  Program Version,EnergyPlus, Version 8.9.0-1c5ba897d1, YMD=2018.02.21 11:48,
    ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
    ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
    ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
    ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
    ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  0.21sec

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2018-02-21 17:38
The Climate Summary Weather Statistics Report has missing rows (degree days and Koppen fields) and bad degree signs in the temperature fields. 99% certain this changed with the JSON PR. On Win64.

Before:
![image](https://user-images.githubusercontent.com/4991075/36495584-5ae59650-16fb-11e8-9f80-a4a324ea6b92.png)

After:
![image](https://user-images.githubusercontent.com/4991075/36495627-7c3d9dfc-16fb-11e8-913f-991340f02eb1.png)

**Comment by rraustad** [comment] 2018-02-21 19:01
This out of date build warning keeps popping up when running in debug or release mode.

![projoutofdate](https://user-images.githubusercontent.com/5778156/36499583-a132e912-1739-11e8-8147-e8e297ce9b9e.jpg)

**Comment by mbadams5** [comment] 2018-02-21 23:12
@rraustad I am aware of the validation issue(s) and is the major work item on for the JSON followup issue.

@mjwitte That is just a file encoding issue. I think the file got changed to `UTF-8` in the JSON branch and when I change it to `Windows 1252`, it all works properly again. However, when I got to commit the changes, it shows the ? mark.

```
diff --git a/src/EnergyPlus/OutputReportTabular.cc b/src/EnergyPlus/OutputReportTabular.cc
index 3dd28a6c3..deb53d64f 100644
--- a/src/EnergyPlus/OutputReportTabular.cc
+++ b/src/EnergyPlus/OutputReportTabular.cc
@@ -5399,7 +5399,7 @@ namespace OutputReportTabular {
                // na

                // SUBROUTINE PARAMETER DEFINITIONS:
-               static std::string const degChar( "°" );
+               static std::string const degChar( "<B0>" );

                // LineTypes for reading the stat file
                int const StatisticsLine( 1 );
@@ -5520,9 +5520,9 @@ namespace OutputReportTabular {
                                                coolingDesignlinepassed = true;
                                                lineType = coolingConditionsLine;
                                        }
-                               } else if ( has( lineIn, "(standard) heating degree-days (18.3°C baseline)" ) ) {
+                               } else if ( has( lineIn, "(standard) heating degree-days (18.3<B0>C baseline)" ) ) {
```

@rraustad I need to look into that popup warning. On Mac and linux everything is working as intended for that target, however, it looks like on Windows it is much more vocal about how it is structured.

**Comment by Myoldmopar** [comment] 2018-02-22 05:32
There is an anomaly about external dependent files causing diffs in the audit file.  See the full comment [here](https://github.com/NREL/EnergyPlus/pull/6491#issuecomment-367572134).

**Comment by Myoldmopar** [comment] 2018-02-22 20:17
I pushed a fix to tell CI to not worry about the lines containing (input file).  It was previously looking for (user input) and ignoring those lines.  I don't know exactly when decent_ci will pull in a new version of the regression test suite from dev support.  @lefticus do we need to restart the CI machines to get a new DevSupport pull?  Or will it do it as needed?  It looks like the clone_regression_repository function is called within each build, so I think we should be fine.  And the audit diffs should be gone.

**Comment by lefticus** [comment] 2018-02-22 21:02
It will eventually catch up yes, but no guarantee when. Just after the
current run has been competed.

**Comment by mjwitte** [comment] 2018-03-16 21:15
@mbadams5 Any progress on producing error messages for bad idf objects?

**Closed as completed** 2018-03-21 21:12 UTC
Labels: PriorityHigh

**Comment by rraustad** [comment] 2018-03-27 22:25
Running a V8.8 file in V8.9. Nice job @mbadams5 ! These should be easy to fix now.

   ** Severe  ** <root>[ZoneHVAC:EquipmentList][CoreZone Equipment List][equipment][0][zone_equipment_object_type] - "CoreZone_RTU Terminal" - Failed to match against any enum values.
