### ISSUE TITLE
HVAC Diagrams are crashing without finishing with example files HospitalXXXX.idf

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4296] opened 2014-06-17 21:10 UTC
MJW 06 June 2014
The HVAC diagram tool can be fragile for certain cases. In this case it is crashing without finishing execution, so my guess is that the error lies within HVAC diagram and the idf files are correct. I will post a bug report for this, but it may be too difficult to fix. There are other specific example files which also do not draw the diagram.

RHH 17 June 2014
I ran the example files with v8.1 and they completed successfully but cannot tell if HVAC diagrams completed since they are so large although I did see many comments showing up in the DOS box during execution saying "Equipment not found with inlet from node:   . . . . ."

Helpdesk Ticket 9507

Example files
HospitalBaseline.idf
HospitalLowEnergy.idf

**Comment by JasonGlazer** [comment] 2015-03-12 12:13
@mjwitte I cannot reproduce HVAC-Diagram crashing. It is possible it was fixed as part of resolving this other defect:

https://github.com/NREL/EnergyPlus/issues/4180

It was an initialization fix that just changed a few lines but was also related to very large files.

https://github.com/NREL/EnergyPlus/commit/80a227d935ab3d16e6b20e3b5c9648c7df4dd0b0

So what is the procedure? I assume I close this ticket, delete the branch I had started and delete the pivotal story?

**Closed** 2015-03-12 13:08 UTC
Labels: HVAC Diagram, Priority, S2 - Medium
