### ISSUE TITLE
Coil:Heating:DX coils won't operate below -20 or -50 C

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#4855] opened 2015-04-15 14:52 UTC
EnergyPlus will not allow DX heating coils to operate below an outdoor temperature that is unnecessarily restrictive.  (-50 or -20C)  Consider removing this limit or making it lower.  This applies to single speed coils and potentially variable speed coils too.

**Comment by mjwitte** [comment] 2015-04-15 15:08
This is nearly a duplicate of #4327

**Comment by kbenne** [comment] 2015-04-15 15:10
I agree. I'm going to remove this one I just added.

**Closed as completed** 2015-04-15 15:11 UTC
Labels: SeverityMedium
