### ISSUE TITLE
False positive 'surface azimuths do not match' warning

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#6994] opened 2018-10-02 20:24 UTC
Issue overview
--------------
A model created with OpenStudio and 'Output:Diagnostics,DisplayExtraWarnings' notes many 'Surface Azimuths do not match as expected.' warnings, e.g.:
```
   ** Warning ** GetSurfaceData: InterZone Surface Azimuths do not match as expected.
   **   ~~~   **   Azimuth=90.0, Tilt=90.0, in Surface=SURFACE 128, Zone=ZN_A1-5_1
   **   ~~~   **   Azimuth=90.0, Tilt=90.0, in Surface=SURFACE 140, Zone=ZN_A1-7_2
   **   ~~~   ** ..surface class of first surface=Wall
   **   ~~~   ** ..surface class of second surface=Wall
```
The input for these surfaces are:
```
BuildingSurface:Detailed,
  Surface 128,                            !- Name
  Wall,                                   !- Surface Type
  Typical Interior Wall,                  !- Construction Name
  Zn_A1-5_1,                              !- Zone Name
  Surface,                                !- Outside Boundary Condition
  Surface 140,                            !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  4.2958, -8.9313, 4.4196,                !- X,Y,Z Vertex 1 {m}
  4.2958, -8.9313, 0,                     !- X,Y,Z Vertex 2 {m}
  4.2958, 0, 0,                           !- X,Y,Z Vertex 3 {m}
  4.2958, 0, 3.048,                       !- X,Y,Z Vertex 4 {m}
  4.2958, -6.1881, 3.048,                 !- X,Y,Z Vertex 5 {m}
  4.2958, -6.1881, 4.4196;                !- X,Y,Z Vertex 6 {m}
```

```
BuildingSurface:Detailed,
  Surface 140,                            !- Name
  Wall,                                   !- Surface Type
  Typical Interior Wall,                  !- Construction Name
  Zn_A1-7_2,                              !- Zone Name
  Surface,                                !- Outside Boundary Condition
  Surface 128,                            !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  -7.7898, -4.2008, 4.4196,               !- X,Y,Z Vertex 1 {m}
  -7.7898, -4.2008, 3.048,                !- X,Y,Z Vertex 2 {m}
  -7.7898, 1.9873, 3.048,                 !- X,Y,Z Vertex 3 {m}
  -7.7898, 1.9873, 0,                     !- X,Y,Z Vertex 4 {m}
  -7.7898, -6.944, 0,                     !- X,Y,Z Vertex 5 {m}
  -7.7898, -6.944, 4.4196;                !- X,Y,Z Vertex 6 {m}
```
Surface 128 vertices are listed in counterclockwise order, and Surface 140 vertices are clockwise. OpenStudio calculates the azimuths for these surfaces as 90 and 270 degrees, respectively. Finally, outputting 'Surface Inside Face Temperature' and 'Surface Outside Face Temperature' of the two surfaces shows expected results (e.g. Inside temp of Surf 128 = Outside temp of Surf 140). This leads me to believe that something is wrong with the warning check. 

@JasonGlazer pinging you because of your geometry work.

I will provide the input file if needed.  

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - Version 8.9.0-eba93e8e1b

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2018-10-02 20:39
In the table envelope summary report, what azimuth is reported for these surfaces?  From the error message, it appears that EnergyPlus thinks both of these are facing 90, when one should be 270. It will be helpful to have the full idf file attached here or e-mailed directly to me or @JasonGlazer.

**Comment by eringold** [comment] 2018-10-02 21:10
@mjwitte thanks for the response. Curiously, it appears that **none** of the surfaces flagged by the GetSurfaceData warning are reported in the Envelope Summary table at all. However, I added a Output:Surfaces:List,Details;, which does show those surfaces with azimuths as reported in the warning, e.g. 90 degrees for both Surface 128 and Surface 140. 
I will email you files directly.

**Comment by dareumnam** [comment] 2019-09-16 21:35
@eringold @mjwitte @JasonGlazer I am wondering if this issue has been already fixed or someone is working on this issue. If not, I would like to take a look at fixing this defect. Could I also have the full idf file?

**Comment by mjwitte** [comment] 2019-09-17 12:37
@dareumnam This has not been fixed as far as I know. If the surface details report says the surfaces are both at azimuth of 90 degrees, then that's what they are in the simulation. This may not be an EnergyPlus issue.

@eringold Reading the original post again, both surfaces should have vertices entered in the same order (either both clockwise or both counterclockwise, depending on the SurfaceGeometry specified in the file), because the two surfaces are in different zones, and the order is from a viewpoint outside the zone. If the file is using world coordinates (no impact from zone origins or zone rotations), then these surfaces are indeed both facing an azimuth of 90. The problem is (was?) with OpenStudio.

Closing this issue for now.

**Closed as completed by mjwitte** 2019-09-17 12:37 UTC
