### ISSUE TITLE
Ratchet tariff documentation is incorrect

### ISSUE THREAD

**Issue by JimDirkes** [NREL/EnergyPlus#8869] opened 2021-07-06 15:25 UTC
Issue overview
--------------
The E+ I/O Reference (v9.4 $& v9.5) says that 1.0 is the default value for the Multiplier field. Apparently, that's not true for v9.4. Initially, I left the field blank and results showed that the ratchet was not taking effect. After I manually entered 1.0, the ratchet works. Who knew?

### Details
 - Platform (Windows 10)
 - Version of EnergyPlus (9.4)
 - Unmethours link: https://unmethours.com/question/55868/tariff-with-ratchet-for-peak-annual-demand/

### Checklist
na

**Comment by jmarrec** [comment] 2021-07-29 06:31
Duplicate of #8854

**Closed as completed by jmarrec** 2021-07-29 06:31 UTC
