### ISSUE TITLE
EP-Launch Lite app does not close via the menu option

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5899] opened 2016-10-04 20:25 UTC
## Issue overview

In EP-Launch Lite, when trying to quit the app via the menu, nothing happens.  The app will close when you click on the "red light" at the top left of the main window.
### Details

Some additional details for this issue (if relevant):
- Platform: Mac running OS X 10.11.6
- Version of EnergyPlus: V8.6
- Unmethours link or helpdesk ticket number: none
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (not applicable)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment] 2018-11-20 11:57
Duplicate of https://github.com/NREL/EnergyPlus/issues/6186

**Closed as completed by jmarrec** 2018-11-20 11:57 UTC
