### ISSUE TITLE
User file generates error file showing fatal but no details

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#6844] opened 2018-07-18 12:38 UTC
Issue overview
--------------

The users file (see helpdesk #12912) creates an error file when running stock EnergyPlus 8.9.0:

```
Program Version,EnergyPlus, Version 8.9.0-40101eaafd, YMD=2018.07.18 07:15,
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  0.35sec
```

But when rebuilding the same build in Visual Studio 2015 using the release version it runs fine and generates a long error file with lots of issues.

We need to correct the generation of the tiny and incomplete error file but it might be difficult to reproduce.

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus Version 8.9.0-40101eaafd (the release 8.9.0 version)
 - helpdesk ticket number 12912

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (see EnergyPlusDevSupport repo for 6844)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment] 2019-03-18 13:51
@JasonGlazer I don't see an entry for 6844 on EnergyPlusDevSupport. Did you push?

**Comment by JasonGlazer** [comment] 2019-03-18 14:02
I just pulled the files off of the helpdesk and put them in the repo and pushed it. You should be able to get them now. Not sure what happened to the original files.

**Comment by jmarrec** [comment] 2019-03-18 14:02
@JasonGlazer Thanks for the quick turn around on this!

**Comment by jmarrec** [comment] 2019-03-18 17:11
I can't reproduce it really. I built 8.9.0 (`git checkout v8.9.0`) in debug, it actually ran fine with it.

```
$ep_build2/Products/energyplus --version
EnergyPlus, Version 8.9.0-40101eaaf

$ep_build2/Products/energyplus -w PRT_Porto.085450_IWEC.epw -d out890 V_PREV_170805_V890.idf 
EnergyPlus Starting
EnergyPlus, Version 8.9.0-40101eaafd, YMD=2019.03.18 17:11
Initializing Response Factors
[...]
EnergyPlus Completed Successfully.
```

Indeed eplusout.err has lots of errors.

I will try to compile in Release, and try the installer tomorrow

**Comment by jmarrec** [comment] 2019-03-20 13:29
I've tried building it in Release.
I've tried the official 8.9.0 installer.
The file runs in all cases.
I tried running the file with the 8.9.0 installer a bunch of times just to make sure. None failed.

I also tried on Windows with the 8.9.0 installer a few times. None Failed.

@JasonGlazer I suggest closing this issue since we can't reproduce it.

**Closed as completed** 2019-03-22 13:37 UTC
