### ISSUE TITLE
Fixed fatal error when autosizing UA-value of hot water coils 

### ISSUE THREAD

**Issue by mleach-noresco** [NREL/EnergyPlus#4980] opened 2015-06-22 20:01 UTC
I have a model with a unit heater with a hot water coil.  All relevant fields in both the unit heater and the hot water coil are set to autosize.  However, EnergyPlus crashes during sizing and gives the error "Autosizing of heating coil UA failed."  It then goes on to say: "Inadequate water side capacity: in Plant Sizing for this hot water loop.  Increase design loop exit temperature and/or decrease design loop delta T."  After doing a heat transfer calculation on the water side, it looks like the maximum hot water flow rate for the coil is too low for the specified plant loop Delta T (by a factor of about four), given the capacity of the coil.  This explains the error (and decreasing the delta T for the plant loop increases flow and prevents the crash).  However, what I don't understand is why the maximum hot water flow rate is coming out so low.  One potential red flag that I found was that the coil inlet air temperature for sizing is being reported as the winter design outside air condition.  Since this is zone equipment, I would expect that temperature to be the zone heating setpoint.  Using the winter design outside air temperature results in an air-side delta T of about 4 times larger than what I would expect.  I'm not sure if it is a coincidence that the air-side delta T seems about 4 times too large and the water-side flow rate seems about 4 times too low, but I thought it was worth mentioning.  In general, I would expect that I can set up my plant loop however I want and the coil water flow rate should adjust accordingly (rather than having to adjust my loop inputs because my coil flow rate is not calculating correctly).

**Comment by kbenne** [comment] 2015-06-22 20:54
Defect file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/4000s/4980/4980_in.idf).

**Comment by Nigusse** [comment] 2016-01-27 19:32
The problem is due to the use of different Design Coil Capacity/Load for auto-sizing water flow rate and the UA-Value of the hot water heating coil in ZoneHVAC:UnitHeater object. The Design Coil Capacity for zone equipment such FanCoil and Terminal Single Duct Objects is recalculated using the design water flow rate and the hot water loop design deltaT. Thus the hot water heating coil UA-value is sized using the same load/capacity as the one used for design water flow rate sizing.

On the contrary the unit heater's water heating coil recalculates Design Coil Capacity based on the design supply air flow rate and entering and leaving design air conditions just like an air loop equipment, which accounts for the load due to outside air. As the result when there is significant outside air fraction (like this defect file case), the unit heater hot water coil entering design condition is skewed toward outside air, which leads to very huge Design Coil Capacity compared to the Design Coil Load and became a bad starting condition for COIL UA-value iterative solver, Regula Falsi. Consequently the UA-Value auto sizing calculation failed for one of the zones, which had large amount of outside air.

This can be corrected by allowing the unit heater hot water coil UA-value sizing to recalculate the Design Coil Capacity based on design water flow rate and the hot water deltaT just like the other ZoneHVAC equipment (e.g. FanCoil). Now, the defect file has completed the sizing calculation successfully and for annual run. The auto sized UA-Values look reasonable compared to Design Coil Load. I pushed the branch to remote.

**Comment by jmarrec** [comment] 2016-02-17 10:44
+1, still running into autosizing issues with this unit heater

**Comment by Nigusse** [comment] 2016-02-17 13:31
@jmarrec the defect file did run OK after the fix. Is this issue in the defect file or another file?

**Comment by jmarrec** [comment] 2016-02-17 13:52
Another file (actually anytime I try to use unit heater I end up having to hardsize the UnitHeater maximum water flow rate at the risk of picking a wrong value).

I was just showing my interest for this issue, opened 6 months ago, that hasn't to my knowledge made its way into a public release.

Btw, where is the branch on which you made the fix? It's not referenced here

**Comment by Nigusse** [comment] 2016-02-17 14:16
No it has not been released.  This bug was just fixed a three weeks ago.  Here is the link to the PR:
https://github.com/NREL/EnergyPlus/pull/5445

**Comment by jmarrec** [comment] 2016-02-17 14:29
thank you!

**Comment by Myoldmopar** [comment] 2016-03-03 20:09
Closed via #5445

**Closed as completed by Myoldmopar** 2016-03-03 20:09 UTC
Labels: SeverityMedium, PriorityLow
