### ISSUE TITLE
Transition from 8.6 to 9.0 not working on ubuntu

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [NREL/EnergyPlus#7514] opened 2019-09-20 16:26 UTC
Hi I'm trying to update an idf file from 8.6 to 9.0. I have understood that to do this is have to pass through the various version. I have problem from he first transition from 8.6 to 8.7 here is the error:

```
Transition-V8-6-0-to-V8-7-0 
 Transition Starting
 Conversion 8.6 => 8.7
 Processing Old IDD -- V8-6-0-Energy+.idd
 Processing New IDD -- V8-7-0-Energy+.idd
 Enter "diff" for differences only, "full" for full idf outputs
-->full
 Will create new full IDFs
 Enter "yes" for including units on output lines, "no" for no units inclusion
-->yes
 Will create new IDF lines with units where applicable
 Enter "yes" for preserving blanks in default fields, "no" to fill those fields with defaults
-->yes
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
  Report Variable Name file=Report Variables 8-6-0 to 8-7-0.csv
  not found.
 F
 Enter input file name, with path
-->5zone.idf
 Processing IDF -- 5zone.idf
 ** Severe  ** IP: IDF line~5 Did not find "Version" in list of Objects
 ** Severe  ** IP: IDF line~7 Did not find "RunPeriod" in list of Objects
 ** Severe  ** IP: IDF line~19 Did not find "RunPeriodControl:DaylightSavingTime" in list of Objects
 ** Severe  ** IP: IDF line~22 Did not find "Site:Location" in list of Objects
 ** Severe  ** IP: IDF line~28 Did not find "Site:GroundTemperature:BuildingSurface" in list of Objects
 ** Severe  ** IP: IDF line~42 Did not find "Site:GroundTemperature:Deep" in list of Objects
 ** Severe  ** IP: IDF line~56 Did not find "Site:GroundTemperature:Shallow" in list of Objects
 ** Severe  ** IP: IDF line~70 Did not find "Site:GroundTemperature:FCfactorMethod" in list of Objects
 ** Severe  ** IP: IDF line~84 Did not find "Site:GroundReflectance" in list of Objects
 ** Severe  ** IP: IDF line~98 Did not find "Site:GroundReflectance:SnowModifier" in list of Objects
 ** Severe  ** IP: IDF line~102 Did not find "SimulationControl" in list of Objects
 ** Severe  ** IP: IDF line~110 Did not find "SizingPeriod:DesignDay" in list of Objects
 ** Severe  ** IP: IDF line~137 Did not find "SizingPeriod:DesignDay" in list of Objects
 ** Severe  ** IP: IDF line~164 Did not find "SizingPeriod:DesignDay" in list of Objects
 ** Severe  ** IP: IDF line~191 Did not find "SizingPeriod:DesignDay" in list of Objects
 ** Severe  ** IP: IDF line~218 Did not find "Timestep" in list of Objects
 ** Severe  ** IP: IDF line~220 Did not find "ConvergenceLimits" in list of Objects
 ** Severe  ** IP: IDF line~224 Did not find "ScheduleTypeLimits" in list of Objects
 ** Severe  ** IP: IDF line~225 Did not find "ScheduleTypeLimits" in list of Objects
 ** Severe  ** IP: IDF line~226 Did not find "ScheduleTypeLimits" in list of Objects
 ** Severe  ** IP: IDF line~227 Did not find "ScheduleTypeLimits" in list of Objects
 ** Severe  ** IP: IDF line~228 Did not find "ScheduleTypeLimits" in list of Objects
 ** Severe  ** IP: IDF line~230 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~238 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~246 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~254 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~262 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~270 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~282 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~286 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~290 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~293 Did not find "Schedule:Week:Daily" in list of Objects
 ** Severe  ** IP: IDF line~300 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~303 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~306 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~309 Did not find "Schedule:Day:Hourly" in list of Objects
 ** Severe  ** IP: IDF line~312 Did not find "Schedule:Week:Daily" in list of Objects
 ** Severe  ** IP: IDF line~318 Did not find "Schedule:Week:Daily" in list of Objects
 ** Severe  ** IP: IDF line~324 Did not find "Schedule:Week:Daily" in list of Objects
 ** Severe  ** IP: IDF line~330 Did not find "Schedule:Week:Daily" in list of Objects
 ** Severe  ** IP: IDF line~347 Did not find "Material:NoMass" in list of Objects
 ** Severe  ** IP: IDF line~355 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~359 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~368 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~377 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~386 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~392 Did not find "Material:InfraredTransparent" in list of Objects
 ** Severe  ** IP: IDF line~395 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~399 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~406 Did not find "Schedule:Compact" in list of Objects
 ** Severe  ** IP: IDF line~428 Did not find "WindowMaterial:Gas" in list of Objects
 ** Severe  ** IP: IDF line~432 Did not find "WindowMaterial:Gas" in list of Objects
 ** Severe  ** IP: IDF line~438 Did not find "WindowMaterial:Glazing" in list of Objects
 ** Severe  ** IP: IDF line~454 Did not find "WindowMaterial:Glazing" in list of Objects
 ** Severe  ** IP: IDF line~469 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~479 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~489 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~499 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~509 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~519 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~529 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~539 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~549 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~559 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~569 Did not find "Material" in list of Objects
 ** Severe  ** IP: IDF line~580 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~586 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~591 Did not find "Material:NoMass" in list of Objects
 ** Severe  ** IP: IDF line~598 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~603 Did not find "Material:NoMass" in list of Objects
 ** Severe  ** IP: IDF line~610 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~616 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~622 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~629 Did not find "Construction" in list of Objects
 ** Severe  ** IP: IDF line~634 Did not find "HeatBalanceAlgorithm" in list of Objects
 ** Severe  ** IP: IDF line~640 Did not find "ShadowCalculation" in list of Objects
 ** Severe  ** IP: IDF line~642 Did not find "SurfaceConvectionAlgorithm:Inside" in list of Objects
 ** Severe  ** IP: IDF line~643 Did not find "SurfaceConvectionAlgorithm:Outside" in list of Objects
 ** Severe  ** IP: IDF line~644 Did not find "ZoneCapacitanceMultiplier:ResearchSpecial" in list of Objects
 ** Severe  ** IP: IDF line~646 Did not find "Building" in list of Objects
 ** Severe  ** IP: IDF line~655 Did not find "GlobalGeometryRules" in list of Objects
 ** Severe  ** IP: IDF line~656 Did not find "Zone" in list of Objects
 ** Severe  ** IP: IDF line~671 Did not find "ZoneInfiltration:DesignFlowRate" in list of Objects
 ** Severe  ** IP: IDF line~685 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~699 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~713 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~727 Did not find "FenestrationSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~742 Did not find "Zone" in list of Objects
 ** Severe  ** IP: IDF line~757 Did not find "ZoneInfiltration:DesignFlowRate" in list of Objects
 ** Severe  ** IP: IDF line~771 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~785 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~799 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~813 Did not find "FenestrationSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~828 Did not find "Zone" in list of Objects
 ** Severe  ** IP: IDF line~843 Did not find "ZoneInfiltration:DesignFlowRate" in list of Objects
 ** Severe  ** IP: IDF line~857 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~871 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~885 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~899 Did not find "FenestrationSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~914 Did not find "Zone" in list of Objects
 ** Severe  ** IP: IDF line~929 Did not find "ZoneInfiltration:DesignFlowRate" in list of Objects
 ** Severe  ** IP: IDF line~943 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~957 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~971 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~985 Did not find "FenestrationSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~1000 Did not find "Zone" in list of Objects
 ** Severe  ** IP: IDF line~1015 Did not find "ZoneInfiltration:DesignFlowRate" in list of Objects
 ** Severe  ** IP: IDF line~1029 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~1043 Did not find "BuildingSurface:Detailed" in list of Objects
 ** Severe  ** IP: IDF line~1060 Did not find "WindowProperty:FrameAndDivider" in list of Objects
 ** Severe  ** IP: IDF line~1086 Did not find "Schedule:Year" in list of Objects
 ** Severe  ** IP: IDF line~1091 Did not find "Sizing:Parameters" in list of Objects
 ** Severe  ** IP: IDF line~1097 Did not find "Output:Table:SummaryReports" in list of Objects
 ** Severe  ** IP: IDF line~1115 Did not find "OutputControl:Table:Style" in list of Objects
 ** Severe  ** IP: IDF line~1117 Did not find "Output:EnvironmentalImpactFactors" in list of Objects
 ** Severe  ** IP: IDF line~1120 Did not find "EnvironmentalImpactFactors" in list of Objects
 ** Severe  ** IP: IDF line~1129 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1130 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1131 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1132 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1134 Did not find "OutputControl:IlluminanceMap:Style" in list of Objects
 ** Severe  ** IP: IDF line~1138 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1139 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1140 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1141 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1142 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1143 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1144 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1145 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1146 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1147 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1148 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1149 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1150 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1151 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1152 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1153 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1154 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1155 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1156 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1157 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1158 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1159 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1160 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1161 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1162 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1163 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1164 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1165 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1166 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1167 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1168 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1169 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1170 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1171 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1172 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1173 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1174 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1175 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1176 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1177 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1178 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1179 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1180 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1181 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1182 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1183 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1184 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1185 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1186 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1187 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1188 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1189 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1190 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1191 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1192 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1193 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1194 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1195 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1196 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1197 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1198 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1199 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1200 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1201 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1202 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1203 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1204 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1205 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1206 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1207 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1208 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1209 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1210 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1211 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1212 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1213 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1214 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1215 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1216 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1217 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1218 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1219 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1220 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1221 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1222 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1223 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1224 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1225 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1226 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1227 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1228 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1229 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1230 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1231 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1232 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1233 Did not find "Output:Meter" in list of Objects
 ** Severe  ** IP: IDF line~1234 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1235 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1236 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1237 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1238 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1239 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1240 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1241 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1242 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1243 Did not find "Output:Variable" in list of Objects
 ** Severe  ** IP: IDF line~1245 Did not find "Output:Surfaces:Drawing" in list of Objects
 ** Severe  ** IP: IDF line~1246 Did not find "Output:Surfaces:List" in list of Objects
 ** Severe  ** IP: IDF line~1247 Did not find "Output:Constructions" in list of Objects
 ** Severe  ** IP: IDF line~1248 Did not find "OutputControl:ReportingTolerances" in list of Objects
 ** Severe  ** IP: IDF line~1249 Did not find "Output:Diagnostics" in list of Objects
 ** Severe  ** Possible incorrect IDD File
 **   ~~~   ** Possible Invalid Numerics or other problems
At line 926 of file /home/el/EnergyPlus/src/Transition/CreateNewIDFUsingRulesV8_7_0.f90
Fortran runtime error: Index '0' of dimension 1 of array 'idfrecords' below lower bound of 1

```

How do I solve it?

**Comment by mjwitte** [comment] 2019-09-20 17:04
@LorenzoBottaccioli These errors suggest that the V8-6-0-Energy+.idd file is empty. Check the contents.

**Comment by Myoldmopar** [comment] 2019-09-20 17:09
I can confirm that the transition for 8.6-8.7 works for me using the 5ZoneAirCooled.idf example file on both Mac and Linux.  I agree, it seems like something went wrong with your 8.6 IDD file that should've been packaged up with your install.  If you see that the IDD has contents, and it still fails, please zip up the 8.6 IDD, 8.7 IDD, and your defect file and post them here so we can continue to investigate.  It would also be helpful to provide more information such as the items that were listed in the [issue template](https://github.com/NREL/EnergyPlus/blob/develop/.github/issue_template.md), including platform (Ubuntu) version and EnergyPlus version.

**Comment by LorenzoBottaccioli** [comment] 2019-09-23 16:43
Hi @Myoldmopar ,

Here you find the requested files. [idf_idd_error.zip](https://github.com/NREL/EnergyPlus/files/3643192/idf_idd_error.zip) I'm currently working with EnergyPlus, Version 9.0.1-bb7ca4f0da installed on Ubuntu 18.04.3 LTS Release 18.04 Codename:	bionic.

**Comment by jmarrec** [comment] 2020-10-19 10:34
I'm confused by the files in the zip. The IDF file is already at Version 9.0?! Also, the comment lines from Design Builder are interesting...

```
(py38)julien@7514 (master *%=)$ head -n10 5zone.idf 
! *** EVALUATION SOFTWARE GENERATES COMPRESSED IDF - TO OBTAIN READABLE IDF PLEASE PURCHASE A LICENCE ***
! File generated by DesignBuilder - 5.5.0.012 22/01/2019 - 18:10:33
! Source file: C:\Users\Marco\Desktop\5zone.dsb

  Version,9.0;

  RunPeriod,
    Senza titolo (01-01:31-12),  !- Name
    1,                       !- Begin Month
    1,                       !- Begin Day of Month
```

@LorenzoBottaccioli I know we're late to the party here, but do you still have this problem? can you provide your 8.6 file? 

I'm going to close this issue for now, but if you can supply more information to be able to reproduce I'll gladly reopen it.

**Closed as completed by jmarrec** 2020-10-19 10:34 UTC

**Comment by LorenzoBottaccioli** [comment] 2020-10-31 17:22
Here the 8.6 idf file that I have sued for test
[test.zip](https://github.com/NREL/EnergyPlus/files/5469484/test.zip)

**Comment by jmarrec** [comment] 2020-11-02 15:32
I took your file, and ran the IDFVersionUpdater from EnergyPlus 9.4.0 on Ubuntu 18.04.

```
$ sudo /usr/local/EnergyPlus-9-4-0/PreProcess/IDFVersionUpdater/
```

The file transitionned properly. The audit is clean.

```bash
$ cat test_transition.audit 

Conversion 8.6 => 8.7
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf

Conversion 8.7 => 8.8
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf

Conversion 8.8 => 8.9
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf

Conversion 8.9 => 9.0
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf
   ** Warning ** Run period start day of week USEWEATHERFILE option has been removed, start week day is set by the input start date.

Conversion 9.0 => 9.1
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf

Conversion 9.1 => 9.2
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf

Conversion 9.2 => 9.3
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf

Conversion 9.3 => 9.4
 Starting new Transition.audit
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Processing IDF -- /home/julien/Software/Others/EnergyPlusDevSupport/DefectFiles/7000s/7514/test.idf
```

here is the resulting IDF file from 9.4


[test.idf.txt](https://github.com/NREL/EnergyPlus/files/5476099/test.idf.txt)

**Comment by LorenzoBottaccioli** [comment] 2020-11-02 18:20
the problem it is related to the IDFversionupdaters of the 9.0 version

**Comment by jmarrec** [comment] 2020-11-02 19:03
Yes, and that's already filed (and closed) as https://github.com/NREL/EnergyPlus/issues/7010 most likely.

Use the transition utilities from ep940 for eg. You can copy them and the IDDs in your existing 9.0 install if you insist on only having that version installed.
