### ISSUE TITLE
FuelFactors: Units of Measures and Energy per Unit Factor are never used

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9493] opened 2022-06-16 07:09 UTC
Issue overview
--------------
IDD:

```
FuelFactors,
[...]
  A2,   \field Units of Measure
  N1,   \field Energy per Unit Factor
```

 https://github.com/NREL/EnergyPlus/blob/f39484f14fe4df6874c0334c90d79916767cf6ad/src/EnergyPlus/PollutionModule.cc#L260

As you can see, `cAlphaArgs(2)` is never used (this is the Units of Measure), and neither is `rNumericArgs(1)` (Energy per Unit Factor)

Either use them or remove them from the IDD

**Additional issue:**

Wrong index due to copy paste here: https://github.com/NREL/EnergyPlus/blob/f39484f14fe4df6874c0334c90d79916767cf6ad/src/EnergyPlus/PollutionModule.cc#L248-L251 Should be `3` in the `if`

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment] 2022-06-23 20:32
Confirmed that these two fields `rNumericArgs(1)` and `cAlphaArgs(2)` in the `GetPollutionFactorInput()` function for `FuelFactors` object are never used. Also confirmed the defect in the same get input function for `EnvironmentalImpactFactors` object.

**Comment by Nigusse** [comment] 2022-06-23 20:44
Also while checking idd of the `FuelFactors` object, I see that there is no easy way to enter a default value to `Source Energy Factor` input field since the default values vary by fuel type. These default values of `source-energy-factors` are hard wired in the code.

Note that these factors do change with time as the diversity of power generation plants are changing. For example, the electricity source-to-site energy currently used by EnergyPlus is 3.167, the most recent value reported for the USA by [EPA](https://portfoliomanager.energystar.gov/pdf/reference/Source%20Energy.pdf) is 2.80. And historical values from EPA are [here](https://energystar-mesa.force.com/PortfolioManager/s/article/What-are-the-historical-Site-to-Source-Conversion-factors).

I suggest adding a table of default values that are currently used by EnergyPlus the input-output documentation [here](https://github.com/NREL/EnergyPlus/blob/f39484f14fe4df6874c0334c90d79916767cf6ad/doc/input-output-reference/src/input-for-output.tex#L750-L752) for easy reference.

**Comment by RKStrand** [comment] 2022-07-29 15:43
@jmarrec @Nigusse Are either one of you planning to work on this?  If not, I will take this on and follow all of your recommendations.  That includes: getting rid of the unused inputs in the two objects, fixing the typo in line 249 of the PollutionModule.cc file, and adding the table which @Nigusse recommended from the EPA to the IO Ref.  However, if one of you is already or planning on working on it, I'll leave it alone.  Thanks!

**Comment by jmarrec** [comment] 2022-07-29 18:26
I (as rigorously as I can) assign myself on issues I plan to work on so the intent is clear, which I didn't here, so all yours @RKStrand !

**Comment by Nigusse** [comment] 2022-07-29 19:02
@RKStrand I have no plan to work on this issue.

**Comment by RKStrand** [comment] 2022-07-29 19:34
@jmarrec @Nigusse Thanks to both of you for getting back to me here.  I know that most of us tend to be very clear with assigning ourselves to items--I just wanted to make sure I didn't swoop in and take something someone was planning on work on.  I will assign this to myself and proceed with what I outlined and may ask one of you to review that the work is what you anticipated.  Thanks again!

**Closed as completed** 2022-08-04 14:50 UTC
Labels: Defect
