### ISSUE TITLE
Repeated ControlCompOutput Max Iterations Exceeded for Rad/Conv HW Baseboard

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5884] opened 2016-09-27 12:53 UTC
## Issue overview

When checking in the new simple chilled ceiling model, it was noted that the input files were resulting in over 30 ControlCompOutput errors for max iterations were exceeded for the annual run of the main simple chilled ceiling model.  The problem appears, however, to be completely unrelated to the chilled panel model though because when the panel is turned off the error messages do not disappear.  While the size of the loads for which the baseboard has trouble converging are all small, it seems like this should not be happening and needs to be investigated further to discover the problem and correct it as needed.  The problem can been seen in the 5ZoneCoolingPanelBaseboard.idf file in the test suite.
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus: V8.6
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ x ] Defect file added (already existing in the test suite 5ZoneCoolingPanelBaseboard.idf)
- [x] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment] 2017-06-26 03:30
@mjwitte Just ran this using release version 8.7...and I'm not seeing these error messages.  Did they magically disappear or am I missing something here?

**Comment by RKStrand** [comment] 2017-06-26 14:33
@mjwitte Nevermind...forgot that it was something that happened during an annual run.  I'm seeing the issue now.  On another note, I see that this is part of GitHub Issue #5823.  I think that is my mistake since based on the number the one you entered would have gone in first.  Could we maybe keep this as a separate issue and eliminate if from 5823? What do you think?

**Comment by RKStrand** [comment] 2017-06-26 15:49
@mjwitte Two things going on here.  First, the tolerance is set somewhat low and there are some cases when the flow rate is fairly low that are just barely missing the cut-off.  Second, the rest of the cases where max iterations is encountered, the flow rate is incredibly low--just above 10-9 kg/s which translates to roughly 1mg/hour.  That is really low and is a result of a choice in the code to set the tolerance for flow at 10-9.  So, many of these cases have such a low flow rate that it isn't even really possible.

So, here is what I am doing to resolve this:
1. Adjust the input file tolerance on not just the cooling panel file but all of the other files containing baseboard to 0.002 from 0.001.  The choice of 0.001 is not based on anything other than a guess so adjusting this probably won't have much of an impact.
2. Change the low flow rate tolerance to 2.7x10-7 which is equivalent to 1 gram/hour.  One drop of water per hour seems pretty insignificant so anything less than that should just be zeroed out.

Making these changes eliminated all of the error messages in the cooling panel input file and probably will get rid of any others as well.  Now what changes this might have in other input files is unknown but hopefully it won't be a major issue...

**Comment by RKStrand** [comment] 2017-06-26 16:11
@mjwitte I do realize that messing with the flow rate tolerance is dangerous and might result in a huge number of input files with changes in them.  So, I will test that and see what happens.  The solution presented by the 4 Pipe Fan Coil seems to be to bring all of the control logic into the routine and then customize it.  That seems like a bad idea in general because that would mean control code all over the place in the code--stuff that should be pretty similar for many things.

**Comment by RKStrand** [comment] 2017-06-26 16:52
@mjwitte After more thought and wanting to avoid major code rewrites and also a testing nightmare from the standpoint of a unit test and diffs in a lot of files, I came up with an alternative that limits the potential changes to the baseboard files only and still takes care of the max iteration errors (I think).

**Comment by mjwitte** [comment] 2017-06-28 14:01
@RKStrand Seems like changing inputs just covers up an underlying problem with the solution algorithm.  Unless the \minimum is also changed, a user could put in the 0.001 and the problem could reappear.  @rraustad did the fancoil changes to deal with this, and @lgu1234 did some other changes related to the regulafalsi searches, and @rraustad has another pending PR #6176 that attempts to move away from ControlCompOutput to regulafalsi for water coils.  So, they may have a suggestion here on the best path forward.

**Comment by rraustad** [comment] 2017-06-28 14:45
ControlCompOutput (half step solution method) is no longer used in the fan coil model (except in a comment that I just found).

    // METHODOLOGY EMPLOYED:
    // If unit is on, calls ControlCompOutput to obtain the desired unit output

Regarding very low flow rates, I have also seen max iteration warnings with RegulaFalsi. This is hard to avoid if the residual is based on a fraction of the magnitude. I have started adding this to the residual calculation. Basically, it's a percentage for low loads, and a fraction otherwise.

    // Calculate residual based on output magnitude
    if ( std::abs( QZnReq ) <= 100.0 ) {
        Residuum = ( QUnitOut - QZnReq ) / 100.0;
    } else {
        Residuum = ( QUnitOut - QZnReq ) / QZnReq;
    }

The changes in PR #6176 probably could be used throughout the code. At this point, my changes have increased performance tests time by a factor of 2. I think this is because the water coil controller is not included in the mass flow rate iterations of the OA controller, and with my changes the extra calls to calculate water flow rate as mass flow rate changes are included (and at this point I think they need to be included). This isn't an apples to apples comparison when looking at the performance test times. I think I need to fix that issue using the existing solution method so I can fairly compare impact on execution speed.

To the point, I think using RegulaFalsi is a better choice over ControlCompOutput since it converges much faster. For this reason, the example files using water coils and/or baseboards would also run much faster.

**Comment by RKStrand** [comment] 2017-07-05 12:29
@rraustad @mjwitte Some food for thought regarding the on-going conversation...

ControlCompOutput already does the "Residuum" calculation outlined above as part of its standard calculation.  This doesn't necessarily fix the problem of low flow in the radiant/convective baseboard.  That is why I tried some additional logic that figures out when it is actually a very low flow situation and it basically says--hey, this flow is so ridiculously low that you need to just zero it out and move on.  Of the convergence not achieved errors I was seeing, this low flow check eliminated probably 90% of the messages (meaning 90% of the problem was when the flow was less than one drop of water per hour and it couldn't get to a solution).

Has anyone ever really looked at the "tolerance" term and its relation to iteration?  We have a tolerance of 0.001 in all sorts of input files, but is that a "good number" given our iteration scheme(s)?  Any thoughts on what number, if any, of acceptable iteration errors is acceptable for an input file?

I am pausing any further work on this until this discussion progresses to a point where we have some consensus on this...

**Comment by mjwitte** [comment] 2017-07-05 13:36
@RKStrand For this particular component, is the tolerance applied as a fraction of the current load or as a fraction of the design load or flow rate?  I would be ok with removing the tolerance as a user input altogether (not sure why these were exposed as inputs way back when).  But, either way, we have precedent in other parts of the code for setting a flow to zero if it is less than VerySmallMassFlow(sp?), so can we apply that concept here to cut this off?

**Comment by RKStrand** [comment] 2017-07-05 15:30
@mjwitte @rraustad  From my understanding of the code, the radiant/convective baseboard (along with everything else that uses ControlCompOutput), uses tolerance in the following way:

First, it calculates Denom (with slight mods for Action of component):
		Denom = sign( max( std::abs( QZnReq ), 100.0 ), QZnReq );

Then, it calculates the "tolerance" using the following:
			ZoneController.SensedValue = ( LoadMet - QZnReq ) / Denom;

Convergence is essentially when the "sensed value" is less than the tolerance.  In most cases, this seems to be fine.  However, if you aren't able to get close to QZnReq for whatever reason, then you run into problems.  For low load cases, this can force a fairly tight situation which is why the "Denom" term was added quite a while ago (not sure how long ago--10-15 years maybe?).

What appears to be happening with the rad/conv baseboard is that a low flow is still producing a load of some kind but clearly the flow is very low in these situations.  So, as the flow rate still bounces around a bit, LoadMet changes but it doesn't approach QZnReq fast enough to meet the tolerance criteria.  My fix flagged the very low flow cases in the baseboard simulation to zero it out if it went below the 1 gram per hour threshold and then trapped the zeroed out flow case in ControlCompOutput.  This seemed fairly reasonable and fixed 90% of the tolerance issues.

As for the tolerance parameter, I understand both sides of this issue.  Pro-leaving it as an input are those research types who want to look at this sort of stuff and those who want to give the users total control.  Another thought is what option does the user have to get rid of these error messages if they have no dial to tweak to get rid of them.  The pro-getting rid of it camp sees that it doesn't have much meaning to 99.9% of users and is a somewhat arbitrary parameter.  Why ask the users for something that they don't have a good handle on and is sort of specific to EnergyPlus?  Maybe some of the others on the team who have been around for a while can shed more light on this.  I think I initially had some part in the implementation of the "Denom" feature but I could easily be remembering wrong and I haven't had any other real input into the "black box" that is ControlCompOutput.

As for the issue of users changing the parameter and getting convergence tolerance warning messages, I don't feel that is a huge issue.  The error messages and convergence tolerances are a good thing and allow the users to evaluate their situation with more information.  It's pretty straight-forward that if users want extremely tight tolerance convergence, they get long execution time and they may run into situations where the solution doesn't converge.

**Comment by mjwitte** [comment] 2017-07-05 16:04
> As for the issue of users changing the parameter and getting convergence tolerance warning messages, I don't feel that is a huge issue. The error messages and convergence tolerances are a good thing and allow the users to evaluate their situation with more information. It's pretty straight-forward that if users want extremely tight tolerance convergence, they get long execution time and they may run into situations where the solution doesn't converge.

a)  I don't see 0.001 (which I interpret as 0.1%) to be extremely tight.
b) If the algorithm can't handle 0.001, then it shouldn't be the default.
c) Users shouldn't need to mess with these to get rid of convergence problems.
d) What order of magnitude are you seeing for `SensedValue` here?  
e) Perhaps we need to establish a parameter for "VerySmallLoad = 1.0 [W] and call it converged if ( LoadMet - QZnReq )<VerySmallLoad?  Or maybe zone hot water components shouldn't even bother to call ControlCompOutput if QZnReq is < SmallLoad=10W?  Fishing here for values, but there must be some better way to solve this other than ratcheting down the absolute tolerance as the load gets smaller and smaller.  What's the point of the max( QZnReq,100)?  @rraustad ?
f) If the issue is the general methodology of ControlCompOutput, and not specific to the baseboard, then feel free to reassign this to @rraustad

**Comment by Myoldmopar** [comment] 2017-11-28 22:16
Addressed via #6397

**Closed as completed by Myoldmopar** 2017-11-28 22:16 UTC
Labels: SeverityMedium, Defect, PriorityLow
