### ISSUE TITLE
EAp2-4/5. Demand data taken from Design Days instead of from Annual Peak

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#5672] opened 2016-05-20 16:02 UTC
## Issue overview

This happens for Interior Lighting (not checked the rest of the rows) in EAp2-4/5 table:
- Electric demand value seems to be taken from Design Day at time of peak. At least it matches the value in _Peak Heating Sensible Heat Gain Components_ table. Depending on the schedule value at that time (if <1) it will not match the required demand value.
- According to LEED (from a review) demand should match Annual peak value. E+ result from _Anual and Peak Values table_ seems to fulfill this requirement.

It also happens for other rows as I find zero values for Demand when Electricy Use is not zero.

**Comment by JasonGlazer** [comment] 2016-10-07 19:37
@ecoeficiente do have a specific file that demonstrates this difference that I can use as a test file?

**Comment by ecoeficiente** [comment] 2016-10-10 12:19
Sorry for the delay, I've missed this among all Github emails I get... I got that in different LEED models which are quite big and not adequate for your tests.
I've randomly picked a file from the examples: _5ZoneBoilerOutsideAirReset.idf_, changing it to annual simulation and I get 9389.21W for space cooling electric demand in EAp2-4/5. That value matches _Demand End Use Components Summary_ Report which I think gathers the peak moment for each use (electricity, natural gas) and then the value for each category (e.g. cooling) which must not necessarily be the peak for that category.
If you go to _Energy Meters_ report you will see 31220.43W for cooling maximum value instead.

Note: I've done this with v8.5

**Comment by JasonGlazer** [comment] 2016-10-10 17:17
@ecoeficiente I am not getting those numbers, what weather file are you using?

**Comment by ecoeficiente** [comment] 2016-10-11 05:18
Yes, sorry. https://energyplus.net/weather-location/europe_wmo_region_6/ESP//ESP_Barcelona.081810_IWEC

**Comment by JasonGlazer** [comment] 2016-10-11 13:48
@ecoeficiente I cannot reproduce your numbers exactly with that file but I get in the EAp2-4/5. Performance Rating Method Compliance table for Space Cooling electric demand of 9319.11 and in the Energy Meters report in the Annual and Peak Values - Cooling a value of 31257.40 for all three "PlantLoop" numbers. I am not sure how these are inconsistent. I think you might be talking about the value in the Annual and Peak Values - Electricity table which for the Cooling:Electricity meter says 9327.56. That is slightly different than the EAp2-4/5 value but not unreasonable since the EAp2-4/5 value is from the peak demand for the entire building and the Cooling:Electricity is the peak for just that specific meter. 

Maybe I am not understanding, could you explain further.

**Comment by MatthewSteen** [comment] 2016-10-11 15:00
I'm actually seeing table EAp2-4/5 report the _minimum_ demand (relative to the building as in #5559) from the BUILDING ENERGY PERFORMANCE - ELECTRICITY PEAK DEMAND table. This appears to just be affecting the Interior Lighting end use.

**Comment by JasonGlazer** [comment] 2016-10-11 15:53
@MatthewSteen I have not heard that the EAp2-4/5 is reporting minimum demands before. I don't see a specific building associated with #5559. What input file is showing that?

**Comment by MatthewSteen** [comment] 2016-10-11 16:30
@JasonGlazer I have two 8.5 models that show this. The issue in #5559 and [#4588](https://github.com/NREL/EnergyPlus/issues/4588#issuecomment-72663433) is that the LEED table reports the peak demand for each end use at the building peak from the `BUILDING ENERGY PERFORMANCE - ELECTRICITY PEAK DEMAND` table not the peak for that end use from the `Energy Meters` report, which is what USGBC is looling for.

![image](https://cloud.githubusercontent.com/assets/8397034/19279204/ae53f732-8f9d-11e6-8ea5-274d5b6852f3.png)

![image](https://cloud.githubusercontent.com/assets/8397034/19279191/9d8786bc-8f9d-11e6-945e-ddd9c58f3a9f.png)

**Comment by JasonGlazer** [comment] 2016-10-11 16:36
That is weird. Would you please email me the files?

**Comment by eringold** [comment] 2017-04-25 22:17
@JasonGlazer I'm seeing this happen with ExteriorLights: .

![leeddemandextlight](https://cloud.githubusercontent.com/assets/10799524/25410118/36316620-29d2-11e7-84e7-4f8e35e525ea.png)
![annualandpeakextlight](https://cloud.githubusercontent.com/assets/10799524/25410195/9317ad04-29d2-11e7-8348-adf94accc814.png)

Would you like that file?

**Comment by MatthewSteen** [comment] 2017-08-04 17:13
@JasonGlazer I'm seeing this in the `Receptacle Equipment` row too.

**Comment by JasonGlazer** [comment] 2017-09-08 12:10
This should also be resolved by #6295

**Comment by mjwitte** [comment] 2017-09-19 00:13
Closed via #6295

**Closed as completed by mjwitte** 2017-09-19 00:13 UTC
Labels: Defect, SeverityHigh, PriorityLow
