### ISSUE TITLE
Trying to run TestRuntime.py sample gives 'expected CFunctionType instance instead of int' error

### ISSUE THREAD

**Issue by joproulx** [NREL/EnergyPlus#9613] opened 2022-08-24 01:19 UTC
Issue overview
--------------
Trying to run for the first time one of your [python code sample TestRuntime.py](https://github.com/NREL/EnergyPlus/blob/develop/tst/EnergyPlus/api/TestRuntime.py) and I get this error:

```
Traceback (most recent call last):
  File "TestRuntime.py", line 89, in <module>
    api.runtime.callback_end_system_sizing(state, common_callback_handler)
  File "C:\trusted\Programs\EnergyPlusV22-10\pyenergyplus\runtime.py", line 538, in callback_end_system_sizing
    self.api.callbackEndOfSystemSizing(state, cb_ptr)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected CFunctionType instance instead of int
```
![image](https://user-images.githubusercontent.com/1434190/186296383-54c10620-db07-45c2-b010-82619b12025b.png)

Any ideas on how to solve this? Let me know if I can provide more info. Thanks in advance!

### Details
Some additional details for this issue:
 - OS: Windows 11
 - Version of EnergyPlus: 22.1.0
 - Version of Python: Tried with 3.8 and 3.10

**Comment by Myoldmopar** [comment] 2022-08-24 17:13
@joproulx thanks for reporting this.  I have some other API examples beyond the TestRuntime.py example in the repo.  Can you email me at   edwin dot lee at nrel dot gov  ?  We can try to work through this problem and also show you some of the other examples.

**Comment by joproulx** [comment] 2022-08-25 01:15
Thanks for the reply @Myoldmopar. I did send you an email, but just for info, I tried other samples and some were working fine. For the `TestRuntime.py`, if I comment these 3 callback registrations, then the sample run correctly.

![image](https://user-images.githubusercontent.com/1434190/186551312-442b0f2f-91ad-497f-9f9e-ece3681f907e.png)

Do you have the same behavior on your side?

**Comment by jmarrec** [comment] 2022-09-06 15:23
@Myoldmopar @joproulx This is because you're using the TestRuntime.py from develop (22.2.0-IOFreeze) with the API from 22.1.0.

This has been fixed since then (by @Myoldmopar actually...): https://github.com/NREL/EnergyPlus/pull/9499.
This issue actually is a duplicate of https://github.com/NREL/EnergyPlus/issues/9481

I have confirmed that:

* Using https://github.com/NREL/EnergyPlus/blob/v22.1.0/tst/EnergyPlus/api/TestRuntime.py with 22.1.0 official works
* Using https://github.com/NREL/EnergyPlus/blob/4872b63adc2630585108b0c9d0c5ebc492ca29e3/tst/EnergyPlus/api/TestRuntime.py with develop works

**Closed as completed by jmarrec** 2022-09-06 15:23 UTC
Labels: UnconfirmedDefect
