### ISSUE TITLE
Low Temperature Radiant Variable Flow cannot meet the load

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4393] opened 2014-08-19 14:52 UTC
Helpdesk Ticket 9591

User Comment and MJW Comment

> I tried with auto sizing and it seems to me that the system does not
 > try to meet the load and the room air temperature can go as high as 40
 > C or as low as 10 C. I set both thermostat and heating and cooling
 > control in the radiant system itself and it doesnt help. I also tried
 > with the example file RadLoHydrHeatCool for a whole year simulation
 > and it seems to have the same problem. Could you please verify this
 > system is properly working? 
 > Thanks.

 I found a few inconsistencies in the example file (sizing;plant temps did not match the loop setpoint manager setpoints) and you probably need to turn off the condensation controls in the radiant system. This will help, but it still doesn't seem to size adequately. Getting up to 30C or so when the setpoints are 26, but it does have a throttling range of 2C which account for some of that. But looking at the flow rates, the radiant system flow is maxing out.
 Mike

MJW Follow-up comment
Doesn't seem that this is sizing properly. Ask MJW for test file that has some things fixed. So, the example file needs some fixing plus the autosizing for this needs to be looked at.

**Comment by RKStrand** [comment] 2016-08-23 16:52
@mjwitte @BobHenninger So, I am looking at this defect and I clearly see the problem, but I don't think that the problem is actually in the code itself.  I think the problem is more in the input files and a need for additional documentation in the IO Reference to give some guidance for using autosizing with a radiant system.  Inside the code, based on what I saw during debugging runs, it is picking up the correct load to autosize on and it is making a correct calculation for a flow rate.  The problem is that a radiant system is not that simple.  First, you have a time lag as the energy has to heat-up/cool-down the slab.  Then, while the load the water loop experiences plays a role (and that is what is used to auto-size), the actual impact on the space is not what the water loop experiences but rather what happens at the top of the slab.  What happens at the top of the slab is dependent on everything else going on in the space.  It is relatively easy to autosize a forced air system because everything is based on the load on the air.  In a radiant system, the load is different just like the resulting comfort is different.  The problem is that I don't think there is a way to back out sizing information in an equation because of the time lag and the rest of the zone heat balance.  Just like the heat balance is somewhat iterative for a radiant system, the autosizing sort of has to be as well.  This is not surprising to me because as I have constructed radiant input files over the years getting the temperatures or comfort in the zones correct has always been an iterative process.  In order for this to work, I think auto-sizing these radiant systems will also have to be iterative.

After doing a bunch of test runs using variations of RadLoTempHydrHeatCoolAuto.idf, what I am finding is that while the design delta T for the plant sizing plays a role, what is of critical importance to getting the sizing correct is: turning off the condensation controls and choosing a chilled water temperature that will work for the particular application.  For example, in the current version of RadLoTempHydrHeatCoolAuto.idf, the chilled water temperature has been set at 10C.  This was done to try to avoid condensation as much as possible.  However, this system simply cannot meet the load because this water temperature is too high.  It doesn't matter what the flow in the system is because no matter how high you push that value by dropping the delta T, you still end up with a temperature at the source location of around 11C and this isn't low enough to meet the load and keep the zone at a reasonably comfortable temperature (air temps max out over 31.3C and comfort at a PMV of 1.68 in the West Zone).  I tried adjusting the design delta T for the plant, but you don't get a whole lot of change in the results.  If you go to a higher delta T, you get a lower flow rate.  If you go to a lower delta T, you get a higher flow rate, but since the delta T is also dropping the two trends tend to wash each other out.

Now, if I change the chilled water loop temperature, I start to see a shift in the resulting air temperature in the zones.  Here is a summary of what I am seeing for the west zone as I change the chilled water temperature:

Loop Temp      Max MAT      Max PMV
10.0                     31.3                1.68
6.67                    26.6                1.32
5.0                      28.8                1.15
1.0                       27.0                0.78

The west zone is the worst of the three in this input file.  If you want to see all three zones, I can attach the csv files.  You would see the same issue with heating if one used a very low water temperature for the plant hot water loop, but that generally isn't something people do unless they are using solar hot water and they don't have to worry about condensation turning the system off.

What I am taking away from this is that the problem is that this particular example has high internal gains (over 7W/sq.ft. plus people) and the radiant system does not have enough capacity potential unless we lower the temperature of the slab.  That's really the only way to get more output out of the system and the only way to do that is lower the chilled water temperature.  Pushing more water flow through the slab gets minimal results--like changing the temperature at the source from 11.4 to like 11.3.  That doesn't mean that there is anything wrong with the sizing routine.  It is doing what it needs to do to figure out the flow rate when autosizing is requested.

Here is what I propose to address this issue:
1. Adjust any of the low temperature radiant system input files that use autosizing to get comfort that keeps the PMV at or below +1.0 as a max during "occupied hours" by adjusting the loop temperature and turning off condensation controls.  I think there are only two files that use autosizing, but I will double check to make sure that I catch any radiant file in the test suite that uses autosizing gets adjusted to produce temperatures that are comfortable.
2. This needs to be documented so that users are aware of this particular quirk of a radiant system.  As this discussion might be a bit longer than one would typically see in the IO Ref, I think what is probably best is to put some comments in the IO Ref in all of the radiant systems noting that radiant systems are special cases of autosizing and then refer them to a new Eng Ref section that I will add.  That way, both of the low temp water based radiant systems can refer to that discussion rather than repeating it in all of them.  The low temperature electric radiant system shouldn't have this problem.

Ok, so that is a long winded discussion of what I believe the problem is and what I think is a "solution" for this.  What are your thoughts on this?

**Comment by mjwitte** [comment] 2016-08-23 17:09
@RKStrand Sounds like a good plan.  You might consider putting the longer discussion in Tips and Tricks instead of Engineering Ref.  As long as it's referenced in the I/O Ref, either one should work.

**Comment by RKStrand** [comment] 2016-08-23 18:07
@mjwitte Putting that longer discussion in Tips and Tricks sounds like a much better idea than putting it in the Engineering Reference--I will do that instead.  Thanks for the suggestions.

**Comment by RKStrand** [comment] 2016-09-05 17:11
@mjwitte Well, I did actually uncover a bug in the code that relates to this stuff but is not really causing any problems here.  The user noted issue is really still an input problem and I have fixed all of the autosize low temperature radiant input files that use autosizing.  I noticed an error message that did not make any sense.  There was a problem both with the actual error message as well as the fact that is was produced at all for an autosizing case (involves calculating a pump efficiency but you can't check that right away when the pump is autosized).  Anyway, I have fixed this and will create a new unit test and wrap this up together with the other changes.

**Comment by mjwitte** [comment] 2016-09-16 22:29
Closed via #5850

**Closed by mjwitte** 2016-09-16 22:29 UTC
Labels: EnergyPlus, Priority, S2 - Medium
