### ISSUE TITLE
Pool not receiving heat when on dedicated PlantLoop

### ISSUE THREAD

**Issue by KWSL** [NREL/EnergyPlus#6713] opened 2018-04-04 17:41 UTC
[Pool Defect Files.zip](https://github.com/NREL/EnergyPlus/files/1876873/Pool.Defect.Files.zip)
Issue overview
--------------
I am working on modeling a pool in a building where the pool will have a dedicated heat source, and thus needs a dedicated PlantLoop.  I noticed while working on the model that the dedicated PlantLoop does not turn on, and the pool does not receive heat.  When the pool is on a PlantLoop that has other coils and loads, it receives heat, and setpoint temperature is maintained, although it is unclear whether this is only for hours when there are other loads on the PlantLoop.

The example file "5ZoneSwimmingPool.idf" includes the pool on a hot water loop that also has other loads.  I created a modified version of the example file where the  pool has a dedicated PlantLoop (attached "5ZoneSwimmingPool_2_Loop.idf").  This file shows no flow to the pool, and the pool receives no heat.  I also noticed that with this file, the heating plant and flow-rate for the Pool Hot Water Loop was autosized to 0.  I created a third file "5ZoneSwimmingPool._2_Loop_hard_size.idf" in which I hard-size the boiler, and plantloop flow, in order to make sure that the issue is not solely with the sizing algorithm.

I'm attaching the three idf files and their associated hourly output variable files.  I believe that this is a significant bug in the pool heating algorithm.

[Pool Defect Files.zip](https://github.com/NREL/EnergyPlus/files/1876749/Pool.Defect.Files.zip)
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 8.9
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2018-08-27 17:00
#6763 is a duplicate of this. Problem was fixed for v9.0 via #6765.

**Closed as completed by mjwitte** 2018-08-27 17:00 UTC
