### ISSUE TITLE
SolarShading divide by 0 error (Ticket 9351)

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4208] opened 2014-04-29 13:39 UTC
line 9035 of SolarShading.cc

TanGamma = TanProfileAngVert;
d2prime = d1 + d2 - W / TanGamma;

TanGamma is 0 here and I assume this is the profile angle of the window wrt to sun location since this file crashes only with certain weather files. 

The window seems to be in a nearly horizontal plane (e.g., skylight) yet the code has determined the window is vertical (if comments are accurate).

FenestrationSurface:Detailed, ABC%R%3:T3%haut%duplex%Est_Wall_6_0_0_0_0_0_Win,  !- Window name
   Window,                                  !- Class
   1001,                                    !- Construction Name
   ABC%R%3:T3%haut%duplex%Est_Wall_6_0_0,   !- Base surface
   ,                                        !- corresponding other window subsurface
   .5,                                      !- View Factor to Ground
   1001,                                    !- Window shading control
   1,                                       !- Frame divider name
   1,                                       !- Multiplier
   4,                                       !- Number vertices
   -59.5381971554,-788.9507581195, 10.2099990001,  !- Vertex 1
   -58.6925077837,-788.642846628, 10.2099990001,  !- Vertex 2
   -58.6925077837,-788.642846628, 12.7099990001,  !- Vertex 3
   -59.5381971554,-788.9507581195, 12.7099990001;  !- Vertex 4

if ( HorVertReveal == 1 ) { // Vertical reveal
	TanAlpha = TanProfileAngHor;
	TanGamma = TanProfileAngVert;
	CosBeta = std::abs( CosBetaLeft );
	L = Surface( SurfNum ).Height;
	d2 = InsReveal + 0.5 * GlazingThickness;
	d2prime = d1 + d2 - W / TanGamma;
	InsideRevealSolAbs = SurfaceWindow( SurfNum ).InsideRevealSolAbs;
} else { // Horizontal reveal

**Comment by JasonGlazer** [comment] 2015-12-15 18:59
@Myoldmopar are you working on this one? If not I will take a shot at fixing it.

**Comment by Myoldmopar** [comment] 2015-12-15 19:14
I am not.

**Comment by JasonGlazer** [comment] 2015-12-15 20:05
Updated test file to 8.4.0

**Comment by JasonGlazer** [comment] 2015-12-16 14:28
I ran the test file with test weather file with the release version of 8.4.0 as well as the current "develop" version of the code and neither one crashed. The code that was indicated as a problem still does not have any specific local protection for divide by zero but perhaps logic that prevents that case from occurring has been added somewhere else. 

@mjwitte, @rraustad  and @Myoldmopar Is it worth adding the following code anyway?

 If (TanGamma == 0.0) {
TanGamma = 0.000001
}

**Comment by mjwitte** [comment] 2015-12-16 14:41
Are you able to reproduce the error with the original defect file and version?  Not sure about the proposed protection.  Would like to understand the section of code better.

**Comment by JasonGlazer** [comment] 2015-12-16 15:07
Yes I just tried it, it crashes with 8.1.0.008.

**Comment by JasonGlazer** [comment] 2015-12-16 15:11
The code is at:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L8970-L8992

**Comment by mjwitte** [comment] 2015-12-16 15:12
And how about 8.2 and 8.3?

**Comment by JasonGlazer** [comment] 2015-12-16 15:45
It does not crash in 8.2 or 8.3

**Comment by mbadams5** [comment] 2015-12-16 15:55
8.2+ is C++ and I know from a previous bug I had fixed that it seems to be suppressing divide by 0 errors. I fixed a bug that caused a divide by 0 in 8.1 and lower but didn't anymore in 8.2+ although the code didn't change at all.

**Comment by JasonGlazer** [comment] 2015-12-16 15:56
A quick inspection of the entire SolarShading.cc file shows about 20 times that a variable or variable expression is used as a divisor (after the / sign) that did not have any obvious protection for protecting for the zero case. That probably means that other logic prevents from divide-by-zero situations but it could also mean that crashes occur and are not reported or crashes could occur for edge cases. 

My recommendation would be to close this issue. 

We could add a new suggestion issue to replace / with a function that protects for divide by zero throughout the entire code base (although it would carry a performance penalty).

**Comment by mjwitte** [comment] 2015-12-16 16:06
You ran this with current develop in a debug build?  Before closing this, I would want to observe what kind of values are showing up here for TanGamma with this file.

**Comment by JasonGlazer** [comment] 2015-12-16 17:32
I just ran it and looked at the values for TanGamma. The test file computes this over 40,000 times. The values are all positive with the smallest being  8.62E-05 and the largest is 32809. 99% of the values are between .001 and 1000.

**Comment by mjwitte** [comment] 2015-12-16 18:52
That's quite a range - but that's what tangent does. Looking around the shading code, I'm not seeing any limits to jump out if the profile angle is exactly zero or 90degrees.  With the age of this issue and the many changes to the code since then, I agree that we should leave it alone for now.  @Myoldmopar Any thoughts?

**Comment by Myoldmopar** [comment] 2015-12-16 19:00
![image](https://cloud.githubusercontent.com/assets/849824/11850781/9fcbb3d2-a3ec-11e5-8b9c-2e2069d06685.png)

**Closed by Myoldmopar** 2015-12-16 19:00 UTC
Labels: Defect, EnergyPlus, S2 - Medium
