### ISSUE TITLE
Using multiple SwimmingPool:Indoor objects gives unexpected results

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9797] opened 2023-01-16 16:10 UTC
Issue overview
--------------

I took this regression test: https://github.com/NREL/OpenStudio-resources/blob/1eaedc8590a23abf7d9f398d182cca5521ec2b39/model/simulationtests/swimmingpool_indoor.rb

It has 5 zones. The core zone has a swimming pool object attached to its floor, which I call "1Pool". I then added two variations:

* 2Pools: I split the floor surface of the core zone and added a second swimming pool object (by cloning the original swimming pool object and assigning it on an extra branch on the demand side of the heating loop)
* 2Pools2zones: I left the core zone swimming pool untouched, but I added a swimming pool object to the East perimeter zone

In both of these cases, one of the pools is meeting it's target pool water temperature setpoint, the other is not.

All pools have a temperature setpoint of 27°C.

![image](https://user-images.githubusercontent.com/5479063/212722581-607ea524-5570-4328-8e0f-406eee0af8e6.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 22.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9797
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment] 2023-02-05 17:22
Related bug report and IDF files here: https://unmethours.com/question/87322/multiple-swimmingpoolindoor-objects-do-not-work/?answer=87348#post-id-87348

**Comment by loooic** [comment] 2023-04-05 14:33
We detected this issue as well. Is there any news about this problem ?

Thanks a lot

**Comment by RKStrand** [comment] 2023-04-05 17:57
@loooic This is assigned to me since I am one of the authors of the swimming pool model.  I hope to look at it in the near future with a view towards having this fixed by the Version 23.2 release later this year.

**Comment by AlexandreDijoux** [comment] 2023-04-06 09:07
Hello everyone, 

The bug seems to appear with version 9.3 of EnergyPlus.  Indeed, I’ve tried to run an example with 2 swimming pools : one named “BASSIN_SPORTIF” with 28 °C for water temperature setpoint and another named “BASSIN_LUDIQUE” with 29 °C for water temperature setpoint. The simulation works properly when running the model with version 9.2 of EnergyPlus: the output “Boiler Heating Energy” is equal to the sum of “Indoor Pool Water Heating Energy” for both swimming pools and the temperatures observed are equals to setpoints.
Then, when I run the simulation with version 9.3 by upgrading the idf with the version updater tool, the results are completely different : the temperature of the swimming pool “BASSIN_LUDIQUE” doesn’t meet the setpoint and the total consumption of the boiler is below the consumption of the pool “BASSIN_LUDIQUE”, which appears to be very overestimated (400 kW against 50 kW in the first simulation).
I’ve tested with versions 9.4 ; 9.6 and 22.1 : results are the same as in version 9.3.
Hope this can help finding the origin of this bug.

RESULTS WITH VERSION 9.2 :
![Image1](https://user-images.githubusercontent.com/127381342/230329516-b607297c-569c-497a-a92e-627262d39a25.png)

RESULTS WITH VERSION 9.3 :
![Image2](https://user-images.githubusercontent.com/127381342/230329598-74fd07ad-11fa-4a98-8911-9ba171804288.png)

**Comment by simonsays1980** [comment] 2023-05-10 16:50
@RKStrand is there any chance that a fix happens in near time?

**Comment by RKStrand** [comment] 2023-05-10 16:53
@simonsays1980 It is one of the items on my list to complete before the V23.2 release.  While I can't make a direct promise that it will be done by a certain date, I do feel like it will be one of top issues that I plan to correct.  So, hopefully this will be done in the near future.  Does that help at all?

**Comment by simonsays1980** [comment] 2023-05-10 17:43
@RKStrand Thanks a lot for coming back to this so quickly. I guess with two major updates a year the minor update might come in the next 2 months? 

I also wrapped my head around how to model it differently. In a 1Zone2Pools environment one could possibly use a 1Zone1Pool setup with a larger pool to approximate the targeted setup. In between the pools is a glass wall that is often open - so it could work. Or might the wall have a more signifcant influence on the behavior of the zone? Just thinking loudly :)

**Comment by RKStrand** [comment] 2023-05-17 17:16
@AlexandreDijoux Would you be willing to share the input file that generated the results?  It is possible that what you are seeing is a second issue with the swimming pool as it relates not to the strange control but results not being accounted for correctly.  It almost seems like in V9.2 the boiler energy is adding the two pool heating energies correctly whereas in V9.3 it seems to be subtracting one from the other for some reason.  That may not be the cause--just what I noticed as I read through what you posted.  Thanks!

**Comment by RKStrand** [comment] 2023-05-23 15:17
The original issue has been fixed and will now go through the review process.  Here is the graph after the fix was applied:
<img width="456" alt="image" src="https://github.com/NREL/EnergyPlus/assets/5804989/7bc9bd86-6320-485e-8840-c05603fc611c">
No more strange deviations from the setpoint as before.
The additional reporting issue reported by @AlexandreDijoux will be separated out into a new defect once an example file is obtained.

**Comment by simonsays1980** [comment] 2023-05-25 13:45
This is great @RKStrand ! Thanks a lot for the quick fix!

**Closed as completed** 2023-06-07 18:34 UTC
