### ISSUE TITLE
Add Date and Time Format Options

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5360] opened 2015-12-09 16:15 UTC
EnergyPlus currently outputs the time at the end of a day as mm/dd 24:00 which is not a valid time format for many tools, including python diffing utilities.  Suggest adding an option (accessible through an environment variable for regression testing) that allows midnight to be output as mm/dd 24:00 or mm/dd+1 00:00.

**Comment by mjwitte** [comment] 2015-12-11 20:26
@amirroth @JasonGlazer @Myoldmopar Per today's discussion, should unify date formats across all output.  This option could offer a user-defined date format or we could standardize on a single format.  Currently, the following formats are used:

%m/%d (12/21) in eio

%m/%d %H:%M - %H:%M (12/21 00:00 - 00:10) in err output ShowContinueErrorTimeStamp()

%y-%m-%d %H:%M:%S (2015-12-11 13:00:24) simulation timestamp in table output

%y.%m.%d %H:%M (YMD=2015.12.11 13:49) simulation timestamp in err and other text files

%m/%d %H:%M:%S (7/21 14:48:00) in some table reports and in csv variables outputs (as converted by readvarseso from eso output)

%d-%b-%H:%M (07-JUL-00:06) in other table reports

**Comment by amirroth** [comment] 2015-12-11 20:31
So years are printed out in some simulation output? I guess those are
needed in some situations, e.g., if you are using actual weather data
rather than TMY. In that case it would be good to use 1900 as a year if an
actual year is not given.

Do any outputs print times below a second? Other than runtimes?

**Comment by mjwitte** [comment] 2015-12-11 20:40
Currently, year is only printed in the timestamp of when the run was executed.  But as better support for multi-year simulations is added, then year will be needed in actual output as well.

**Comment by jamiebull1** [comment] 2016-01-21 17:10
+1 for fixing the 24:00 representation of midnight. I've just been bitten by it once again (in Python).

**Comment by wqp89324** [comment] 2017-02-16 21:06
+1 for fixing the 24:00 representation of midnight.

**Comment by Fan-Feng** [comment] 2017-06-14 02:59
+1 for fixing the 24:000 representation,hahaha

**Comment by mitchute** [comment] 2018-06-05 15:17
+1 on this issue

**Comment by jmarrec** [comment] 2018-07-17 07:25
+100 on this issue.

This is by far my biggest pain when doing post-processing. Correctly parsing these super weird timestamps in python is by far my biggest bottleneck, and that includes opening both eplusout.csv **and** the SQLite database.

**Comment by jmarrec** [comment] 2018-07-18 07:53
@jasondegraw wrote on this unmethours issue [here](https://unmethours.com/question/32769/suppose-i-have-100-variables-calculated-using-energyplus-and-i-want-to-print-the-100-in-10-csv-files-how-may-i-achieve-it/?comment=32826#post-id-32826):

> The utility that is responsible for converting the ESO (which has dates and times that make sense internally to E+) into CSV is [ReadVarsESO](https://github.com/NREL/EnergyPlus/tree/develop/src/ReadVars). Yes, it is in F90, but it is open source and we are happy to take contributions (even in other programming languages). The contribution policy is right [here](https://energyplus.net/contributing).

I don't think the "problem" is `ReadVarsESO` only, since the SQL file suffers from the same problem. The problem is perhaps more what "makes internal sense in E+"  and what people have been used to.

But I think I do get part of your point: you could leave E+ to use its current time representation internally and just modify the output procedures: ReadVarsESO **and** the SQLite writing procedures ([SQLite::createSQLiteTimeIndexRecord](https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/SQLiteProcedures.cc#L1502) to begin with, maybe others).

Bonus: this makes you avoid a potential rats nest because you don't have to modify one of the pillars of the existing structure
Cons: having conversions going on may create slow-downs (thoughts?)

----

Providing an option to use the legacy 24:00 or the new format as @mjwitte suggested seems like a good idea though in order to not break all existing post-processing workflows that people may have setup (though I would make the new time format the default, with an option to revert to old behavior).

**Comment by jasondegraw** [comment] 2018-07-18 22:08
@jmarrec I didn't indicate that there was a problem, so let's be clear on that first. The original question had to do with CSV so I logically confined my comment to CSV. Changes to ReadVars are still possibly in play for the next release, anything else is a much heavier lift. And again, we're happy to take contributions.

**Comment by jmarrec** [comment] 2018-07-19 14:08
Note that I did put quotes around "problem", because I do realize that this thread is labeled "suggestion" and that everything is currently working as designed right now :)

I would still welcome your (plural=dev team members) thoughts on whether the change should be internal or just the output procedures, whether that would induce slow downs, etc. That'd help to clarify the roadmap and assess how much work this would be.

**Comment by JasonGlazer** [comment] 2018-07-19 14:21
I would expect that this would be simply changes within EnergyPlus source code when writing output. As @mjwitte indicated near the top of the discussion, it would probably make sense to unify the output format so that it is consistent whenever used. A new Output: object or field would be needed and the idea of a command line option or environmental variable to override it is a good idea. Seems like a small project that should expect a *lot* of diffs.

**Comment by MatthewSteen** [comment] 2018-07-19 16:20
I suggest changing EnergyPlus' default time and date format to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), which is what [OpenStudio uses](https://github.com/NREL/OpenStudio/blob/3549a2c2955007d05e8aa55371fcf5ce1e6b2a27/openstudiocore/src/utilities/time/DateTime.hpp#L139-L149) (and probably supported by most programming languages).

An option to override this with a new object would probably be helpful for some users.

**Comment by jasondegraw** [comment] 2018-07-19 20:57
@jmarrec I don't think those quotes mean what you think they mean. I didn't post my comment here because the UnmetHours question is related to this issue, but only partly (item 5 in @mjwitte's list of 6 items). There's much more to the issue than just the contents of the ESO and the SQL. If I had wanted to post it here I would have posted it here in the first place. Please don't do it again.

**Comment by jmarrec** [comment] 2018-07-20 07:46
I really didn't want to cause any trouble to anyone. I consider that contributing starts with reporting and discussing issues, and that it's a **really** important part too: you can't fix bugs you don't know about, and having feedback from (real-world / industry) users seems like a good idea considering you're developing a product that is intended to find an audience.

Since the comment box on UH isn't the place to have a discussion, and that there was this issue, I just moved it here thinking we might have a constructive discussion on the topic. At the very least I'd be able to give my user feedback, but I was also thinking that clarifying the approach to tackle this enhancement request might be a nice benefit, and that I may actually consider implementing it myself.

I also consider unmethours to be 1. public, and 2. some sort of anti-chamber of GitHub issues. So going from UH to github seems like a perfectly natural move (cf: E+ github [issue template](https://github.com/NREL/EnergyPlus/blob/develop/.github/issue_template.md) does include a "link to unmethours"). I didn't even pause to consider that someone would find that move offensive in any shape or form.

I meant well.

**Comment by MatthewSteen** [comment] 2019-11-27 18:22
Wow, 16 👍 for this issue. That's the most I've seen, so seems like it a high priority to users.

**Comment by shorowit** [comment] 2022-10-19 19:58
One downside to addressing the 24:00 issue as proposed here is that it can be confusing when using daily or monthly reporting frequencies.

For example, if you request monthly output, the first timestamp would end up labeled as `2007/02/01 00:00:00`, which may come across as February data to many users. While many of us really dislike `2007/01/31 24:00:00`, it does at least better convey that it's January data. (This could be resolved by switching to the start-of-report instead of end-of-report convention, so that the first monthly timestamp would be `2007/01/01 00:00:00`, but that's sure to open up another can of worms and opinions...)

**Comment by hobob0t** [comment] 2023-02-08 18:55
+ 1 times infinity for this. 24:00 is not a widely used format. E+ should follow recognized datetime standards or at least have a checkbox for "use ISO 8601"

**Closed as completed** 2023-02-22 18:07 UTC
Labels: NewFeatureRequest
