### ISSUE TITLE
`Hydronic Tubing Length` field in constant flow radiant objects became empty after transition from v9.4 to v9.5

### ISSUE THREAD

**Issue by hongyuanjia** [NREL/EnergyPlus#9171] opened 2021-11-06 16:37 UTC
Issue overview
--------------

In the transition file `CreateNewIDFUsingRulesV9_5_0.f90`, rules for `ZoneHVAC:LowTemperatureRadiant:ConstantFlow` were broken, which makes the value of `Hydronic Tubing Length` field become empty after transition from v9.4 to v9.5.

Taking the file `RadLoTempCFloHeatCool.idf` as an example, one input constant flow radiant object is:

```
ZoneHVAC:LowTemperatureRadiant:ConstantFlow,
    West Zone Radiant Floor, !- Name
    RadiantSysAvailSched,    !- Availability Schedule Name
    West Zone,               !- Zone Name
    Zn001:Flr001,            !- Surface Name or Radiant Surface Group Name
    ConvectionOnly,          !- Fluid to Radiant Surface Heat Transfer Model
    0.012,                   !- Hydronic Tubing Inside Diameter {m}
    0.016,                   !- Hydronic Tubing Outside Diameter {m}
    400,                     !- Hydronic Tubing Length {m}
    0.35,                    !- Hydronic Tubing Conductivity {W/m-K}
    ......
```

After transitioning from v9.3 to v9.4, it became:

```
ZoneHVAC:LowTemperatureRadiant:ConstantFlow,
    West Zone Radiant Floor, !- Name
    West Zone Radiant Floor Design Object,  !- Design Object
    RadiantSysAvailSched,    !- Availability Schedule Name
    West Zone,               !- Zone Name
    Zn001:Flr001,            !- Surface Name or Radiant Surface Group Name
    ,                        !- Hydronic Tubing Length {m}
    4e-04,                   !- Rated Flow Rate {m3/s}
    ,                        !- Pump Flow Rate Schedule Name
    ......
```

Note that the value of `Hydronic Tubing Length` was lost. The value `400` should be kept in the transitioned file. This error comes from line 681 in `CreateNewIDFUsingRulesV9_5_0.f90`:

https://github.com/NREL/EnergyPlus/blob/00d968c57b48ff354fdc123d00e782e18842f1ba/src/Transition/CreateNewIDFUsingRulesV9_5_0.f90#L676-L701

Now, line 681 is:
```
L681:    OutArgs(6)=OutArgs(8) 
```
It should be changed to:
```
L681:    OutArgs(6)=InArgs(8) 
```

### Details
Some additional details for this issue (if relevant):
 - Platform: All
 - Version of EnergyPlus: official v9.5.0 release
 - Unmethours link or helpdesk ticket number: NA

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [RadLoTempCFloHeatCool.idf.txt](https://github.com/NREL/EnergyPlus/files/7490864/RadLoTempCFloHeatCool.idf.txt)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2021-11-08 14:04
This is a duplicate of #9131.

**Comment by mjwitte** [comment] 2021-11-08 14:18
Or maybe it's not a duplicate. @jcyuan2020 Please confirm if this is fixed by #9139.

**Comment by hongyuanjia** [comment] 2021-11-08 14:21
Actually, this issue is not a duplicate of #9131. This one is specific to the transition of `ZoneHVAC:LowTemperatureRadiant:ConstantFlow`. PR #9139 only touches rules of `ZoneHVAC:Baseboard:RadiantConvective:Water`, but not `ZoneHVAC:LowTemperatureRadiant:ConstantFlow`, AFAIK

**Comment by jcyuan2020** [comment] 2021-11-08 14:56
I am adding the fix this one to RP #9139. @hongyuanjia @mjwitte

**Comment by mjwitte** [comment] 2022-01-19 21:20
Addressed in #9139.

**Closed as completed by mjwitte** 2022-01-19 21:20 UTC
