### ISSUE TITLE
Object Count Summary sub-table Input Fields no longer applicable, remove table

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#8095] opened 2020-06-19 14:54 UTC
Issue overview
--------------
Tested with example file 5ZoneAirCooled. Input processing no longer reads IDD objects and therefore this table always reports 0's. This table is no longer needed.

![image](https://user-images.githubusercontent.com/5778156/85145915-45046b00-b21b-11ea-87d0-ef3b56d23095.png)

![image](https://user-images.githubusercontent.com/5778156/85145854-31590480-b21b-11ea-9fa8-fc4ab7c2973b.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2020-06-19 15:00
One could argue that it should remain, but be fixed and revised. Anyways, this is a duplicate of https://github.com/NREL/EnergyPlus/issues/6917 If I remember correctly there is (or was?) a compliance reporting requirement for information like this? @JasonGlazer ?

**Comment by JasonGlazer** [comment] 2020-06-19 15:14
Yes, I believe that some (LEED?) compliance forms ask for information that is based on this. That should be verified before we remove the table.

**Comment by rraustad** [comment] 2020-06-19 18:11
I forgot I opened that long ago. Refer to closed issue #6917 as needed.

**Closed as completed** 2020-07-01 14:27 UTC
Labels: Defect
