### ISSUE TITLE
IDF Editor - add support for non-DOS file editing

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5464] opened 2016-02-05 16:14 UTC
IDF Editor does not support editing IDF files that are unix or MacOS line endings. Those should be added.

https://github.com/santoshphilip/eppy/issues/68#issuecomment-180415810

**Comment by mjwitte** [comment] 2016-02-05 16:43
This is a duplicate of #5453

**Comment by santoshphilip** [comment] 2016-02-05 18:00
I have been messing with line endings for a while. 
here are some thoughts on it:

There are three line endings (apart from obscure ones I don't know about :-) 

```
dos_sep='\r\n'
mac_sep='\r'
unix_sep='\n'
```

`mac_sep` is used on the classic Macs
Modern Macs with OS X use `unix_sep`
You are rarely going to run into `mac_sep`, but the possibility exists

Often files move between Unix and Windows machines
So you may wind up with files having mixed line endings, both `dos_sep` and `unix_sep` in the same file

In the case of IDF Editor, you are really concerned about reading the files.
Writing the file is going to be DOS line endings, since you are on a windows machine. No point in putting effort doing anything different.

**Comment by JasonGlazer** [comment] 2016-02-05 18:15
I agree, being able read DOS, Unix and MacOS line endings but write just DOS line endings would probably be sufficient.

**Comment by mjwitte** [comment] 2016-03-07 15:29
Closed via https://github.com/NREL/EnergyPlusBuildSupport/pull/25

**Closed as completed by mjwitte** 2016-03-07 15:29 UTC
Labels: AuxiliaryTool

**Comment by santoshphilip** [comment] 2016-03-07 22:31
thanks @JasonGlazer @mjwitte 
eppy now now no longer needs that functionality (the toggle for line endings)
But I think I'll just leave it there.
