### ISSUE TITLE
Oscillating Winter Designday Zone Load with Ceiling Diffuser Model

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#8091] opened 2020-06-18 16:19 UTC
Issue overview
--------------
User file specifies Ceiling Diffuser model as interior convection algorithm. Zone Ideal load for winter designday shows oscillating behavior rather than the expected steady state. This is checked with multiple versions of EnergyPlus and the behavior started in Version 9.2. The following two changes are suspected to be related:
[https://github.com/NREL/EnergyPlus/pull/7300](https://github.com/NREL/EnergyPlus/pull/7300)
[https://github.com/NREL/EnergyPlus/pull/7444](https://github.com/NREL/EnergyPlus/pull/7444)

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 10 64bit
 - Version of EnergyPlus 9.2.0, 9.3.0
 - Helpdesk ticket number 15486

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added 
[Comparison_CeiingDiffuserModel.xlsx](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/Comparison_CeiingDiffuserModel.xlsx)
[LoadCalculation_9.2.idf](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/LoadCalculation_9.2.idf)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2020-07-24 12:44
@RKStrand Are you able to look into this?

**Comment by mjwitte** [comment] 2020-07-24 21:55
Confirmed that the load was constant after #7300 was merged. Core Sensible Heating=4011.465W (sizing peak load changed from 5308 to 4125W).

Confirmed it was still constant just before #7444 was merged.

The oscillation on the sizing day simulation started with #7444 but the eio sizing output did not change (4125W). Core Sensible Heating varies from 3805W to 4441W with an average of 4124W.

**Comment by mjwitte** [comment] 2020-07-29 15:09
@RKStrand The oscillation occurs if the ACH required to meet the load falls into the 0.1-0.5 range where the model currently transitions from Hforced to Hnatural. Here's a plot of Hin vs ACH for a floor. This test file just happens to fall in the transitional range.

Change the walls to increase the load, and it settles in on a constant load. I tried some adjustments (transition starting at 3.0 ACH or down to zero ACH) to reduce the slope, but it appears that H just changes too quickly in this range where it's a function of both ACH and deltaT. I also tried updating convection coefficients at every surface iteration (instead of every 30 iterations) - still got varying load.

![image](https://user-images.githubusercontent.com/4991075/88817090-b8868a00-d182-11ea-8bfd-d8b4cc3d8573.png)

**Comment by RKStrand** [comment] 2020-07-29 20:46
@mjwitte Hmmm.  Well, that is weird and definitely unanticipated.  What do the "stable" and "unstable" labels refer to in your graph above?

**Comment by mjwitte** [comment] 2020-07-30 11:18
Stable/unstable is the direction of heat flow which triggers either `CalcWaltonUnstableHorizontalOrTilt` or `CalcWaltonStableHorizontalOrTilt` for the natural convection component.  [CeilingDiffuserConvection1.xlsx](https://github.com/NREL/EnergyPlus/files/5000875/CeilingDiffuserConvection1.xlsx)

**Comment by RKStrand** [comment] 2020-07-30 13:47
Oh yeah...wasn't familiar with the stable/unstable naming.  I get it though I'm not sure I like the way these are worded.  Since this looks like it might be 10 year old code, I just accept it and carry on.
As for how to solve the problem, I'm not 100% sure what will fix things.  My one idea at the moment is to allow the convection coefficient to vary for a bit and then simply freeze it at some value for the rest of the iterations if it is in the magic range.  That would keep it from bouncing around but I'm not sure that would guarantee that things wouldn't oscillate.

**Comment by RKStrand** [comment] 2020-08-10 20:57
@mjwitte Ok, so I'm looking at this now while waiting reviews on my two outstanding PRs (thanks for your initial comments on one of them!).  Here are some thoughts that I had after looking at this again.
]
First, after looking at this a bit more closely, what we currently have is not strictly a linear interpolation between forced and natural convection.  The reason why is subtle and unfortunately I didn't notice this before.  Hforced is always calculated--not limited at ACH=1.  So, what results is not strictly a linear interpolation between forced and natural.  Now, maybe that's not a bit deal--it's just interpolating on a sliding scale rather than setting a value at ACH = 0.5 for natural and a value at ACH=1 for forced and then interpolating from there.  Does it make a big difference?  Probably not though I could give this a try and see what happens.

Second, if I remember correctly, the cut-off used to be ACH=3 and then it was changed to 1.0 as part of the review of the previous work.  There is nothing magical about either one of those points OR the fact that it interpolates over a 0.5ACH range.  Why not let this vary over say a range of 2ACH from 1.0 to 3.0?  Would this wider band bring a smoother transition and less bouncing around?  I'm not sure but maybe it's worth a try.  What's interesting is that it seems like it's this one zone (core) that has issues.  The other zones have slight flutters--but that might be because surrounding zones have interzone partitions that connect them to the core.

Anyway, just recording some thoughts here--partially to see what you think and partially so that I don't forget!

**Comment by TiejunWu** [comment] 2020-08-26 14:49
@RKStrand   @mjwitte 
We did some investigation around the issue and now we have a workaround to this issue for our application. Given this and the complicated nature of the problem, our recommendation is to not make changes to the cutoff ACHs values of 0.5 to 1 ACH for now. However, we would still like to get your insights in understanding the cause of this oscillatory behavior, both qualitatively and quantitatively.

**Following are some of the investigations and findings.**

To understand how oscillation behavior is affected by ACH, I did some experiments based on the IDF. From preliminary results data, the oscillation in the core zone is the most severe. And its supply air ACH is close to 0.5 which is the transition from natural convection to the mixed mode. So what I did was to add a convective heat source to the core zone to change its load and thus the ACH.  I got the following set of result.  The red data points and red lines in the table are the cases where significant oscillation of the load profile occurred.
![image](https://user-images.githubusercontent.com/7797674/91317803-7c961300-e788-11ea-80d7-e0831094339b.png)

![image](https://user-images.githubusercontent.com/7797674/91317725-65572580-e788-11ea-9e37-fcfb83ad726f.png)

In this series of test cases, all the cases converged to a steady state, except the four cases highlighted in red. In the table, for those four cases, the heating load, air flow rate value were the average value during the 24 hours of heating designday. Also the ACH spans the range of pure natural convection (ACH<0.5), mixed mode convection (ACH 0.5~1) and forced convection (ACH >1).

For those four cases that had oscillatory zone load, the result are shown here:

![image](https://user-images.githubusercontent.com/7797674/91318082-d8f93280-e788-11ea-87b3-42a1ccd27464.png)
![image](https://user-images.githubusercontent.com/7797674/91318098-deef1380-e788-11ea-835b-4d7aacaf3b8c.png)
![image](https://user-images.githubusercontent.com/7797674/91318111-e31b3100-e788-11ea-80a5-d492f073d251.png)
![image](https://user-images.githubusercontent.com/7797674/91318144-e9a9a880-e788-11ea-8736-5bb3af459765.png)

From these four cases, I can see that for the heat source =200W case where the ACH is right around 0.5, the odd shape of the curve probably means some part of the curve is in the natural convection zone and the higher heating load time steps are in the mixed mode convection zone. For the other heat source values (0, -200 W, -400 W), ACH values for all time steps are in the range of mixed mode convection. 

Another observation I can get from the result data table is that for this example, the oscillatory behavior only occurs for a narrow band of ACH (~0.49 – 0.63). For other ACH values, the calculation would converge to a steady state.

Then I looked at the “converged” cases to see how it got to a steady state. The following curve is for heat source = -2000 W. For this case, numerically the load converged at 6718.8 W. It is still oscillatory with incredibly small amplitude.

![image](https://user-images.githubusercontent.com/7797674/91318387-2bd2ea00-e789-11ea-9b2d-20d4720d2518.png)

Based on these observations from the data, our conclusions are:

1. From the trend line in the first graph, it looks like for the cases where the oscillatory behavior occurs, the 24 hour averaged load would be a reasonable representation of the steady state load to be used for the purpose of equipment sizing.  We will use this approach for now, but would like to get a better understanding about the oscillatory behavior.

2. In EnergyPlus time step marching, there seems to be some positive feedback mechanism and some negative feedback mechanism that affects the load. An example for positive feedback mechanism I can think of is the convection heat transfer coefficient. If the next step got a bigger load, the supply air flow rate will increase, so ACH will increase and cause the convection heat transfer coefficient to increase, that would further increase the zone load (assume surface temperature did not change). A negative feedback mechanism could be the surface temperature, higher heat transfer coefficient would cause the surface temperature to be closer to zone air temperature, thus at next step, the convection heat transfer rate could drop. There could also be complicated interactions between zones, between surfaces within the zone. 

3. The oscillatory behavior maybe inherent to EnergyPlus, but why does the amplitude of oscillation get so large for certain conditions? This may give a more quantitative explanation for this specific example.

I think items 2 and 3 would benefit from stepping through the code for a few time steps and track how the value of some of the relevant variables (surface temperature, heat transfer coefficient, etc.) change between the time steps. We would appreciate if you can provide some insights into this.

**Comment by RKStrand** [comment] 2020-08-26 15:37
Thanks for looking into this further, @TiejunWu.  I think my concerns after all of this are still why are the extreme fluctuations happening for the case where the heat source/sink is 0W and how do we prevent this in other cases.  I'm glad to hear that you have found a workaround for your application--but how do we prevent this from happening?  I agree with you that someone (likely me) needs to step through the code or get some very detailed output to see what is happening with the surface temperatures and the heat transfer coefficients and why this transition from natural convection to mixed mode has such a large influence on the results.  The cases where the amplitude of the loads is only around 1.5% is not bad and maybe we would be able to live with that.  However, the "base" case with load variations of around 15% are just way too large.
@mjwitte, what are your thoughts on this?  It seems to me like something needs to be done (and hopefully the "fix" won't cause other issues).

**Comment by RKStrand** [comment] 2020-08-26 15:44
@TiejunWu I failed to comment on your Point 3 above--sorry.  Yes, there will potentially still be some very slight oscillatory behavior in EnergyPlus because numerical imprecision will filter in and cause that behavior.  EnergyPlus will never get to perfect steady state because of numerics.  However, as you saw, those oscillations are incredibly small and acceptable.  It's when those oscillations are larger like we are seeing in this file that we have to investigate further and find a solution that works for all files without a workaround so that users don't have to go through the process that you did to get to the result.

**Comment by RKStrand** [comment] 2020-08-26 20:02
@mjwitte @TiejunWu Ok, here's what I can tell you after looking into this a bit further.  The biggest issue in the core space is the convection from the ceiling and the floor.  While the walls also show some variation, the variation in the convection from the floor and the ceiling are the biggest issues.  If you look at the correlations for forced convection from the ceiling and floor, you will also notice they are much larger than the wall correlation at the start of the transition at ACH=0.5.  As a result, I think those are more heavily impacted as a result.

So, here is what I tried: changing the transition to be between ACH = 1 to ACH = 3 and a transition from ACH = 0.5 to ACH = 3.0.  Both of these cases snapped everything in line and there was next to no changes in the load (difference in max to min load was less than 10^-3, max loads were roughly 3976W vs. 3963W, respectively).

Why did we go with a range of ACH = 0.5-1.0 for the transition zone?  Based on an email exchange with the model author (Dan Fisher), he said that the correlation actually should end at ACH=3 because that is the data that they had, but he felt that it should be pretty stable down to ACH=1.  So, ACH=1 was chosen as the top end of the transition zone and ACH=0.5 was the lower bound.  But that was based on the forced convection correlation and his thought that the zone would still be "well mixed" down to ACH=1.   It was not based on what would happen if the transition was relatively short.  At ACH = 1, the forced correction values are roughly 2.22, 3.96, and 6.33 for the wall, floor, and ceiling, respectively.

Here's what I am proposing to resolve this:
Expand the transition region from the current ACH=0.5->1 to ACH=0.5->3.  Evaluate forced convection using the correlation above ACH=3.  For ACH below 0.5, use the natural convection correlation.  Between ACH=0.5 and ACH=3.0, interpolate between the natural convection correlation and the forced correlation value at ACH=3.0.  This would bound the forced correlation at the data cut-off point and give a truly linear interpolation between ACH=0.5 and ACH=3.0.  Right now, it evaluates the forced convection value at whatever the ACH is which means it's not truly a linear interpolation.  Would need to fix values for existing unit tests and add at least a new one as well.  Probably also need to check into the documentation and clarify that also.

What are both of your thoughts on this?  I believe this would fix the issue for the defect inducing IDF and hopefully avoid these problems in the future.  The larger transition regime seems to steady things out better from what I am seeing.

**Comment by mjwitte** [comment] 2020-08-27 14:38
@RKStrand Your proposed approach sounds reasonable. The proof would be in seeing stable results across all of the loads tested above. As an alternative, could you keep the same transition zone and alter the interpolation method to be "truly linear"?

**Comment by RKStrand** [comment] 2020-08-27 15:48
@mjwitte I will try the truly linear interpolation for the existing boundaries (0.5-1.0).  I don't think it will be as effective, but I will give that a try before I do anything else.  I will also test the various conditions that @TiejunWu outlined in the work around above.  I'll post results here as they become available.

**Comment by RKStrand** [comment] 2020-08-27 18:44
@mjwitte Ok, the truly linear interpolation from ACH=0.5-1 shows even more fluctuations.  The reason is that Hforced continues to drop from ACH=1 to ACH=0.5 which helps a bit.  With a straight linear interpolation, the slope is constant throughout the range but ends up being higher near ACH=0.5 which seems to be where the trouble is happening in this particular file.  I'll try the straight linear interpolation from ACH=0.5 to ACH=3.0 now and see if this is ok.  Before, I just expanded the range but without making it a truly linear interpolation.

**Comment by RKStrand** [comment] 2020-08-27 20:51
@mjwitte @TiejunWu I implemented the straight linear interpolation and it seems to fix the problem for this file.  I added in a varying load as above between +400 and -600--all cases have a constant heating load for the core zone (the one that was causing issues).  I am hopeful that this will fully resolve this issue and we won't run into any more oscillation problems with other files.  I look at existing unit tests and create some new ones to test this out as well as double check the docs to see if anything needs to be modified.  Should have something ready for review tomorrow.

**Comment by TiejunWu** [comment] 2020-08-28 01:12
@RKStrand Thank you very much for looking into this. With this fix, the assumption is that the fluctuation was caused by the steeper slope of the transition line. So by stretching the transition zone, the fluctuation will be fixed by the flatter transition line. I am attaching a plot for the ceiling surface heat transfer coefficient here ( for the natural convection I am using 2.6 K as the temperature difference between the surface and the zone air, which is close to what I get for the ceiling surface of core zone):

![image](https://user-images.githubusercontent.com/7797674/91509074-40a59f80-e8a7-11ea-9d27-3eb33a33f0d5.png)

However, it we look at the table I showed earlier, fluctuation really happened only for the narrow range of ACH between (0.49-0.63). When we check that range of the transition curve on the Hin vs ACH curve shown here, the transition curve is actually steeper when ACH approaches 1, and we did not observe fluctuation there. That kind of indicates there might be some other factors causing the fluctuation together with (or other than) the steeper slope for the Hin curve. 

My concern is that the fix might solve the fluctuation for this particular case, but if the cause actually involves other factors, the fluctuation may show up in some other cases.

When you step through the code, were you able to see what is causing the trend to reverse at ~3776 W or 4470 W for the original case without heat source or sink?

**Comment by RKStrand** [comment] 2020-08-28 16:13
@TiejunWu From what I am seeing inside the debugger, the solution is simply not stable and overshoots the correct solution in both directions.  Once it gets far enough away from the solution, it reverses course and tries to get back to where it should be.  In this particular case (the case with zero additional heat source/sink), I am seeing the ACH vary from 0.5 to 0.56.  That's a 12% difference between different time steps.  On the walls, because Hforced and Hnatural are relatively close (1.9 vs. 1.3ish), this difference results in a relatively small difference in the actual H value (~1.35 at ACH=0.5 vs. ~1.4 at ACH=0.55 or an actual difference around 3-4%).  On the floor, Hforced and Hnatural are about 3 apart and Hnatural is relatively small (0.85ish).  H is around 0.85 when ACH=0.5 and around 1.2 when ACH=0.56 or an actual difference of around 40%.  Even though the temperature isn't moving a lot, H is and you see the biggest differences when you look at the floor and ceiling.

From what I am seeing, the changes are simply too large and the solution can't resolve them.  I think this is also why we aren't seeing the differences when things are close to an ACH of 1.0.  At that point, the percentage differences in how much H changes are much smaller and the numerics seem to work out.  For example, when the floor is close to an ACH of 1.0, the Hforced value is around 4.  Even if the ACH is bouncing around, it's likely to be a change in H of less than 10%.  So, I think the solutions that are around 0.5ACH for the various cases you looked at with different source/sink values, are residing in a region where the changes in H are simply too high to arrive at a solution.  It seems to ping-pong back and forth and overshoot the solution.  Once it has gone "too far", it comes back but simply isn't able to narrow in on the solution.  The switch to a mixed mode that ranges from 0.5ACH to 3.0ACH reduces the amount H changes for the same change in ACH by a factor of 5 and this seems to settle things down and avoid the tendency to overshoot.

Will this fix the problem for every case, I don't think there is any guarantee there.  All I know is that the ceiling diffuser correlation for forced convection had a lower experimental bound of 3.0ACH which makes it a reasonable place to start a straight linear interpolation between purely forced and purely natural.  I'm also not sure this answers your concerns about potentially something else causing the oscillations.  What I do see is the oscillations go away when I increase the mixed mode from to be from 0.5ACH to 3.0ACH from the current 0.5ACH to 1.0ACH.

Based on all of this, what are your thoughts on my proposed solution?

**Comment by TiejunWu** [comment] 2020-09-04 21:39
@RKStrand Thank you very much for looking into the details. Looks like the conclusion is that the slope of the transition line and the circumstance around the ceiling surface of the core zone likely caused the oscillation. So by extending the transition zone from 0.5-1.0ACH to 0.5-3.0 ACH, the slope of the transition line is reduced and can eliminate the oscillation. Given that 3.0 ACH is the lower bound of the experimental data and this fix would reduce the possibility of oscillation behavior, I think you can go ahead and implement the fix. We will report in the future if we encounter any cases that still has oscillation problems. 

Since you are working with ConvectionCoefficients.cc, one other minor issue I had was that when I tried to manually calculate the convection heat transfer coefficients based on the simulation output variables, I was not able to match the EnergyPlus output variable value for "Surface Inside Face Convection Heat Transfer Coefficient", usually there is a 1~2% difference.   In my manual calculation, since EnergyPlus does not have an output variable for zone air flow ACH, I used the zone air node (Node 13) "current density volume flow rate" and the zone volume (1710 m3) to calculate the ACH value. I suspect that the difference might be in the ACH I used and the ACH used in the convection heat transfer coefficient. In the convection heat transfer coefficient code, the ACH is calculated in the function  [CalcCeilingDIffuserACH](https://github.com/NREL/EnergyPlus/blob/aa2bc4186f4d77c5ee7436e206e4396aa726bbfc/src/EnergyPlus/ConvectionCoefficients.cc#L2595).  In which it called [this function](https://github.com/NREL/EnergyPlus/blob/aa2bc4186f4d77c5ee7436e206e4396aa726bbfc/src/EnergyPlus/ConvectionCoefficients.cc#L2642) to calculate zone volume flowrate. In this program, there is one line called psychrometric function to calculate the zone air density.  I could not find the code that calculates the output variable "System Node Current Density Volume Flow Rate". I suspect the zone air density used in this program is inconsistent with the density used to calculate the output variable. Can you please take a look when you have time?

**Closed as completed** 2020-09-15 16:01 UTC
Labels: Defect
