### ISSUE TITLE
IDFVersionUpdater Problem

### ISSUE THREAD

**Issue by santle** [NREL/EnergyPlus#7492] opened 2019-09-10 10:56 UTC
IDFVersionUpdater  is not working proper

**In EnergyPlusV9-0-1, conversion of working IDF of E+version 8.9 to version 9.0 is not working**

C:\EnergyPlusV9-0-1\PreProcess\IDFVersionUpdater>Transition-V8-9-0-to-V9-0-0.exe
 Transition Starting
 Conversion 8.9 => 9.0
 Processing Old IDD -- V8-9-0-Energy+.idd
 Processing New IDD -- V9-0-0-Energy+.idd
 Enter "diff" for differences only, "full" for full idf outputs
-->full
 Will create new full IDFs
 Enter "yes" for including units on output lines, "no" for no units inclusion
-->yes
 Will create new IDF lines with units where applicable
 Enter "yes" for preserving blanks in default fields, "no" to fill those fields
with defaults
-->no
 New IDF lines will have blank fields filled with defaults as applicable
 F
 Enter input file name, with path
-->C:\Users\jcamilsa\Desktop\DesignBuilder_Beeah\Beeah.idf
 Processing IDF -- C:\Users\jcamilsa\Desktop\DesignBuilder_Beeah\Beeah.idf
At line 1062 of file C:\ci\EnergyPlus-v9.0.1-Win64-VS14\src\Transition\UtilityRo
utines.f90
Fortran runtime error: Index '1959303391' of dimension 1 of array 'defaultyear'
above upper bound of 13

**In EnergyPlusV9-1-0, conversion of working IDF of E+version 8.9 to version 9.0 is too not working**

C:\EnergyPlusV9-1-0\PreProcess\IDFVersionUpdater>C:\EnergyPlusV9-1-0\PreProcess\
IDFVersionUpdater\Transition-V8-9-0-to-V9-0-0.exe
 Transition Starting
 Conversion 8.9 => 9.0
 Processing Old IDD -- V8-9-0-Energy+.idd
 Processing New IDD -- V9-0-0-Energy+.idd
 Enter "diff" for differences only, "full" for full idf outputs
-->full
 Will create new full IDFs
 Enter "yes" for including units on output lines, "no" for no units inclusion
-->no
 New IDF lines will not include units
 Enter "yes" for preserving blanks in default fields, "no" to fill those fields
with defaults
-->yes
 Will create new IDF lines leaving blank incoming fields as blank (no default fi
ll)
 F
 Enter input file name, with path
-->C:\Users\jcamilsa\Desktop\DesignBuilder_Beeah\Beeah.idf
 Processing IDF -- C:\Users\jcamilsa\Desktop\DesignBuilder_Beeah\Beeah.idf
 Processing IDF -- WindowShadingControl preprocessing . . .
 Processing IDF -- WindowShadingControl preprocessing complete.
 Processing IDF -- Processing idf objects . . .
At line 1062 of file C:\ci\EnergyPlus-v9.1.0-Win64-VS14\src\Transition\UtilityRo
utines.f90
Fortran runtime error: Index '1959303391' of dimension 1 of array 'defaultyear'
above upper bound of 13

Is there a way to overcome this issue?

**Comment by mjwitte** [comment] 2019-09-16 16:03
Start again with the original 8.9 file using the v9.1.0 updater (it will automatically do both steps up to 9.1 and you can ask it to save intermediates). If that works, then please note that here and close the issue. If that fails, then please attach the v8.9 here for further investigation.

**Comment by santle** [comment] 2019-09-18 06:34
I have attached the IDF file here:
[Beeah.zip](https://github.com/NREL/EnergyPlus/files/3624772/Beeah.zip)

**Comment by mjwitte** [comment] 2019-09-18 12:41
Strange, I cannot reproduce the problem here. I ran Transition-V8-9-0-to-V9-0-0.exe both in the v9.0.1 install and v9.1.0. They both completed without error. Here is the v9.0 file.
[Beeah-v901.zip](https://github.com/NREL/EnergyPlus/files/3626403/Beeah-v901.zip)

 I see the place in the transition source code where this says it's failing. But that code should only execute for a "RunPeriod" object. Beeah.zip above has a "RunPeriod:CustomRange" object.

**Comment by santle** [comment] 2019-09-24 10:48
Thanks. 
I will be closing this thread shortly. 
Before this, is there a way in energyplus to change the default weekend from "Saturday & Sunday" to "Friday and Saturday" as applicable to middle east? Your advice would be very helpful to me as I didn't find any related topic in the internet.

**Comment by jmarrec** [comment] 2019-10-25 13:37
@santle this is a completely separate question (and one that would rather belong on UnmetHours.com).

But bottom line: No, you can't, it's harcoded around here: https://github.com/jmarrec/EnergyPlus/blob/0e6e9c08a048eb9bb04387a61384bd842816c52f/src/EnergyPlus/ScheduleManager.cc#L3764:L3778

**Closed as completed by jmarrec** 2019-10-25 13:37 UTC
