### ISSUE TITLE
"test" strings in ReportSizingManager.cc show up in Fans table

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#6960] opened 2018-09-13 20:50 UTC
Issue overview
--------------
The string `test my Design Day` shows up in the Fans table here: https://github.com/NREL/EnergyPlus/blob/a2c22cb63eb1131ca4a170e7a4030adffa6a1296/src/EnergyPlus/ReportSizingManager.cc#L423

Also, there's a "test..." in the `Date/Time for Fan Sizing Peak` column here: https://github.com/NREL/EnergyPlus/blob/a2c22cb63eb1131ca4a170e7a4030adffa6a1296/src/EnergyPlus/ReportSizingManager.cc#L425

![image](https://user-images.githubusercontent.com/8397034/45514946-1020d580-b764-11e8-831e-e5564d6904fd.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (8.9)
 - Unmethours link or helpdesk ticket number (NA)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2018-09-13 20:56
Duplicate of #6899, but thanks for the reminder.

**Closed as completed by mjwitte** 2018-09-13 20:56 UTC
