### ISSUE TITLE
Create scripting language bindings

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6568] opened 2018-03-22 23:13 UTC
Problem: Writing and compiling C++ is daunting and prevents many users from contributing to the source code.

Solution: Create scripting language bindings (e.g., Python or Ruby), that allow users to prototype new features that simulate at runtime.

Dependency: Expanded API (http://energyplus.uservoice.com/forums/258860-energyplus/suggestions/9676680-expand-the-energyplus-api-library-to-expose-intern)

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9676944) feedback from @nealkruis

**Comment by blockspacer** [comment] 2019-08-24 16:23
It may be good idea to use cling to solve that issue
see https://github.com/godotengine/godot/issues/31630

**Comment by mitchute** [comment] 2021-06-01 19:33
The issue is addressed by #7776.

**Closed as completed by mitchute** 2021-06-01 19:33 UTC
Labels: MigratedFromUserVoice, NewFeatureRequest
