### ISSUE TITLE
Indexing issue when using multiple UnitarySystem and/or CoilSystem as OASystem components

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#9785] opened 2023-01-09 23:52 UTC
Issue overview
--------------
There appears to be an issue with pointer based components (e.g., UnitarySystem, CoilSystem, etc.) in the OASystem and maybe elsewhere.

In SimOASysComponents the value of state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) is passed into the function SimOAComponent. This value starts out as 0 and this call returns the index to the object. Then the value will be used to simulate the correct component in each object class.

    for (CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {
        CompType = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentType(CompNum);
        CompName = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum);
        SimOAComponent(state,
                       CompType,
                       CompName,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum),
                       FirstHVACIteration,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum), <---- this will initially be 0 for all OASys components
                       AirLoopNum,
                       Sim,
                       OASysNum,
                       OAHeatCoil,
                       OACoolCoil,
                       OAHX);
        if (OAHX) ReSim = true;
    }

Now inside SimOAComponent, this value is passed in as CompIndex. For example a heating coil will pass back it's component index.

    } else if (CompTypeNum == SimAirServingZones::CompType::Coil_GasHeat) { // 'Coil:Heating:Fuel'
        if (Sim) {
            //     stand-alone coils are temperature controlled (do not pass QCoilReq in argument list, QCoilReq overrides temp SP)
            SimulateHeatingCoilComponents(state, CompName, FirstHVACIteration, _, CompIndex); <-- the heating coil will pass back the index to the coil object since this is &CompIndex
        }

But for pointer based equipment, the factory pointer is stored in state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex], which should be the index of the component in the OASystem list.

    } else if (CompTypeNum == SimAirServingZones::CompType::DXSystem) { // CoilSystem:Cooling:DX
        if (Sim) {
            if (state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex] == nullptr) {
                UnitarySystems::UnitarySys thisSys;
                state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex] =
                    thisSys.factory(state, DataHVACGlobals::UnitarySys_AnyCoilType, CompName, false, 0);
                CompIndex = UnitarySystems::getUnitarySystemIndex(state, CompName) + 1;
                state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompIndex) = CompIndex;
                UnitarySystems::UnitarySys::checkUnitarySysCoilInOASysExists(state, CompName, 0);
            }
            bool HeatingActive = false;
            bool CoolingActive = false;
            Real64 OAUCoilOutTemp = 0.0;
            bool ZoneEquipFlag = false;
            Real64 sensOut = 0.0;
            Real64 latOut = 0.0;
            int dummyCompIndex = 0; // TRANE
            state.dataAirLoop->OutsideAirSys(OASysNum).compPointer[CompIndex]->simulate(state, <-- now this will crash or fail for models with multiple UnitarySystem objects (i.e., PTAC, CoilSystem, etc.)

As a fix I propose to pass in CompNum instead of state.dataAirLoop->OutsideAirSys(OASysNum).ComponentIndex(CompNum) and set these values inside SimOAComponent.

    for (CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {
        CompType = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentType(CompNum);
        CompName = state.dataAirLoop->OutsideAirSys(OASysNum).ComponentName(CompNum);
        SimOAComponent(state,
                       CompType,
                       CompName,
                       state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum), <-- won't need this argument now
                       FirstHVACIteration,
                       CompNum, <---- pass this instead and set these other vars inside SimOACompnent

This pointer is also set in GetOutsideAirSysInputs where the factory is called for these pointer based objects. This may also correct this situation where CompIndex would not be used in the SimOAComponent function since the pointer has already been set. This is likely the better option for correcting this issue since this check is missing from the factory loop over each component in all OASystems in GetOutsideAirSysInputs. This would correct this issue. And the checks for NullPtr could be removed in SimOASystem.

    for (OASysNum = 1; OASysNum <= state.dataAirLoop->NumOASystems; ++OASysNum) {
        for (CompNum = 1; CompNum <= state.dataAirLoop->OutsideAirSys(OASysNum).NumComponents; ++CompNum) {

            } else if (state.dataAirLoop->OutsideAirSys(OASysNum).ComponentTypeEnum(CompNum) == SimAirServingZones::CompType::DXSystem)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment] 2023-01-10 11:58
Probably related/duplicate of #9738

**Closed as completed** 2023-01-19 17:27 UTC
Labels: Defect
