### ISSUE TITLE
Issue when using different heating and cooling airflow rates with Airflow Network

### ISSUE THREAD

**Issue by jonwinkler** [NREL/EnergyPlus#5134] opened 2015-08-20 19:00 UTC
If I simply change the following line to a different airflow rate (say 1.17), the HVAC loop fails to converge for all timesteps with a heating load. Is this a bug? Or does the Airflow Network not support different airflow rates for heating and cooling modes? @nmerket @lgu1234 @jasondegraw 

(https://github.com/NREL/EnergyPlus/blob/6e67bc4debba7cb02bd4c3ef595f0f3d81736169/testfiles/AirflowNetwork_MultiZone_House.idf#L1839)

**Comment by mjwitte** [comment] 2015-08-20 19:03
@jonwinkler I suspect you might find the same issue if you make a similar change in a file with AirLoopHVAC:UnitaryHeatPump:AirToAir and no airflownetwork.

**Comment by jonwinkler** [comment] 2015-08-20 19:11
No. If you disable the AFN in the simulation (set AirflowNetworkControl to NoMultizoneOrDistribution), the HVAC loop convergence warnings no longer appear despite having a different airflow rate for heating mode.

**Comment by mjwitte** [comment] 2015-08-20 19:17
@jonwinkler Well, that's a pleasant surprise.

**Comment by jonwinkler** [comment] 2015-08-20 19:38
This issues also exists with the Airflow Network when using an AirLoopHVAC:UnitaryHeatCool object instead of the AirLoopHVAC:UnitaryHeatPump:AirToAir. Use equal heating and cooling airflow rates, the simulation runs smoothly. Set a lower heating air flow (very common for residential systems), the simulation grinds to a halt due to the HVAC loop not converging.

**Comment by lgu1234** [comment] 2015-08-20 19:38
@jonwinkler When you changed the flow rate in unitary system, did you change the coil flow rate also?

**Comment by jonwinkler** [comment] 2015-08-20 19:41
@lgu1234  I've tried it both ways - changing the coil rated air flow and leaving it the same. Though the coil rated flow rate shouldn't have to the same as the flow rate specified in the unitary system, correct?

**Comment by jasondegraw** [comment] 2015-08-20 19:43
@jonwinkler @lgu1234 I ran some quick tests and I'm seeing the same thing. With "Supply Air Flow Rate During Heating Operation" at 1.17 I get convergence failure unless I turn off AFN, with 1.19 it works.

**Comment by lgu1234** [comment] 2015-08-20 19:54
@jonwinkler I tried another example file: AirflowNetwork_MULTIZONE_House_TwoSpeed.idf. It uses AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed. When I changed the value of Speed 2 Supply Air Flow Rate During Heating Operation from 0.7551 to 0.7500 with both parent and coil object, the program ran to completion without any divergence. Please also test AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed.

**Comment by jonwinkler** [comment] 2015-08-20 19:59
@lgu1234 This problem also exists when using an AirLoopHVAC:UnitaryHeatCool object, which is a bigger issue for us than heat pumps. I will test AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed.

**Comment by jonwinkler** [comment] 2015-08-20 20:26
@lgu1234 I tested using AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed in AirflowNetwork_MultiZone_House.idf and the file ran without convergence issues. Odd that the issue exists with AirLoopHVAC:UnitaryHeatPump:AirToAir and AirLoopHVAC:UnitaryHeatCool objects.

**Comment by lgu1234** [comment] 2015-08-20 21:37
@jonwinkler I assigned this issue to me and will take a look at it.

**Comment by lgu1234** [comment] 2015-09-18 15:41
@jonwinkler @jasondegraw The failure of convergence is caused by part load ratio conflict. The existing code passes fan part ratio from Furnace to the AirflowNetwork. The AirflowNetwork model requires coil part load ratio. However, when coil flow rates are the same as the fan flow rate, the part load ratio of fan and coils are the same. When one of coil flow rates is different from the fan flow rate, and fan part load ratio is different from the coil part load ratio, the convergence failure occurs. My change is to pass the coil part ratio from furnace to AirflowNetwork.

Two test files were added with two type of systems: AirLoopHVAC:UnitaryHeatPump:AirToAir and AirLoopHVAC:UnitaryHeatCool.

Differences were found in an example file by running all example input files: AirflowNetwork_MultiZone_House.idf. The maximum difference is 10e-5 in the units of J. The cause is due to the last digit difference of Real64 (16th after decimal) between fan part load ratio and cooling part load ratio.

**Comment by Myoldmopar** [comment] 2015-09-24 11:27
Closed via #5213

**Closed as completed by Myoldmopar** 2015-09-24 11:27 UTC
