### ISSUE TITLE
Autosizing of heating coil UA failed for Coil:Heating:Water for plant loop exit temperature below 45C

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#5638] opened 2016-05-03 14:14 UTC
## Issue overview

Autosizing of heating coil UA failed for Coil:Heating:Water for plant loop exit temperature below 45C
See this unmet hour [post](https://unmethours.com/question/17066/plant-sizing-how-to-choose-the-design-loop-exit-temperature-and-temperature-difference/) and the subsequent comments by @EnergyArchmage 

> The hot water coil sizing routines break down when the Design Loop Exit Temperature goes below about 45C. It is unfortunate but the sizing method seems to have been developed for warmer hot water. It should be okay to use one set of values for sizing and then still operate the loop at the 40C.
> 
> I ran into this as a user once and found the 45C by trying a whole range of temperatures until it stopped failing with that error.
### Details
- Platform: All
- Version: EnergyPlus 8.5
### Checklist
- [x] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment] 2016-05-18 16:37
Julien, do you still have the file that fails with the bad UA error?

**Comment by jmarrec** [comment] 2016-05-19 11:55
I'm not the OP on unmet hours, it's urado. I'll connect you two via email

**Comment by EnergyArchmage** [comment] 2016-05-19 13:24
A defect file could be constructed from an integration testfile by changing the HW loop to size and operate at 40C.

**Comment by Nigusse** [comment] 2017-01-25 21:50
At such low heating coil water inlet temperature (< 45C), the coil water air outlet temperature can easily approach the heating coil water inlet temperature.  In this situation, effectiveness approaches almost 1.0 ( 0.9999 my test case), which means that the UA-value needed is very very huge (the theoretical limit being infinity when effectiveness is 1.0). This implies that the UA-value is not bound by design heating capacity (UA1=DataCapacityUsedForSizing) and Regulafalsi cannot find a solution in this range. So, there is no way of resolving this issue except suggesting to the user to increase the plant design loop exit temperature and/or reduce the plant design loop deltaT. 

I am looking at a way to estimate plant design loop exit temperature that avoids this situation and advise users during in such situation. Please let me know if you have concerns? @jmarrec @rraustad @EnergyArchmage @mjwitte

**Comment by EnergyArchmage** [comment] 2017-01-26 00:25
Seems like the warning should be for high leaving air temperature.  The lowish HW temps are reasonable, but users can't have it both ways.

**Comment by Nigusse** [comment] 2017-01-26 13:30
During the coil sizing both inlet temperatures (air and water) are fixed and the design load is already predetermined. The only variable that can change is the coil air leaving temperature but the maximum it can reach is coil water inlet temperature ( 40 C or 45 C in this case). You cannot heat coil air leaving temperature above the coil water inlet temperature and that is why we are having effectiveness of 1.0. I think the only option is to increase the coil water inlet temperature.

**Comment by rraustad** [comment] 2017-01-26 13:52
The only question here is how to protect RegulaFalsi so it doesn't fail. If the user want's to size the coil using 40C then we have to figure out what needs to be done to find a UA for that coil. Do we use a higher inlet water temp (min = 45C?) to size the coil and then let it operate at 40C inlet? What would a manufacturer do if someone called in with those operating conditions? They will certainly sell a coil to the caller. The first thing that comes to mind is that this coil will not meet the design load. That's OK, results will show unmet load, maybe the user is OK with that. Can we figure out what the minimum water inlet temperature is and then use that to size the coil? Or maybe just set UA = capacity and move on? There are probably other solutions. 

@larryscheier any insight into manufacturers sizing limits for water coils?

**Comment by rraustad** [comment] 2017-01-26 18:41
Comment from Larry:

    As far as Trace goes, the heating coils only follow the Btuh's around and don't care about HX 
    water temperature limits. If a htg coil is designed for 10000 Btuh, then the hourly htg load is
    met up to 10,000 Btuh during the HVAC simulation. If the hourly load exceeds design htg
    capacity, then the supply air leaving the hw coil is reduced proportionately and this may cause
    an unmet load.  The autosized hot water plant capacity is based on the sum of their design coil
    sizes if sized as noncoincident or the block hw design load if the hw plant is sized as coincident.
    The plant loop doesn't care about the plant water temperatures for the most part except when
    the boiler unloading curve is a function of return hw temperature.

We then called Colmac and requested sizing for a HW coil given inputs that we thought would fail. In a nutshell, they said to either increase the gpm or the entering water temperature. Since in E+ the gpm is already calculated, we'll try to minimally increase the water inlet temperature until a UA can be found to see if that seems reasonable. If not, then we'll probably just set UA = load and move on.

**Comment by EnergyArchmage** [comment] 2017-01-27 19:36
Perhaps better values for the design water delta T will help here, see issue #5655

**Comment by Nigusse** [comment] 2017-01-27 21:31
This fix traps low coil design inlet hot water temperature (< 46.0 C) and resets the coil design inlet hot water temperature to a minimum of 46.0 C for UA value sizing only. This fix sizes the UA to a reasonable value and eliminated UA-value auto-sizing calc failure due to low coil design inlet water temperature. I have also added a function that estimates design inlet water temperature for this purpose. Maximum of 46.0 and the estimated coil design inlet water temperature is used. Note that this temperature is used for UA-sizing only. And warning message is provided if this happens.

**Comment by rraustad** [comment] 2017-02-09 21:00
Closed via 5992

**Closed as completed by rraustad** 2017-02-09 21:00 UTC
Labels: SeverityMedium, PriorityLow
