### ISSUE TITLE
Update LCC to use 2020 and 2021 NIST supplement 

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9153] opened 2021-10-27 14:58 UTC
Issue overview
--------------
Add LCCusePriceEscalationDataSet20xx.idf for the 2020 and 2021 EIA energy price projections using data from:

https://www.energy.gov/eere/femp/building-life-cycle-cost-programs

Please note a script is available to do update this via #7218 created by @MatthewSteen

**Comment by jmarrec** [comment] 2022-07-26 13:08
Duplicate of #9551

**Closed as completed by jmarrec** 2022-07-26 13:08 UTC
Labels: NewFeatureRequest
