### ISSUE TITLE
Collapse EnergyPlus to a single Project

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5239] opened 2015-09-28 21:35 UTC
The static library was split during the LTO/PGO work, but since that isn't being used, it would be nice to just re-collapse them into a single project **OR** create a meaningful set of individual projects.  The split in half version is just awkward.

**Comment by mjwitte** [comment] 2016-03-09 18:44
@Myoldmopar I think this is a duplicate of #5368 - closing.

**Closed as completed by mjwitte** 2016-03-09 18:44 UTC
