### ISSUE TITLE
Chillers and WaterToWater Heat pumps will accept only a CondenserLoop on the Condenser or Source Side

### ISSUE THREAD

**Issue by KWSL** [NREL/EnergyPlus#4972] opened 2015-06-15 21:33 UTC
Chillers and WaterToWater Heat pumps will not operate if the condenser side is connected to a PlantLoop.  This eliminates the possibility of connecting the condenser side directly to a loop where heat recovery is desired.  Take the example of a building with a boiler and cooling tower both connected to a PlantLoop for use in a heat pump loop.  This building cannot also be modeled with a water to water heat pump connected to the same loop.

The curious thing is that the model will run with watertowater heat pumps and chillers connected to PlantLoops, but no heating or cooling is produced.

**Comment by KWSL** [comment] 2015-06-16 16:27
Another way to solve this would be to allow all the same plant equipment to provide the supply side of a Condenser Loop.  We would also need the setpointmanagers to work the same way as on a PlantLoop.

**Comment by mjwitte** [comment] 2015-06-16 17:46
@KWSL There must be something else going on here.  I have connected the condenser side of a chiller to a PlantLoop, and the WaterToWater Heat Pumps also.  Please e-mail examples to me directly.  Thanks.

**Comment by KWSL** [comment] 2015-06-16 18:25
emailed.  Montpelier, VT TMY3 weather file and simulated using version 8.3.3

**Comment by mjwitte** [comment] 2015-06-19 18:40
Same issue as #4385 but different defect files.

**Comment by mjwitte** [comment] 2015-06-19 22:09
And helpdesk ticket 10532

**Comment by KWSL** [comment] 2015-06-30 14:12
I'd be happy to try to figure out what this is, if someone can give me some suggestions on where to begin looking.  From my test files, when one of these components is attached to a PlantLoop, the simulation runs fine, but there is never any source side flow.  Even if I hard-size the flow-rate at the branch level, I don't get any flow.  This leads me to believe that the issue is with normal run-time and not with sizing.  Any ideas on subroutines to start looking in?

**Comment by mjwitte** [comment] 2015-06-30 16:42
@Myoldmopar Any suggestions for @KWSL for where to look for flow controls that would behave differently for a component when it's on a plant loop vs condenser loop?

**Comment by Myoldmopar** [comment] 2015-06-30 20:20
That's a pretty interesting issue.  There are very very few places in the source that still consider a difference between plant and condenser loops.  I'll take this issue and see what I can come up with.

**Comment by KWSL** [comment] 2015-06-30 21:18
I know.  I started looking yesterday, and found very few differences, only in setting up allowable SetpointManagers and Plant Loop Demand Calculation Scheme.

Thanks for taking this on @Myoldmopar.  I contributed a minor update to the WatertoAirHeatPump model a few years ago, so I have some familiarity with the code, but it's a lot to search for a bug like this without having a deeper understanding of the program!

**Comment by mjwitte** [comment] 2015-09-15 18:35
@KWSL The GLHE problem has been fixed in #5184.  We can't reproduce a problem for the chiller.  4972_ChillerCondOnCondenserLoop and 4972_ChillerCondOnPlantLoop produce the same results.  If you have another file that does show a problem for chillers with the condenser on a plant loop, please send it to me.

**Comment by KWSL** [comment] 2015-09-30 18:53
sweet!  I don't have a specific test file for the chillers.

Thanks,

Karen

**Comment by mjwitte** [comment] 2015-12-05 11:33
Cannot reproduce, closing.

**Closed as completed by mjwitte** 2015-12-05 11:33 UTC
Labels: SeverityHigh, PriorityLow
