### ISSUE TITLE
TOC and bookmarks missing in InputOutputReference documentation

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8678] opened 2021-03-31 14:04 UTC
Issue overview
--------------
In InputOutputReference.pdf, the Table of Content is missing, and the most of the document bookmarks are missing: 

![image](https://user-images.githubusercontent.com/64040111/113156635-c99b0580-91ff-11eb-8f92-1e08d97d2158.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) All
 - Version of EnergyPlus (if using an intermediate build, include SHA) v9.5
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment] 2021-03-31 14:05
Duplicate of #8568

**Closed as completed by Myoldmopar** 2021-03-31 14:05 UTC
