### ISSUE TITLE
SpaceGainsMonthly report is missing from eplustbl.csv

### ISSUE THREAD

**Issue by dmac000** [NREL/EnergyPlus#6863] opened 2018-07-27 15:25 UTC
The SpaceGainsMonthly report isn't included in `eplustbl.csv` after upgrading to 8.9, but was there in 8.8.

After debugging, I see that `FindItemInVariableList` in `DataOutputs.cc` is now case-sensitive, but the output variables are created in mixed-case. Changing it back to make `VariableName` uppercase results in the report being created.

IDF: `1ZoneEvapCooler.idf` with these changes:

    OutputControl:Table:Style,
      Comma, !- Column Separator
      JtoKWH; ! Unit Conversion

    Output:Table:SummaryReports,
      SpaceGainsMonthly;

**Comment by mjwitte** [comment] 2018-08-27 16:18
So, it this an issue for *all* of the monthly summary reports?

**Comment by dmac000** [comment] 2018-08-29 10:56
Some of the reports are there but a few of the others are missing. I tried adding "AllMonthly" to the idf, and the csv results are about half the length from 8.8 to 8.9.

[1ZoneEvapCoolerTable-8.8.csv.txt](https://github.com/NREL/EnergyPlus/files/2331826/1ZoneEvapCoolerTable-8.8.csv.txt)
[1ZoneEvapCoolerTable-8.9.csv.txt](https://github.com/NREL/EnergyPlus/files/2331827/1ZoneEvapCoolerTable-8.9.csv.txt)

**Comment by JasonGlazer** [comment] 2018-10-25 13:09
I'm working on this issue.

**Comment by mjwitte** [comment] 2018-10-25 15:41
@JasonGlazer This may be related to #7019

**Comment by jmarrec** [comment] 2018-10-26 08:36
Duplicate of #7019, and I fixed this in #7031 already (confirmed with user example above)

**Closed as completed by jmarrec** 2018-10-26 08:36 UTC
Labels: PriorityHigh
