### ISSUE TITLE
Warning "Windows has protected your PC" when running 9.3 installer

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#8198] opened 2020-08-12 13:36 UTC
When I ran the 9.3 installer on Windows 10, it gave me a malware warning. This is the full 9.3 installer (not the later bug fix installer) which I downloaded from here.

![image](https://user-images.githubusercontent.com/18285074/90020932-8d219600-dc7e-11ea-955f-ff0d20040465.png)

Possibly related - later on once actual installation has started, a yellow UAC prompt comes up with the wording "unknown publisher". This probably is because the installer is not code signed.

---

Edit - this was using installer `EnergyPlus-9.3.0-64d91887f6-Windows-i386.exe`

**Comment by jmarrec** [comment] 2020-08-13 07:00
@DaveInCaz Did you get the warning when you tried the 64 bit version prior to trying the 32 bit one?

code signing / download counts is likely the problem yes. Without an extended EV Authenticode (with is problematic because of 1) cost, and 2) automation since you historically needed a physical device though that seems to have changed with cloud HSMs...), you need a bunch of downloads & install before reputation builds up, and the i386 (32bit) package is really not used a lot in these modern days.

**Comment by DavidHollman** [comment] 2020-08-13 11:19
Yes that was the 32-bit installer (I added the installer filename to the issue).

I just downloaded and tried the 64-bit installer (`EnergyPlus-9.3.0-baff08990c-Windows-x86_64.exe`) and it did NOT show the warning.

However, I also tried the 32-bit installer again, and today - _no warning_. I don't know what that means, its literally the same file I had downloaded yesterday.  Maybe its the reputation gain you mentioned, or maybe something else (?).  I also don't know that the 64-bit installer isn't working for the same reason.

**Comment by jmarrec** [comment] 2020-08-13 11:54
I'm not sure how windows work but I would reckon when you clicked on "run anyways" the first time, it added it to some kind of exclusion list, similar to how a browser would do if you encounter an invalid certificate. That's probably why you didn't see it the second time

**Comment by DavidHollman** [comment] 2020-08-13 11:57
@jmarrec I guess that could be the case with Defender issues like this, I'm not sure either.

If that is the case then I don't think it really solves the problem, because the issue for some users will be that the first time they see this, they won't run it. Also, some IT organizations simply won't allow it, not really giving users the choice.

**Comment by jmarrec** [comment] 2022-07-19 12:40
duplicate of https://github.com/NREL/EnergyPlus/issues/6364

**Closed as completed by jmarrec** 2022-07-19 12:40 UTC
Labels: Developer Issue
