### ISSUE TITLE
Chiller:Absorption hot water flow problems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5910] opened 2016-10-17 21:36 UTC
## Issue overview

User notes that Chiller:Absorption hot water source flow is always at max, even though the HW loop has variable flow pumps and the chiller flow mode is NotModulated.  This results in the source HW loop overheating late in the cooling season as the pump heat exceeds the heat requirement from the absorption chiller.  

I tried a test of with the chiller flow mode changed to LeavingSetpointModulated, but this failed with very cold temperatures leaving the chiller hot water outlet node, -90C.  The flow rates do vary with this flow mode, and the leaving hot water temperatures look reasonable on the summer design day, and again when the chiller comes on for a few days in April. But on the day that the simulation fails, the chiller loads and flow rates seem reasonable, but the leaving hot water temperature nosedives.  See ABSORBERHWOUTLETNODE:System Node Temperature.
### Details

Some additional details for this issue (if relevant):
- Platform Win64
- Version of EnergyPlus 8.6.0
- helpdesk ticket 11467
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added EnergyPlusDevSupport\DefectFiles, use ITA_BOLOGNA-BORGO PANIGALE_IGDG.epw
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment] 2017-05-15 18:01
Chiller:Absorption with flow type specified as "NoModulated" results maximum flow through the generator hot water loop by design, and when there is a cooling load on the chiller, the generator hot water loop pump adds heat to the loop fluid depending on the water flow rate and pump pressure rise. There are two issues that I noted when investigating this bug issue:

(1) The generator hot water loop pump pressure rise specified is very high, 1247600.0 Pa. The loop pump max fluid heat gain rate is 19,193.8 W.  This is much higher than the load on the generator during low cooling load season. This is April in moderate climate location Bologna, Italy weather. Thus, there is a constant heat build up in the hot water loop. Reducing the pump pressure rise equal to that of the chilled water loop pump (244,435 Pa), reduced the heat build up and the example file to run to completion. Sometimes, pump fluid heat was enough to provide heat to the generator.

(2) This is more of a suspicion. The generator's heat input rate is calculated [here](https://github.com/NREL/EnergyPlus/blob/145457349_Issue%235910/src/EnergyPlus/ChillerAbsorption.cc#L1562):

		QGenerator = SteamInputRat * QEvaporator * FRAC;

I am suspicious why we need to multiply QEvaporator by FRAC (CyclingRatio). Note that this equation is correct per the engineering reference. But, the generator heat input rate is already scaled using actual chiller load, QEvap, not the available chiller capacity.  This also leads to unrealistic COP value.  I suggest to drop the FRAC term and change the equation to this:

		QGenerator = SteamInputRat * QEvaporator;
 
@mjwitte @Myoldmopar @rraustad @EnergyArchmage  Let me know what your thoughts are.

**Comment by Nigusse** [comment] 2017-05-16 20:54
Flow Mode specified as "LeavingSetpointModulated" failed even with reduced pump pressure rise. There is more issue to this Flow Mode. The chiller Flow Mode is applied to the Generator flow rate calculation. I think, we should not apply the chiller Flow Mode to the generator as well. The heat generator source is a boiler that has s separate loop and in this case the Boiler Flow Mode is set to "NoModulated".  Need to look it again.

**Comment by Myoldmopar** [comment] 2018-03-16 03:15
Closed via #6511

**Closed as completed by Myoldmopar** 2018-03-16 03:15 UTC
Labels: SeverityMedium, PriorityLow
