### ISSUE TITLE
Utilities Folder Blank in V9.3

### ISSUE THREAD

**Issue by Sramac10** [NREL/EnergyPlus#8114] opened 2020-06-26 17:38 UTC
Issue overview
--------------
Utilities tab is blank in E+ v9.3 that i had installed recently. Is there a way to fix it? 

![image](https://user-images.githubusercontent.com/67479269/85885393-1a755d80-b799-11ea-9f1f-c92452b95248.png)

**Comment by mjwitte** [comment] 2020-06-28 19:58
This is a duplicate of #7910. It is fixed in the [v9.3.0 bug fix release.](https://github.com/NREL/EnergyPlus/releases/tag/v9.3.0-BugFix)

**Closed as completed by mjwitte** 2020-06-28 19:58 UTC
