### ISSUE TITLE
EnergyPlus shading control errors - too many controlled shaded windows in zone

### ISSUE THREAD

**Issue by hongyuanjia** [NREL/EnergyPlus#7511] opened 2019-09-19 08:37 UTC
### Overview
The attached defect file generates these types of warnings:
```
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE

   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
```

### Workaround
The first warning is a true warning, review WindowShadingControl objects to be sure that "Zone Name" is consistent with both the "Daylighting Control Object Name" and the listed Fenestration Surfaces.

The second warning is a false warning and may be ignored.

### Details

 - Platform: Windows 8.1, Windows 10, ArchLinux
 - Version of EnergyPlus: v9.0 & v9.1

I encountered an issue that EnergyPlus **randomly** crashes on my model. I really cannot figure out where the problem comes from. The wired thing is that sometimes it ran successfully, but sometimes it didn't. This occurred both on my linux and windows machine, for both EnergyPlus v9.0 and v9.1.

I am not sure if this is related to https://github.com/NREL/EnergyPlus/issues/7223. But I believe there is something going wrong in daylighting controls. As you can see from the error message, there is several warning messages saying that there are too many controlled shaded windows for zone `Zone 1-Office` and empty map for windows for zone `Zone 3-3`.

I searched the code base and found that these messages were generated by function `MapShadeDeploymentOrderToLoopNumber`:

https://github.com/NREL/EnergyPlus/blob/65479e0be49b834870ffc79170785a64ab62634e/src/EnergyPlus/DaylightingManager.cc#L10845-L10878

I have double checked that all fenestration surfaces listed in `WindowShadingControl` belongs to the right zone. So I did not know where I should start for debugging my model.

Below is the model file. 
[test.txt](https://github.com/NREL/EnergyPlus/files/3630138/test.txt)

<details>
  <summary>Contents of error messages</summary>
<p>

```
Program Version,EnergyPlus, Version 9.1.0-08d2e308bb, YMD=2019.09.19 15:02,
   ************* Beginning Zone Sizing Calculations
   ** Warning ** Site:GroundTemperature:BuildingSurface: Some values fall outside the range of 15-25C.
   **   ~~~   ** These values may be inappropriate.  Please consult the Input Output Reference for more details.
   ** Warning ** CheckUsedConstructions: There are 3 nominally unused constructions in input.
   **   ~~~   ** Each Unused construction is shown.
   ************* Construction=ZEB_GLASS_DOOR
   ************* Construction=ZEB_DOOR
   ************* Construction=ZEB_IRTSURFACE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3
   ** Warning ** Calculated design heating load for zone=MEETING_ROOM_1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=MEETING_ROOM_2 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=MEETING_ROOM_3 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=SERVER_ROOM is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 1-OFFICE is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 1-PANTRY is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 2 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 3-1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** Calculated design heating load for zone=ZONE 3-3 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ************* Beginning System Sizing Calculations
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AHU 1 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AHU 2 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=AHU 3 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=FCU 5 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ** Warning ** ManageSizing: Calculated Heating Design Air Flow Rate for System=FCU 4 is zero.
   **   ~~~   ** Check Sizing:Zone and ZoneControl:Thermostat inputs.
   ************* Beginning Plant Sizing Calculations
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 1
   **   ~~~   ** User-Specified Design Inlet Air Temperature [C] = 33.00000
   **   ~~~   ** differs from Design Size Design Inlet Air Temperature [C] = 29.03919
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 1
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 1.08000E-003
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 8.46274E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water ZONE 1
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 1.552048E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9876
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5116
   **   ~~~   **                                    Wair,out = 8.692330E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME 1
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 1.17000
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.39515
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 2
   **   ~~~   ** User-Specified Design Inlet Air Temperature [C] = 33.00000
   **   ~~~   ** differs from Design Size Design Inlet Air Temperature [C] = 29.08417
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 2
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 1.42000E-003
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 9.78993E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water ZONE 2
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 1.561284E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9877
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5116
   **   ~~~   **                                    Wair,out = 8.692362E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME 2
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 1.61000
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.45425
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water ZONE 3
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 1.80000E-003
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 9.21295E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water ZONE 3
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 1.827733E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9916
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5132
   **   ~~~   **                                    Wair,out = 8.693280E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME 3
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 2.08000
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 0.36186
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water MEETING_ROOM_1
   **   ~~~   ** User-Specified Design Water Flow Rate [m3/s] = 2.90000E-004
   **   ~~~   ** differs from Design Size Design Water Flow Rate [m3/s] = 1.48857E-004
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeWaterCoil: Potential issue with equipment sizing for Coil:Cooling:Water MEETING_ROOM_1
   **   ~~~   ** User-Specified Design Air Flow Rate [m3/s] = 1.36000E-003
   **   ~~~   ** differs from Design Size Design Air Flow Rate [m3/s] = 5.08446E-002
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water MEETING_ROOM_1
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 2.087994E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9954
   **   ~~~   **                                    Wair,out = 8.500000E-003
   **   ~~~   ** The revised design conditions are: Tair,out = 13.5148
   **   ~~~   **                                    Wair,out = 8.694169E-003
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume FAN VARIABLE VOLUME OF FCU 5
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 1.36000E-003
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 5.08446E-002
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ************* SizeDXCoil: Potential issue with equipment sizing for Coil:Cooling:DX:SingleSpeed DX COIL FOR SERVER_ROOM
   **   ~~~   ** User-Specified Gross Rated Total Cooling Capacity [W] = 5000.00000
   **   ~~~   ** differs from Design Size Gross Rated Total Cooling Capacity [W] = 1369.74521
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** Sizing: Coil:Cooling:DX:SingleSpeed "DX COIL FOR SERVER_ROOM": Rated air volume flow rate per watt of rated total cooling capacity is out of range.
   **   ~~~   ** Min Rated Vol Flow Per Watt=[4.027E-005], Rated Vol Flow Per Watt=[5.053E-006], Max Rated Vol Flow Per Watt=[6.041E-005]. See Input Output Reference Manual for valid range.
   ** Warning ** For object = Coil:Cooling:DX:SingleSpeed, name = "DX COIL FOR SERVER_ROOM"
   **   ~~~   ** Calculated outlet air relative humidity greater than 1. The combination of
   **   ~~~   ** rated air volume flow rate, total cooling capacity and sensible heat ratio yields coil exiting
   **   ~~~   ** air conditions above the saturation curve. Possible fixes are to reduce the rated total cooling
   **   ~~~   ** capacity, increase the rated air volume flow rate, or reduce the rated sensible heat ratio for this coil.
   **   ~~~   ** If autosizing, it is recommended that all three of these values be autosized.
   **   ~~~   ** ...Inputs used for calculating cooling coil bypass factor.
   **   ~~~   ** ...Inlet Air Temperature     = 26.67 C
   **   ~~~   ** ...Outlet Air Temperature    = -115.05 C
   **   ~~~   ** ...Inlet Air Humidity Ratio  = 1.125000E-002 kgWater/kgDryAir
   **   ~~~   ** ...Outlet Air Humidity Ratio = 1.000000E-005 kgWater/kgDryAir
   **   ~~~   ** ...Total Cooling Capacity used in calculation = 5000.00 W
   **   ~~~   ** ...Air Mass Flow Rate used in calculation     = 2.922675E-002 kg/s
   **   ~~~   ** ...Air Volume Flow Rate used in calculation   = 2.526892E-002 m3/s
   **   ~~~   ** ...Air Volume Flow Rate per Watt of Rated Cooling Capacity is also out of bounds at = 5.0537846E-006 m3/s/W
   **   ~~~   **  During Warmup, Environment=DESIGN_DAY_APR, at Simulation time=04/21 00:00 - 00:15
   **   ~~~   ** CalcCBF: SHR adjusted to achieve valid outlet air properties and the simulation continues.
   **   ~~~   ** CalcCBF: initial SHR = 0.49908
   **   ~~~   ** CalcCBF: adjusted SHR = 0.83243
   ************* SizeFan: : Potential issue with equipment sizing for Fan:VariableVolume DX FAN
   **   ~~~   ** User-Specified Maximum Flow Rate [m3/s] = 8.10000E-004
   **   ~~~   ** differs from Design Size Maximum Flow Rate [m3/s] = 2.52689E-002
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
   **   ~~~   ** Verify that the value entered is intended and is consistent with other components.
   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water SERVER_ROOM
   **   ~~~   ** no apparatus dew-point can be found for the initial entering and leaving conditions;
   **   ~~~   ** the coil outlet design conditions will be changed to correct the problem.
   **   ~~~   ** The initial design conditions are: Tair,in = 33.0000
   **   ~~~   **                                    Wair,in = 2.152708E-002
   **   ~~~   **                                    Twater,in = 7.0000
   **   ~~~   **                                    Tair,out = 13.9963
   **   ~~~   **                                  
```

</p>
</details>

Thanks in advance for your help.

**Comment by mjwitte** [comment] 2019-09-20 20:22
The crash is unrelated to WindowShadingControl. The crash is in a system reporting function (arrays bounds error), because this file has two air terminal units in the same zone served by the same airloop. Posting a new issue for this problem. #7518 

After that is fixed, then I'll work on figuring out the daylighting errors here.

**Comment by hongyuanjia** [comment] 2019-09-21 04:41
@mjwitte Thanks a lot for investigating this!

**Comment by Myoldmopar** [comment] 2019-09-23 14:11
Do we need to adjust the title of this now that you have addressed the crash portion of this @mjwitte?  And with the crash gone, is this urgent enough to try to get in for this release?

**Comment by mjwitte** [comment] 2019-09-23 14:35
Title updated. Not sure if the remaining issue is urgent - will investigate now.

**Comment by mjwitte** [comment] 2019-09-23 15:21
@hongyuanjia Regarding these warnings:
```
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: too many controlled shaded windows in zone ZONE 1-OFFICE
   ** Warning ** MapShadeDeploymentOrderToLoopNumber: found unassociated window for zone ZONE 1-OFFICE
```
There is one WindowShadingControl object which specifies the wrong Zone Name:
```
  WindowShadingControl,
    Blinds-Zone 1-Pantry,    !- Name
    Zone 1-Office,           !- Zone Name
```
With that changed to "Zone 1-Pantry" the above warnings are gone.

But the warning for `MapShadeDeploymentOrderToLoopNumber: found empty map for window in zone ZONE 3-3` remains.

This is a false warning which happens because not every window in Zone3-3 is included in the WindowShadingControl. The logic in `MapShadeDeploymentOrderToLoopNumber` does not currently anticipate this possibility. This warning can be ignored. 

@Myoldmopar This issue will be addressed after v9.2 release to:
1. Supress the false warnings
2. Add more information to the warnings to identify where the error is, and 
3. Assure that the logic accounts for daylighting enclosures which extend across multiple zones when using air boundary "surfaces" (new in v9.2).

**Comment by hongyuanjia** [comment] 2019-09-23 15:29
@mjwitte Oh, thanks for catching this! I was not able to catch this error. Good to know that I can just ignore the remaining warnings.

**Comment by mjwitte** [comment] 2020-09-21 22:20
@JasonGlazer Do you know if this issue is resolved by the shading control changes in #8269 ?

**Comment by JasonGlazer** [comment] 2020-09-22 16:03
I did not address this issue specifically

**Comment by mjwitte** [comment] 2020-09-23 01:24
Confirmed that these warnings are still present in v9.4.0-575a350ad4 (almost release).

**Closed as completed** 2022-03-18 19:00 UTC
