### ISSUE TITLE
Incorrect location for RunReadVars

### ISSUE THREAD

**Issue by jamiebull1** [NREL/EnergyPlus#5108] opened 2015-08-17 14:32 UTC
Running EnergyPlus from the command line interface with the `--runreadvars` flag set raises an error (on Windows 10 with EnergyPlus 8.3):

`ERROR: Could not find ReadVarsESO executable: C:\EnergyPlusV8-3-0\ReadVarsESO.exe.`

The program is looking for `ReadVarsESO.exe` in the wrong place (the `C:\EnergyPlusV8-3-0` rather than `C:\EnergyPlusV8-3-0\Postprocess`.

**Comment by MatthewSteen** [comment] 2015-08-17 15:19
duplicate of #5058?

**Comment by jamiebull1** [comment] 2015-08-17 15:48
Ah yes. Looks like it. So it will be fixed and I can workaround for now by copying `ReadVarsESO.exe` into the EnergyPlus root?

**Comment by MatthewSteen** [comment] 2015-08-17 15:56
@jamiebull1 I would think so, although I haven't run EP yet using the CLI.

**Comment by jamiebull1** [comment] 2015-08-17 16:09
@MatthewSteen Yes, that works fine.

**Closed as completed** 2015-08-17 16:09 UTC
