### ISSUE TITLE
Sky temperature is always zero when weather file has subhourly data

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5604] opened 2016-04-11 23:32 UTC
## Issue overview

User's initial concern was that WeatherProperty:SkyTemperature had not impact on the simulation results.  It turns out that something about the user's custom weather file was causing the sky temperature to always be zero, with and without the WeatherProperty:SkyTemperature object.
1.  Whatever is in the weather file that results in sky temperatures of zero should generate a warning.
2.  The WeatherProperty:SkyTemperature object should always work, regardless of what's in the weather file.
### Details

Some additional details for this issue (if relevant):
- Win64
- Version of EnergyPlus v8.5.0
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles\5604)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment] 2016-04-11 23:35
Also see first item in #5603

**Comment by lklawrie** [comment] 2016-04-12 00:21
The problem is that the user weather file is a multiple interval file (4 intervals per hour) and the part of the if that includes the setting for scheduled sky temperatures should also be in the "else" of this if.  I can modify the Fortran in v8.1 to test and then include.

**Comment by JasonGlazer** [comment] 2016-05-19 18:10
@lklawrie Did you ever make a Fortran change to fix this?

**Comment by Myoldmopar** [comment] 2016-06-09 14:03
Closed via #5680

**Closed as completed by Myoldmopar** 2016-06-09 14:03 UTC
Labels: PriorityLow
