### ISSUE TITLE
Coil:WaterHeating:AirToWaterHeatPump OutputVariable names for heating reference cooling coils 

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#6767] opened 2018-05-31 03:01 UTC
Issue overview
--------------
The variable names for the heat pump water heater (HPWH) heating coil reference cooling coils instead of heating coils and must be requested with the Cooling Coil names.

__Input Output Reference__
* [Coil:WaterHeating:AirToWaterHeatPump:Pumped](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex#L5711-L5736)
* [Coil:WaterHeating:AirToWaterHeatPump:Wrapped](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex#L5931-L5960)

---

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by YanfeiNREL** [comment] 2019-07-26 22:07
@MatthewSteen Hey, would you please point me where did u find the issue? It is in the code of DXCoils.cc? Or WaterThermalTanks.cc? Or the code to generate the Input/Output References? Or from the EnergyPlus simulation outputs?Thanks.

**Comment by MatthewSteen** [comment] 2019-07-27 01:40
Based on the links I provided, it was a documentation issue.

**Comment by MatthewSteen** [comment] 2019-07-27 01:56
Based on the link, I believe it was a documentation issue. See the last four OutputVariable names.

    HVAC,Average,Cooling Coil Total Cooling Rate [W]

    HVAC,Sum,Cooling Coil Total Cooling Energy [J]

    HVAC,Average,Cooling Coil Sensible Cooling Rate [W]

    HVAC,Sum,Cooling Coil Sensible Cooling Energy [J]

    HVAC,Average,Cooling Coil Latent Cooling Rate [W]

    HVAC,Sum,Cooling Coil Latent Cooling Energy [J]

    HVAC,Average, Cooling Coil Runtime Fraction []

    HVAC,Average,DX Cooling Coil Crankcase Heater Electric Power [W]

    HVAC,Sum, Cooling Coil Crankcase Heater Electric Energy [J]

    HVAC,Average,Cooling Coil Total Water Heating Rate [W]

    HVAC,Sum,Cooling Coil Total Water Heating Energy [J]

    HVAC,Average,Cooling Coil Water Heating Electric Power[W]

    HVAC,Sum,Cooling Coil Water Heating Electric Energy [J]

**Comment by YanfeiNREL** [comment] 2019-07-29 22:08
@MatthewSteen Which documentation do you mean for the "documentation"?  I found the issue in simulation output file(csv file), and Input/Output Ref. I want to make sure if there are other types of documentation having this issue if you know.

**Comment by MatthewSteen** [comment] 2019-07-29 22:10
Yes, I/O ref per my links.

**Comment by YanfeiNREL** [comment] 2019-07-29 22:11
@MatthewSteen Okay, Thanks.

**Comment by mjwitte** [comment] 2019-08-07 15:19
This is related to #7440, which is actually the same issue.

@YanfeiNREL #7439 - changing the I/O Ref is incomplete. The code is using the "Cooling Coil . . . " names, so the current I/O Ref is consistent with the code. If we change one, we have to change both.

@MatthewSteen From the air-side perspective,  Coil:WaterHeating:AirToWaterHeatPump* objects are a cooling coil, so it was intentional to use "Cooling Coil . . . " in the output variable names for consistency with other DX cooling coils.

But I understand the confusion by doing that. We could keep the "Cooling Coil . . . " names for the air side here, and change the water side outputs to "Heat Pump Coil Total Water Heating Rate" (or delete Total?) or some other suggestion. Or we could change all of the output variable names here to "Heat Pump Coil  . . " or some other suggestion. Or we could just leave things alone and add a note to the I/O Ref explaining the reasoning for the current names. 

@rraustad @Myoldmopar @shorowit @nmerket - thoughts?

**Comment by YanfeiNREL** [comment] 2019-08-07 15:59
@mjwitte Thanks for your clarifying. I was also confused for the Coil:WaterHeating:AirToWaterHeatPump*. I see the input fields for those objects are talking "heating" properties. I will close this issue, if no further suggestions.

**Comment by rraustad** [comment] 2019-08-07 16:41
I would avoid changing the cooling coil report names since those report names should be consistent across the different component types (unless this cooling coil type should be differentiated). For table reporting a single key should aggregate all like components. On the heating side a different name might me more appropriate if the current name causes mass confusion.

```
Output:Table:Monthly,
  Coil Report,                            !- Name
  ,                                       !- Digits After Decimal
  Heating Coil Heating Energy,            !- Variable or Meter Name 1
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 1
  Heating Coil Heating Rate,              !- Variable or Meter Name 2
  Maximum,                                !- Aggregation Type for Variable or Meter 2
  Cooling Coil Total Cooling Energy,      !- Variable or Meter Name 3
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 3
  Cooling Coil Sensible Cooling Energy,   !- Variable or Meter Name 4
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 4
  Cooling Coil Total Cooling Rate,        !- Variable or Meter Name 5
  Maximum,                                !- Aggregation Type for Variable or Meter 5
```

**Comment by MatthewSteen** [comment] 2019-08-07 16:47
@mjwitte thanks for the comments and clarification. For context, the HPWH objects in my model were used to approximate an air-to-water heat pump chiller.

**Comment by YanfeiNREL** [comment] 2019-08-13 21:50
@mjwitte , which approach do i need to adopt to improve this issue with minimum efforts?

**Comment by MatthewSteen** [comment] 2019-08-13 21:59
Seems like the easiest fix would be to update the docs explaining the reasoning for the OutputVariable names, which would (1) keep the naming convention consistent and (2) address this issue rather than potentially needing to open a new one to change the `/src` code.

**Comment by YanfeiNREL** [comment] 2019-08-21 15:17
The issue is the same with #7460 . I update the DOC to further explain why we use "cooling coil" output variables for this type of Heating-Coil. I am closing it.

**Closed as completed by YanfeiNREL** 2019-08-21 15:17 UTC
