### ISSUE TITLE
MSCOMCTL.OCX missing from 8.3.0 installer?

### ISSUE THREAD

**Issue by bachc** [NREL/EnergyPlus#5105] opened 2015-08-14 13:42 UTC
Hi there, it seems that MSCOMCTL.OCX might be missing from the 8.3.0 installer:
![clipboard02](https://cloud.githubusercontent.com/assets/2520741/9274992/b3d54864-425f-11e5-93c3-83d6004537c0.png)

I had the problem on a machine with Windows 8.1 Enterprise (64 bit), but it wasn't an issue on a different machine with Windows 8.1 Pro (64 bit). Not quite the same programs installed on both machines, could be that the OCX file was either provided by Windows Pro or by a third party program on that machine.

**Comment by mitchute** [comment] 2015-10-09 20:52
Also had another OSU user who could not run 8.4 because MSINET.OCX was missing. Let me know--I can track down more details if needed.

**Comment by mjwitte** [comment] 2015-10-16 17:10
@bachc @mmatts These ocx files are in the installer, but there may be some version compatibility problem or something else preventing them from installing properly.
@kbenne Can the installer produce a log file so we can see what's happening (or not happening) in these cases?

**Comment by kbenne** [comment] 2015-10-16 20:15
it seems so.

http://nsis.sourceforge.net/Logging:Enable_Logs_Quickly
http://nsis.sourceforge.net/Dump_log_to_file
http://stackoverflow.com/questions/861297/saving-nsis-install-log

**Comment by kylezoa** [comment] 2015-12-17 02:30
Issue also occurs on Windows 10 64-bit. msinet.ocx was not found on startup of EP-Launch. However the file was found in windows\syswow64 after installation.

Had to use this command for Windows to recognize the file is in windows\syswow64:

```
regsvr32 c:\windows\syswow64\msinet.ocx
```

**Comment by mjwitte** [comment] 2016-05-02 22:23
Helpdesk ticket 11280 another Win10 user, MSOMCTL.OCX not found.

**Comment by mjwitte** [comment] 2016-06-03 15:44
Until this is fixed, the workaround is to install [EnergyPlus v8.2.0](https://github.com/NREL/EnergyPlus/releases/tag/v8.2.0-Update-1.2) on the target machine and this will add the necessary files.  v8.2.0 may be uninstalled immediately if desired. The files should remain in place and later versions of EP-Launch and IDF Editor should work on that machine.

**Comment by JasonGlazer** [comment] 2016-08-29 13:10
I just tried to reproduce the problem by creating a new WIndows 10 computer (1511 OS Build 10586.164. 64-bit) as a virtual machine and installing the release version of 8.5.0 and running EP-Launch and IDF Editor and did not see any message related to the MSOMCTL.OCX. I tried this also with a new Windows 8.1 64-bit virtual machine and it also did not reproduce the problem. @bachc and @mitchute and @kylezoa is there anything else about the configuration of the operating system that you can tell me about that might help me reproduce the issue?

**Comment by mitchute** [comment] 2016-08-29 13:19
Been awhile and I think the person who had the issue is long gone, so I don't think I have more to add. I have a Windows tablet with a relatively fresh install of Windows 10. I'll give it a try this evening and let you know.

**Comment by kylezoa** [comment] 2016-08-29 13:30
@JasonGlazer I have nothing to add either, it may have been a configuration error caused by another program.

**Comment by bachc** [comment] 2016-08-29 14:15
I'd guess the next time I use E+ I'll be either running Windows 10 or use the same machine. Windows 8 is probably on its way out. Seems to me that leaving it with the workaround suggested by mwitte on June 3 is the best use of everyone's resources.

**Comment by mitchute** [comment] 2016-08-30 13:22
I successfully installed and ran 8.3 on Windows 10.

**Comment by JasonGlazer** [comment] 2016-08-30 19:11
Thanks @bachc @mitchute and @kylezoa. I decided to just try to add some logging to the installer for now.

**Comment by EnergyArchmage** [comment] 2017-03-30 15:23
I recently started getting this error on Windows 10.  Appeared after installing version 8.7 (or maybe also reinstalling version 8.6). EPLaunch no longer runs on my machine for all different installed version of e+.

**Comment by mitchute** [comment] 2020-02-03 04:15
It's been almost 3 yrs since any activity on this issue. Closing, but we can reopen it if necessary if this shows up again.

**Closed as completed by mitchute** 2020-02-03 04:15 UTC
Labels: Defect, SeverityHigh, PriorityLow
