### ISSUE TITLE
Find Simple Root Controller Error

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4332] opened 2014-06-25 14:29 UTC
MJW comment  12 December 2013
I suppose this file should cause a CR to figure out why it fataled out.

User complains;
> > I have a file(attached) that is exiting with the following fatal error:
 > >
 > > ** Severe ** FindRootSimpleController: Root finder failed at RUN,
 > 22:00:00.0 - 22:15:00.0
 > > ** ~~~ ** Controller name=2 20 KITCHEN K HC CONTROLLER
 > > ** ~~~ ** Controller action=Normal action
 > > ** ~~~ ** Root candidate x=9.998980000000000E-005 does not lie within
 > the lower/upper brackets.
 > > ** ~~~ ** Upper bracket is x=0.000000000000000
 > >
 > > I am using the latest version of EnergyPlus and running the file with
 > the Burlington, VT weather file.
 > >
 > > I am not sure how to resolve this error.

MJW response to user
> Well, that's a new flavor of Root finder error .
 >
 > The fix is to change all of your controller "Minimum Actuated Flow" fields
 > to 0.0 and this file will run to completion. Non-zero min flow rates are
 > not well supported and can cause issues. I generally set those to zero
 > (everywhere they are available). That said, this should not cause a fatal
 > error - we will try to sort that out.

Helpdesk Ticket 8911

User file
131207_BaseHVAC_Original,idf

**Comment by Myoldmopar** [comment] 2015-08-13 15:54
I think it is a duplicate.

**Comment by Myoldmopar** [comment] 2015-08-13 17:12
Yep, duplicate of #4187 and more info over there.  Closing this newer one.

**Closed by Myoldmopar** 2015-08-13 17:12 UTC
Labels: EnergyPlus, Priority, S2 - Medium
