### ISSUE TITLE
Do not open standard error output file in unit tests and other unit test problems

### ISSUE THREAD

**Issue by wfbuhl** [NREL/EnergyPlus#4823] opened 2015-03-25 18:28 UTC
The standard error output file (eplusout.err) is accessed only through the function ShowErrorMessage in UtilityRoutines.cc. This function handles the opening of eplusout.err so there is no need to open this file in any unit test. In fact code such as (from MixedAir.unit.cc):

	// Open the Error Output File (lifted from UtilityRoutines.cc)
	int StandardErrorOutput = GetNewUnitNumber( );
	IOFlags flags;
	flags.ACTION( "write" );
	gio::open( StandardErrorOutput, DataStringGlobals::outputErrFileName, flags );
	int write_stat = flags.ios( );

will open a file called "eplusout.err" with a different unit number than the actual eplusout.err, which has unit number = 1 in the unit tests. This seems to screw up the error message file that remains after the unit tests are run. Eliminating the above code results in a correct error output file with the error messages from all the unit tests.

**Comment by mjwitte** [comment] 2015-03-26 11:55
@wfbuhl Thanks.  I can remove this in my next round of unit test fixes.  @lefticus It would be very helpful if we could access the err and eio output file when there is a unit test failure.  Is that doable?

**Comment by mjwitte** [comment] 2015-03-28 12:53
@lefticus @Myoldmopar Many of the unit tests are opening the eio output file and then closing it and deleting it
	int write_stat;
	// Open the Initialization Output File (lifted from SimulationManager.cc)
	OutputFileInits = GetNewUnitNumber();
	{ IOFlags flags; flags.ACTION( "write" ); flags.STATUS( "UNKNOWN" ); gio::open( OutputFileInits, "eplusout.eio", flags ); write_stat = flags.ios(); }

. . .

	// Close and delete eio output file
	{ IOFlags flags; flags.DISPOSE( "DELETE" ); gio::close( OutputFileInits, flags ); }

Would it be appropriate to open the eio once in EnergyPlus_tests\main.cc so all the test can write to it and the file could be saved for review?

**Comment by mjwitte** [comment] 2015-03-28 13:26
@lefticus @Myoldmopar Same for InitializePsychRoutines(); - could this be done once in EnergyPlus_tests\main.cc ?

**Comment by mjwitte** [comment] 2015-03-28 19:28
Work on this issue also includes 
1.  Add ShowMessage at the beginning of every unit test to help navigate the err output file and know what test generated what error messages.
2.  Add missing eio output file inits to prevent random output file creation with names such as FOR3.DAT, FOR7.DAT etc.
3.  Add missing InitializePsychRoutines in WaterCoils unit test
4.  Add more explicit initializations in HeatBalanceManagerTest, GetWindowConstructData to prevent seemingly random failures due to zero value in NominalRforNominalUCalculation.  This consistently failed on CI linux (release, but not debug) and clang.  Did not fail on Windows CI.  Happened to stumble across a way to reproduce locally in Windows release config, but would not fail every time, sometimes had to run energyplus_tests.exe 3 or 4 times (with all tests passing) before this test would fail.

**Comment by mjwitte** [comment] 2015-03-29 03:54
Finally found a way to reproduce the WaterCoilTest failure locally - by running just that test alone.
Here is the error file:
   ************* Begin Test: WaterCoilsTest, WaterCoolingCoilSizing
   ** Severe  ** For autosizing of Coil:Cooling:Water Test Water Cooling Coil, a system sizing run must be done.
   **   ~~~   ** No "Sizing:System" objects were entered.
   **   ~~~   ** The "SimulationControl" object did not have the field "Do System Sizing Calculation" set to Yes.
   **  Fatal  ** Program terminates due to previously shown condition(s).
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=For autosizing of Coil:Cooling:Water Test Water Cooling Coil, a system sizing run must be done.
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=22hr 35min 49.01sec

Fixed (hopefully) by adding init for SysSizingRunDone=true

**Comment by wfbuhl** [comment] 2015-03-30 01:29
These suggestions seems like a good idea.  As I noted, the .err file is
different than the .eio file in that it opened automatically when the first
error message is invoked. What about closing the files?

Fred

**Closed** 2015-04-02 11:47 UTC

**Comment by wfbuhl** [comment] 2015-04-02 18:23
Good work Mike.
