### ISSUE TITLE
The tabular reports often do not have a title for the first column. (CR #8555)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3329] opened 2014-01-14 01:09 UTC
###### Added on 2011-09-26 10:35 by @lklawrie
--
#### Description
Noticed that the HVAC Sizing Summary (for example) does not show "Zone Name" for the zone sizing or "system name" for the system sizing.

--
Last build tested: `11.09.24 V7.0.0.023`

**Comment by JasonGlazer** [comment] 2016-01-11 15:13
Upon examination, every single tabular report follows the same format and does not have a header (or title) for the first column shown in first row. The upper left box for every table is blank. Given that it is the general format, I am reluctant to make any kind of change. They could be added in each case such as "Utility", "End Use", "Zone", "Month", or sometimes something more generic like "Parameter" or "Description. It seems like the context of the rows is almost always clear so I do not think this is necessary. I am also hesitant to change the format of the tables at this point since GUI's that use the tables might need to be updated.

@mjwitte @kbenne @Myoldmopar If any of you think we should make this change, lets discuss it.

**Comment by JasonGlazer** [comment] 2016-01-11 15:17
@nealkruis @macumber @lgentile I think you were all involved in the old "output schema" discussions so thought you might want to weigh in on this issue.

**Comment by macumber** [comment] 2016-01-11 16:38
This is a change that could potentially break existing queries, other than that I don't have strong feelings.

**Comment by EnergyArchmage** [comment] 2016-01-12 13:25
As I recall the original complaint had to do with how having the first cell in table be blank makes it bit more awkward when reading/parsing the tables into secondary post processing tools.  It trips up automated routines and/or makes queries a bit awkward.  Maybe could repeat the table's subtitle for old tables but make it a policy moving forward to fill out the first column with some useful title.

**Comment by macumber** [comment] 2016-01-12 16:03
@DavidGoldwasser  @asparke2 are the ones most affected by this

**Comment by asparke2** [comment] 2016-01-12 17:05
I haven't had any trouble parsing any of the tables yet, so to me it isn't something that needs fixing.

**Comment by JasonGlazer** [comment] 2016-01-12 18:57
It seems like the known problems of making this change outweigh the unknown possible benefits. Given that I am going to close this issue without making any code changes. It is "As Designed".

**Closed by JasonGlazer** 2016-01-12 18:57 UTC
Labels: EnergyPlus, S2 - Medium, suggestion
