### ISSUE TITLE
Zone Other Equipment Output:Variable produces zero values (for non-zero objects)

### ISSUE THREAD

**Issue by JimDirkes** [NREL/EnergyPlus#9434] opened 2022-05-17 19:56 UTC
Issue overview
--------------
I have defined two Output:Variables in the attached file for the same object. One is defined as Other Equipment Electricity Rate, the other as Zone Other Equipment Electricity Rate. The Zone Other Equipment Electricity Rate produces a bunch of zeroes, the other one gives correct values. Mike Witte thinks recent code revisions may have confused the Output:Variable

The Zone Lights Electricity Rate Output:Variable works well

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): V9.4.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): [GRCCT Proposed Test.idf](https://github.com/NREL/EnergyPlus/files/8711175/GRCCT.Proposed.Test.txt)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment] 2022-05-17 21:06
@JimDirkes I edited your original post to put back the details and checklist from the template (those are actually useful for us!). 

And I'm going to close the issue, because while I can reproduce it on 9.4.0 and 9.5.0, it works fine on 9.6.0 and 22-1-0.

|   Version                |   ('1STFLOOR:EVENTSPACECORE', 'Zone Other Equipment Electricity Rate') |   ('1STFLOOR:EVENTSPACECORE MISCELLANEOUS GAIN', 'Other Equipment Electricity Rate') |
|:------------------|-----------------------------------------------------------------------:|-------------------------------------------------------------------------------------:|
| 9.4.0-998c4b761e  |                                                            0           |                                                                          1.74245e+06 |
| 9.5.0-de239b2e5f  |                                                            0           |                                                                          1.74245e+06 |
| 9.6.0-4b123cf80f  |                                                            5.91344e+10 |                                                                          1.74245e+06 |
| 22.1.0-ed759b17ee |                                                            5.91344e+10 |                                                                          1.74245e+06 |

**Closed as completed by jmarrec** 2022-05-17 21:06 UTC
Labels: UnconfirmedDefect

**Comment by jmarrec** [comment] 2022-05-17 21:11
Attached are all the version from 9.4.0 (the one you supplied) to 22.1.0 I tested
[All_versions.zip](https://github.com/NREL/EnergyPlus/files/8711571/All_versions.zip)
.

**Comment by JimDirkes** [comment] 2022-05-18 10:41
Typical Mssr. Marrec efficiency - fixed before I even mention it :) Thank you!
