### ISSUE TITLE
Invalid time series SQL dat when using Site:GroundDomain:Slab with Finite Difference undisturbed ground temperatures in 8.4

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/EnergyPlus#5314] opened 2015-11-12 15:49 UTC
Model runs without any apparent errors, and tabular SQL data is fine. But time series data is missing. Below is text for the object, and screenshot from ResultsViewer

```
Site:GroundDomain:Slab,
  IngradeCoupledSlab,                     !- Name
  5,                                      !- Ground Domain Depth {m}
  1,                                      !- Aspect Ratio
  5,                                      !- Perimeter Offset {m}
  1.8,                                    !- Soil Thermal Conductivity {W/m-K}
  3200,                                   !- Soil Density {kg/m3}
  836,                                    !- Soil Specific Heat {J/kg-K}
  30,                                     !- Soil Moisture Content Volume Fraction {percent}
  50,                                     !- Soil Moisture Content Volume Fraction at Saturation {percent}
  Site:GroundTemperature:Undisturbed:FiniteDifference, !- Undisturbed Ground Temperature Model Type
  FDTemps,                                !- Undisturbed Ground Temperature Model Name
  1,                                      !- Evapotranspiration Ground Cover Parameter
  GroundCoupledOSCM,                      !- Slab Boundary Condition Model Name
  InGrade,                                !- Slab Location
  SLAB 8 HW CONCRETE,                     !- Slab Material Name
  No,                                     !- Horizontal Insulation
  ,                                       !- Horizontal Insulation Material Name
  ,                                       !- Horizontal Insulation Extents
  ,                                       !- Perimeter Insulation Width {m}
  Yes,                                    !- Vertical Insulation
  VERTICAL SLAB INSULATION,               !- Vertical Insulation Material Name
  1.5,                                    !- Vertical Insulation Depth {m}
  Timestep;                               !- Simulation Timestep
```

![screen shot 2015-11-09 at 10 10 44 am](https://cloud.githubusercontent.com/assets/4857055/11122859/4091f6ca-891a-11e5-84f0-08076e933378.png)

cc: @Myoldmopar

**Comment by Myoldmopar** [comment] 2015-12-08 22:15
Sooooooo, I can't reproduce this.

On my build as of today, I ran the `PipingSystem_Underground_TwoPipe_FD_GroundTemps.idf` file with a debug build.  One thing I did notice is that you _definitely_ need a weather file specified, even if doing design day runs, since this model requires annual weather data to generate ground temps.  But I digress.

The output in sqlite in the ReportData table looks like:

![image](https://cloud.githubusercontent.com/assets/849824/11670283/31528c70-9dbe-11e5-9688-f9644f667946.png)

To verify, here is the eso output file (which becomes the csv in a typical workflow):

![image](https://cloud.githubusercontent.com/assets/849824/11670325/752eb0cc-9dbe-11e5-80f7-43f27dad80e5.png)

Same numbers.  @DavidGoldwasser, I am curious if maybe something went wrong with the simulation because there was a missing weather file?  

Anyway, I'll put a mental timer on this for about a day, and if no one can prove me wrong, I'm closing this.

**Comment by DavidGoldwasser** [comment] 2015-12-09 05:13
@Myoldmopar I thought you were able to reproduce this? (See November 11th email).

Here is a link to the IDF
https://www.dropbox.com/s/p63nsm0721r3moj/in.idf?dl=0

I ran it with USA_ID_Boise.Air.Terminal.726810_TMY3.epw

**Comment by Myoldmopar** [comment] 2015-12-09 14:47
Yeah, I thought I had @DavidGoldwasser.  I found the email, but I'm wondering if I hit the weather file issue and it made me think I had reproduced it.  I'm re-running right now with your idf to see what's up.  But as I showed above, I don't think it _could_ really be anything related to the finite difference ground temp model, since it did report results properly above.  I'll let you know.

**Comment by Myoldmopar** [comment] 2015-12-09 15:12
Welp.  I just ran your idf again, and it works.  The SQLite output is fully populated in the ReportData table:

![image](https://cloud.githubusercontent.com/assets/849824/11688899/7150864a-9e4c-11e5-901b-a3688a28c9dd.png)

The eso output matches:

![image](https://cloud.githubusercontent.com/assets/849824/11688911/88289614-9e4c-11e5-84d3-3a5c489673ee.png)

We can chat about it later, but for now I'm moving on to other bugs.

**Comment by mitchute** [comment] 2015-12-09 15:47
@Myoldmopar I will add the error handling so the weather file issue is handled.

**Comment by DavidGoldwasser** [comment] 2015-12-09 17:06
@Myoldmopar ok, I'm fine with it closing as long as it runs in develop. I was using 8.4 on Linux, and windows. You did try to look at time series sql data vs just tabular?

**Comment by Myoldmopar** [comment] 2015-12-09 17:15
So I don't deal much with the sql data, but as far as I could tell, that _was_ the time series data, not the data that goes out to the tabular results.  Of course it is _in an sql table_ within the sql file, but that's a different story...  

I'll try to remember to let you know when we create a Windows test package of 8.4.0+BugFix so that we can re-test it.

I'll close this for now.......

**Closed as completed by Myoldmopar** 2015-12-09 17:15 UTC
Labels: Defect, SeverityHigh, PriorityLow
