### ISSUE TITLE
LEED Summary Table EAp2-2 shows incorrect total number of hours not met

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#5296] opened 2015-10-30 16:36 UTC
Below are the results from a v8.3.0 baseline and proposed model. In each case the number of hours heating/cooling loads not met match the `System Summary` report `Time Setpoint Not Met` table for occupied heating/cooling. 
#4588 @JasonGlazer

---

EAp2-2. Advisory Messages

Data
Number of hours heating loads not met   1.25
Number of hours cooling loads not met   8.50
Number of hours not met 23.25

---

EAp2-2. Advisory Messages

Data
Number of hours heating loads not met   401.00
Number of hours cooling loads not met   24.25
Number of hours not met 467.75

**Comment by JasonGlazer** [comment] 2015-11-17 16:51
@MatthewSteen What file can I use to reproduce this issue?

**Comment by MatthewSteen** [comment] 2015-11-17 17:27
@JasonGlazer emailed the IDFs to you.

**Comment by JasonGlazer** [comment] 2015-11-18 14:21
@MatthewSteen Now that I am looking at the issue more carefully, I am not sure what you want changed. The numbers match between the two tables but you do not believe that should. Could you explain why they should be different? Is it because one is using the term "loads" and the other "setpoint" or is it the use of the "occupied" columns?

**Comment by MatthewSteen** [comment] 2015-11-18 14:37
@JasonGlazer I could be missing something, but I'm assuming the intent of this table is to have the `Number of hours not met` < 300 per 90.1-2007 and LEED. I'm also assuming that this total should be the sum of the cooling and heating hours listed above it which match the `System Summary > Time Setpoint Not Met` standard report table for the total Facility hours `During Occupied Heating` and `During Occupied Cooling`. For example, this table from the first model above shows:

Time Setpoint Not Met

During Heating [hr] During Cooling [hr] During Occupied Heating [hr]    During Occupied Cooling [hr]
....
Facility    2673.50 3361.75 **1.25  8.50**

**Comment by JasonGlazer** [comment] 2015-11-18 14:48
They do.

**Comment by MatthewSteen** [comment] 2015-11-18 15:00
@JasonGlazer I don't think we're understanding each other, so to be perfectly clear:

1.25 + 8.5 **!=** 23.25

So where does this 23.25 `Number of hours not met` come from?

**Comment by JasonGlazer** [comment] 2015-11-18 15:09
Thanks. That I will look into.

**Comment by Myoldmopar** [comment] 2015-11-25 15:51
Closed via #5327

**Closed as completed by Myoldmopar** 2015-11-25 15:51 UTC
Labels: SeverityHigh, PriorityLow
