### ISSUE TITLE
Documentation Issues - 2017

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5997] opened 2017-02-02 21:41 UTC
- [x] E+ I/O document V8.6 pages 769-770 describes "1.21.8.1.10 Field: Electric Input to Cooling Output Ratio Function of Temperature Curve Name" where at the early part of the paragraph it says "For the type of LeavingCondenserWaterTemperature, the curve object type should be Curve:Bicubic or Table:TwoIndependentVariables that parameterizes the variation of the energy input to cooling output ratio (EIR) as a function of the leaving chilled water temperature and the leaving condenser water temperature. " (yes, I am using leaving condenser water temperature). But near the end of the paragraph it says "The biquadratic curve should be valid for the range of water temperatures anticipated for the simulation (otherwise the program issues warning messages)." (from helpdesk ticket 11860).

The last sentence should read
"The bicubic curve should be valid for the range of water temperatures and part-load ratios anticipated for the simulation (otherwise the program issues warning messages)."

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-02-08 21:20
- [x] I/O Reference, v8.6 p 1110, Table 1.40 "Value of opening factor multiplier for different venting conditions.", table alignment is messed up. Table should be like this (from v8.2 docs):
![image](https://cloud.githubusercontent.com/assets/4991075/22757836/fc7a45c4-ee11-11e6-942f-c59583eed578.png)

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-05-02 15:04
- [x] Reference discussion on [unmethours](https://unmethours.com/question/24056/tracking-energyplus-runtime-progress/?answer=24065#post-id-24065), the section about energyplus.log should be removed.  At least on Windows, that file has not been saved for quite some time now.  Check the full set of docs for other references to a .log output.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-05-24 13:53
- [x] par. 5.3.2 in the Engineering Reference, after equation 5.23 where it says
"Rhorizon and Rdome are calculated once for each surface since they are independent of sun position."

This is out of date, and should read:
If the Sky Diffuse Modeling Algorithm (ShadowCalculation object) is set to SimpleSkyDiffuseModeling, then Rhorizon and Rdome are calculated once for each surface since they are independent of sun position. If the Sky Diffuse Modeling Algorithm is set to DetailedSkyDiffuseModeling, then Rhorizon and Rdome are calculated every timestep for each surface."

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-05-24 14:17
- [x] Engineering Ref (v8.7.0) pdf p. 1086, text is running off the bottom of the page.  Not sure how much is missing before the next page starts.

- This issue does not exist in V8.9 pdf (see pages 1047-1048) no need to address.

**Comment by JasonGlazer** [comment] 2017-06-06 18:13
- [x] Output:IlluminanceMap should indicate that it is only valid when used with SplitFlux daylighting method.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-06-07 20:00
- [x] p. 97 of the Engineering Reference the equation numbers are missing in the description of the DOE-2 convection algorithm
"hn is calculated using Equation or Equation ." (helpdesk ticket 12090)
Based on the v8.2 engineering rerefence, the equation numbers here should be references to the current equations 3.74 and 3.75.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by aaron-boranian** [comment] 2017-06-07 20:20
- [x] In both the Input-Output Reference and Engineering Reference documentation for the AirConditioner:VariableRefrigerantFlow object, discussion of the condenser entering node conditions only refers to outdoor air dry-bulb temperature. This may confuse users who want to model water- or evaporatively-cooled VRF systems.

 - Input-Output Reference for [Cooling Capacity Ratio Modifier Function of Low Temperature Curve Name](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-cooling-capacity-ratio-modifier-function-of-low-temperature-curve-name) input field of [AirConditioner:VariableRefrigerantFlow](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-variable-refrigerant-flow-equipment.html#airconditionervariablerefrigerantflow) object.
 - Engineering Reference for [Cooling Capacity Ratio Modifier Function of Low Temperature Curve Name](http://bigladdersoftware.com/epx/docs/8-7/engineering-reference/variable-refrigerant-flow-heat-pumps.html#cooling-capacity-ratio-modifier-function-of-low-temperature) input field of [AirConditioner:VariableRefrigerantFlow](http://bigladdersoftware.com/epx/docs/8-7/engineering-reference/variable-refrigerant-flow-heat-pumps.html#variable-refrigerant-flow-heat-pump-model-system-curve-based-model) object.
 - [Related UnmetHours question](https://unmethours.com/question/24875/water-source-vrf-system-curve/?answer=24876#post-id-24876)

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-06-09 16:49
- [x] In the I/O Ref, ZoneHVAC:IdealLoadsAirSystem outputs, the Ideal Loads Output Variable Overview should include the caveats that the outdoor air load is only calculated when there is active heating or cooling (or humidification/dehumidification).  This is stated later on in the individual output descriptions, but it should be stated here as well, probably several places here, including before the equation. (helpdesk ticket 12105)

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-06-13 20:27
- [ ] I/O Ref section for HybridModel:Zone is not in the pdf.  The source files were added in #5882 but there's no line in overview.tex to input the new file into the document?

- This object/model was first introduced in V8.7 

Posted new issue [#6947](https://github.com/NREL/EnergyPlus/issues/6947) for this.

**Comment by mjwitte** [comment] 2017-06-13 20:38
- [x] Typo in Engineering Reference section for Ground Heat Transfer Calculations using Site:GroundDomain:Slab, subsection heading "Boudary Conditions".

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by aaron-boranian** [comment] 2017-06-20 19:50
- [x]  Typo in EMS Application Guide for [Hydronic Low Temp Radiant Design Water Mass Flow Rate for **Cooling**](http://bigladdersoftware.com/epx/docs/8-7/ems-application-guide/hvac-systems.html#hydronic-low-temp-radiant-design-water-mass-flow-rate-for-cooling) internal variable: 'The internal variable called “Hydronic Low Temp Radiant Design Water Mass Flow Rate for **Heating**” provides ... '

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-07-03 12:26
- [x] In the Auxiliary Programs document, the example def files for the Weather Converter show backslashes and underscores in many places.  These should not be in the final pdf.

The underscore appears everywhere in the documentation where "\begin{lstlisting} ... \end{lstlisting}" is used as designed. It is OK as is.

**Comment by aaron-boranian** [comment] 2017-07-04 18:04
- [x] In both the Input-Output Reference and Engineering Reference documentation for the SetpointManager:OutdoorAirReset object, discussion of the supply temperature being controlled is only for air systems. However, there are example files that use this object to reset plant systems as well (5ZoneBoilerOutsideAirReset.idf, 5ZoneWaterSystems.idf). This option to reset plant systems using the outdoor air reset SPM object should be part of the documentation. 

 - Input-Output Reference for [SetpointManager:OutdoorAirReset](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-setpoint-managers.html#setpointmanageroutdoorairreset) object.
 - Engineering Reference for [SetpointManager:OutdoorAirReset](http://bigladdersoftware.com/epx/docs/8-7/engineering-reference/setpoint-managers.html#outdoor-air-reset) object.

- I/O Ref document is already updated (addressed missing OutdoorAir Restet SPM use in plant loops in Eng. Ref. document)

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by aaron-boranian** [comment] 2017-07-04 18:07
- [x] IDF example in Input-Output Reference section for the [Exterior:WaterEquipment](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-exterior-energy-use-equipment.html#exteriorwaterequipment) object isn't displaying as code blocks like other IDF examples. 

- [x] Description of last output variable "Exterior Equipment Mains Water Volume" in Input-Output Reference section for the [Exterior:WaterEquipment](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-exterior-energy-use-equipment.html#exteriorwaterequipment) object isn't displaying correctly (looks like there is no space between variable unit and description). 

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by aaron-boranian** [comment] 2017-07-06 15:26
- [x] Typo in Table 2.3: Operators for Erl: "*" multiplication symbol doesn't appear in **Operator Symbol** column at left of table (see below). Maybe it's being interpreted as a bad symbol (missing a \ to escape)? 

![screen shot 2017-07-06 at 9 25 03 am](https://user-images.githubusercontent.com/15160917/27918726-0c8ec6d0-622d-11e7-953f-bf6fa7172088.png)

- [x] Typo in code block for compound expressions following Table 2.3: using "\*" for multiplication symbol (see below). Should remove \ since don't need to escape characters in code block.

![screen shot 2017-07-06 at 9 23 46 am](https://user-images.githubusercontent.com/15160917/27918668-e45ad104-622c-11e7-8d19-6a86c8601e3a.png)

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by MatthewSteen** [comment] 2017-07-10 18:20
- [x] Typo in IO Ref for [ZoneHVACFourPipeFanCoil](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-zone-forced-air-units.html#zonehvacfourpipefancoil) 2nd paragraph, 1st sentence looks like it should read...

> The heating or cooling output of the ~~unit ventilator~~ **fan coil unit** is controlled by varying the air flow rate, the water flow rate, or both. Air flow rate can be controlled by cycling the fan on/off or with a variable speed fan drive. [(source code)](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-zone-forced-air-units.tex#L487)

---

https://github.com/NREL/EnergyPlus/issues/5997#ref-commit-7724958



  Included Matthew's fix here [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946).

**Comment by aaron-boranian** [comment] 2017-07-11 16:18
- [x] There are multiple differences between what the EMS Application Guide claims that actuators contain as control types and what the EDD file shows as available actuator info. EMS Application Guide should be consistent with EDD file.
  - Update "[Mass Flow Rate Minimum Setpoint](http://bigladdersoftware.com/epx/docs/8-7/ems-application-guide/hvac-systems-001.html#system-node-setpoints)" to "Mass Flow Rate Minimum **Available** Setpoint"
  - Update "[Mass Flow Rate Maximum Setpoint](http://bigladdersoftware.com/epx/docs/8-7/ems-application-guide/hvac-systems-001.html#system-node-setpoints)" to "Mass Flow Rate Maximum **Available** Setpoint"
  - Add "Pump Pressure Rise" (missing from documentation)

This is not an exhaustive list.
Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by aaron-boranian** [comment] 2017-07-19 22:17
- [x] The "Zone Component Load Summary" output table report contains information for individual heat transfer components contributing to design day sizing calculations for heating and cooling. However, there aren't definitions or equations in the [Input/Output Reference](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/output-table-summaryreports.html#zone-component-load-summary) or [Engineering Reference](http://bigladdersoftware.com/epx/docs/8-7/engineering-reference/zone-component-loads-summary.html#zone-component-loads-summary) to help users know what the components represent or how the components are calculated. This should be included since users can get confused about what different heat gain components represent (infiltration vs zone ventilation, e.g.). Users should also be able to see how it's calculated for their own output processing purposes.

Posted new issue [here](https://github.com/NREL/EnergyPlus/issues/6956).

**Comment by JasonGlazer** [comment] 2017-07-20 14:29
@aaron-boranian the Engineering Reference includes a section on the Zone Component Loads Summary report already [here](http://bigladdersoftware.com/epx/docs/8-7/engineering-reference/zone-component-loads-summary.html#zone-component-loads-summary). What further clarification is needed in that section?

**Comment by aaron-boranian** [comment] 2017-07-20 15:33
@JasonGlazer that section essentially just lists all the load components, but doesn't define them. For example, new users or energy modelers may not be familiar with the difference between infiltration, ventilation, and zone mixing load components. It would be nice to include equations that explicitly show how each load component is calculated.

**Comment by JasonGlazer** [comment] 2017-07-31 13:55
- [x] Remove references to FORTRAN in the Engineering Reference

**Comment by JasonGlazer** [comment] 2017-08-16 16:06
- [x] In the IORef, for Refrigeration:Compressor, the following fields are not documented
- Mode of Operation
- Transcritical Compressor Power Curve Name
- Transcritical Compressor Capacity Curve Name

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-09-29 16:35
- [x] From helpdesk ticket 12319, I/O Ref, WaterUse:Equipment, incorrectly references inlet/outlet nodes. This should say if the WaterUse:Equipment is included in a WaterUse:Connections object, blah blah blah.

> "1.53.1.2.17 Water Use Equipment Heating Energy [J]
The heating energy accumulated by the heating rate above, in units of Joules (J). This output
is also added to a meter with End Use Key = WaterSystems, Group Key = Plant. If both of the
node names specified in the WaterUse:Equipment object are blank, then this output is reported
with Resource Type = DistrictHeating. If either of the node names are entered, then this output
is reported with Resource Type = EnergyTransfer. The sub-categories may be entered as any
type (e.g., Laundry, Dish Washing, etc. defined in WaterUse:Equipment object input for End-Use
Subcategory) with General being the default sub-category (ref. Output Meter)"

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by JasonGlazer** [comment] 2017-10-13 12:55
- [x] In the AuxiliaryPrograms.pdf documentation, the section on HVAC Diagram is 7.8, which is a continuation of the section on Input Macros (EP-Macro). It should really be its own chapter just like all the other utility programs. It should probably be Chapter 8 and the rest of the chapters renumbered.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by mjwitte** [comment] 2017-10-13 20:48
- [x] Documentation should be clarified regarding the ecoroof model.  Both the I/O Ref and Engineering Ref mention using the eco model with conduction finite difference is "under development".  But that isn't true.  Running econroof with CondFD produces this warning:
   ** Warning ** CalcEcoRoof: EcoRoof simulation but HeatBalanceAlgorithm is not ConductionTransferFunction(CTF). Has not been tested under other solution approaches.
Maybe that should be changed to a severe/fatal?
Helpdesk ticket 12333.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by MatthewSteen** [comment] 2017-10-26 16:19
- [x] Typo in the [Life-Cycle Cost Computations](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/economics-calculations/life-cycle-cost-computations.tex#L34) section of the ER.

> Step 4. Put the nonrecurring, nonrecurring, and utility costs into a monthly array for the entire length of the study period.

should be:

> Step 4. Put the nonrecurring, **recurring**, and utility costs into a monthly array for the entire length of the study period.

---

https://github.com/NREL/EnergyPlus/issues/5997#ref-commit-7724958
  Included Matthew's fix here [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946).

**Comment by JasonGlazer** [comment] 2017-11-28 12:28
- [x] The CurrencyType object is not shown in the table of contents and is just shown as a subsection to the LifeCycleCost:UseAdjustment object. It should be promoted to show in the table of contents to make it easier for people to find.

- [x] The link to the iso.org page in the CurrencyType documentation is broken and should be replaced.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by JasonGlazer** [comment] 2017-12-29 16:17
- [x] the "Web Resources" section of the Weather Converter Program in Auxiliary Programs should have updated links.

Addressed in Pull Request [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946)

**Comment by MatthewSteen** [comment] 2018-01-03 03:36
**Pump:VariableSpeed IO documentation**

- [x] [Field: Design Pump Head](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-pumps.tex#L27)

> This numeric field contains the pump's ~rated~ **design** head pressure in Pascals. The default is 179352 Pa, or 60 ftH20, and is for a fairly large building.

- [x]  [Field: Motor Efficiency](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-pumps.tex#L35)

> This numeric field contains the pump ~'s~ **motor's** efficiency in decimal form (0 = 0\%, 1 = 100\%).

**Pump:ConstantSpeed IO documentation**

- [x] [Field: Design Power Consumption](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-pumps.tex#L260)

> This numeric field contains the pump’s ~rated~ **design** power consumption in Watts. If the user is performing a pressure simulation on the loop in which this pump is found, this value would only be used to estimate pump efficiency. During reported calculations, the pump would use the loop pressure drop and current flow conditions along with efficiency to calculate pump power dynamically. This field can be autosized. When set to autosize the type of scaling factor is chosen in the input field Design Power Sizing Method.

- [x]  [Field: Motor Efficiency](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-pumps.tex#L264)

> This numeric field contains the pump ~'s~ **motor's** efficiency in decimal form (0 = 0\%, 1 = 100\%).
 
---

https://github.com/NREL/EnergyPlus/issues/5997#ref-commit-7724958
  Included Matthew's fix here [160251551_Issue#5997](https://github.com/NREL/EnergyPlus/pull/6946).

**Comment by Nigusse** [comment] 2018-09-07 15:38
@mjwitte @Myoldmopar All but two issues listed in this documentation are addressed. Two of the issues should be addressed separately (each) and posted two new issues [here](https://github.com/NREL/EnergyPlus/issues/6947) and [here](https://github.com/NREL/EnergyPlus/issues/6956).

**Comment by Nigusse** [comment] 2018-09-07 16:02
@JasonGlazer I think the "Zone Component Load Summary" issue listed above warrants a separate issue by itself. What do you think?

**Comment by JasonGlazer** [comment] 2018-09-12 16:08
@Nigusse Sure, although I still believe that the section in the engineering reference that describes the Zone Component Loads Summary is sufficient for understanding how it works.

**Comment by Nigusse** [comment] 2018-09-12 17:20
@JasonGlazer @mjwitte @Myoldmopar I will post a separate issue for "Zone Component Load Summary" calculation definitions or equations request as a place holder for next release consideration.

**Comment by Nigusse** [comment] 2018-09-12 17:51
@mjwitte @Myoldmopar The only issue remaining now is 
"- [ ] In the Auxiliary Programs document, the example def files for the Weather Converter show backslashes and underscores in many places.  These should not be in the final pdf."

The underscore appears everywhere in the documentation where "\begin{lstlisting} ... \end{lstlisting}" listing template is used. I think this is a a standard template in LaTex mainly used to add code snippet to a documentation as described [here](https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings). I don't know enough if we can customize it to remove the underscore.

**Comment by mjwitte** [comment] 2018-09-12 18:04
@Nigusse I'm confused. I don't see any problems in the current Auxiliary Programs doc def file listings. Even going back several releases. I don't know what prompted me to post [this comment](https://github.com/NREL/EnergyPlus/issues/5997#issuecomment-312632248).

**Comment by Nigusse** [comment] 2018-09-12 18:58
@mjwitte Ok. Thanks. I will mark it as designed.

**Comment by Myoldmopar** [comment] 2018-09-19 20:01
Closed by #6946

**Closed as completed by Myoldmopar** 2018-09-19 20:01 UTC
Labels: Documentation
