### ISSUE TITLE
HeatExchanger:AirToAir:SensibleAndLatent Supply Air Outlet Temperature Control problems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4794] opened 2015-03-12 16:56 UTC
User file has three similar VAV systems plus other with heat recovery using HeatExchanger:AirToAir:SensibleAndLatent.  Supply Air Outlet Temperature Control is set to Yes for all of the HX, but only the first one seems to be honoring that.  The others are over-recovering sending warm air into the system causing the cooling coil to operate at a high load.  Even the first HX is not controlling well and the cooling coil is coming on at a small load, but that's a separate (maybe) issue.

**Comment by mjwitte** [comment] 2015-03-12 17:17
Further review reveals that the heat recovery outlet setpoint is being set using a SetpointManager:OutdoorAirPretreat.  At certain times, the requested setpoint (e.g. 3.4C) is colder than the outdoor air temperature (3.5C) which apparently makes the HX not honor the setpoint - don't know if it thinks it is in cooling mode or if there is just some misstated conditions.  It seems at this point the economizer should be kicking in and locking out the hx anyway.  See VAV_POD_3 HEAT RECOVERY OUTLET NODE:System Node Temperature [C](Each Call)  at time stamp  01/23  15:20:00
 for an exmple.

**Comment by rraustad** [comment] 2015-03-23 00:59
I don't see the schedule file in the defect folder. Should I just convert to a constant?

SCHEDULE:FILE,            
    Bath_ZN_1_FLR_1_SchFile,    !- Name
    ,                         !- Schedule Type Limits Name
    SchoolPrimary-Chicago-0001-UTIL-DA05_DyLtFix_pre-liteSch.csv,    !- File Name

**Comment by mjwitte** [comment] 2015-03-24 15:24
@rraustad Schedule file is there now.

**Comment by rraustad** [comment] 2015-03-25 03:27
Took a while to look through the first system. Hard to say if it's working correctly since the OA flow is 0 most of the time. DifferentialDryBulb control with 0 minimum OA flow rate. Then there's the use of BypassWhenOAFlowGreaterThanMinimum.

Controller:OutdoorAir,    
    VAV_POD_1_OA_Controller,    !- Name
    VAV_POD_1_OARelief Node,    !- Relief Air Outlet Node Name
    VAV_POD_1 Supply Equipment Inlet Node,    !- Return Air Node Name
    VAV_POD_1_OA-VAV_POD_1_CoolCNode,    !- Mixed Air Node Name
    VAV_POD_1_OAInlet Node,    !- Actuator Node Name
    0.0,                      !- Minimum Outdoor Air Flow Rate
    AUTOSIZE,                 !- Maximum Outdoor Air Flow Rate
    DifferentialDryBulb,      !- Economizer Control Type
    ModulateFlow,             !- Economizer Control Action Type
    ,                         !- Economizer Maximum Limit Dry Bulb Temperature
    ,                         !- Economizer Maximum Limit Enthalpy
    ,                         !- Economizer Maximum Limit Dewpoint Temperature
    ,                         !- Electronic Enthalpy Limit Curve Name
    ,                         !- Economizer Minimum Limit Dry Bulb Temperature
    NoLockout,                !- Lockout Type
    FixedMinimum,             !- Minimum Limit Type
    qqAlways_0,               !- Minimum Outdoor Air Schedule Name
    ,                         !- Minimum Fraction of Outdoor Air Schedule Name
    ,                         !- Maximum Fraction of Outdoor Air Schedule Name
    mechVent_VAV_POD_1_OA_Controller,    !- Mechanical Ventilation Controller Name
    ,                         !- Time of Day Economizer Control Schedule Name
    ,                         !- High Humidity Control
    ,                         !- Humidistat Control Zone Name
    ,                         !- High Humidity Outdoor Air Flow Ratio
    ,                         !- Control High Indoor Humidity Based on Outdoor Humidity Ratio
    BypassWhenOAFlowGreaterThanMinimum;    !- Heat Recovery Bypass Control Type

![4794_sys1](https://cloud.githubusercontent.com/assets/5778156/6817886/5dff6070-d27d-11e4-912f-fe9bb667e8ce.jpg)

**Comment by rraustad** [comment] 2015-03-27 02:19
This does not look as bad as first thought. The air loop is operating according to the availability schedule.
![4794_availsch](https://cloud.githubusercontent.com/assets/5778156/6860888/97e10130-d404-11e4-95c9-dad7f3b88717.jpg)

The HX is operating only during times when economizer is not active, as designed. When in cooling mode, the HX is full on and does not attempt to control to the active set point temperature. Note the 3 times in this graph that the HX flow rate is low (right side of graph) where HX outlet temp  (grey) approaches secondary inlet temp (green). So this defect file is working as intended, however, during times when the HX inlet temp is > than the set point temp, the control set point temp is not maintained (nor attempted to be maintained).

if ( ExchCond( ExNum ).ControlToTemperatureSetPoint && ExchCond( ExNum ).SupInTemp < HXTempSetPoint ) {

Suggestion is to add bidirectional control when using temperature control.

![4794_zoom_coolingmode](https://cloud.githubusercontent.com/assets/5778156/6860909/f1ddbcf0-d404-11e4-8e41-8c1114d13d83.jpg)

**Comment by mjwitte** [comment] 2015-03-27 14:58
@rraustad Thanks for the detailed look at this.  The question of what "heating" mode means is still ambiguous.  One could argue that anytime SecInTemp > SupIntemp then we are in heating mode and the setpoint control should be active.  That's what I expected the control to do.  Regarding the zero min OA schedule, that's necessary to allow the DCV to do it's thing.  Changing the bypass control to "BypassWhenWithinEconomizerLimits" results in the heat exchanger bypassing all winter unless an Outdoor Drybulb Min Limit is specified.  But the value for that is difficult to choose - don't want to miss out on free cooling when needed, thus selecting BypassWhenOAFlowGreaterThanMinimum and letting the economizer decide seems like the correct strategy.

**Comment by rraustad** [comment] 2015-03-27 15:14
I would expect that IF SupInTemp < HXTempSetPoint, then SecInTemp would have to be greater than SupInTemp to provide any heating. I would have to verify that is working correctly. I was mulling over allowing this control to apply to cooling mode as well. I haven't come up with a good reason not to allow that. So basically:

if ( ExchCond( ExNum ).ControlToTemperatureSetPoint ) {
then try to meet the set point whether in heating or cooling mode
}

**Comment by mjwitte** [comment] 2015-03-27 15:28
@rraustad "I would expect that IF SupInTemp < HXTempSetPoint, then SecInTemp would have to be greater than SupInTemp to provide any heating. "  But if SupInTemp>HXTempSetPoint and SecInTemp>SupInTemp we want the HX to stay off.  This is not happening currently.

Regarding the suggestion to control in both directions, that should be a second option.  But longer term we need to find a way to simplify all of these interacting controls.  It's difficult to get the OA controller, HX, and setpoint controls at the mixed air node to all coordinate in a way that makes sense.

**Comment by rraustad** [comment] 2015-03-27 15:38
"But if SupInTemp>HXTempSetPoint and SecInTemp>SupInTemp we want the HX to stay off. This is not happening currently"

You lost me. Why would we turn off the HX during the cooling season simply because a user tried to minimize heating energy during the heating season (i.e., used SP control)? Maybe your thinking of this more broadly than I am but HX's are hard enough to justify economically without throwing away potential recovered energy.

**Comment by mjwitte** [comment] 2015-03-27 16:09
This is not cooling season.  It's January.  It's heating season, but the interior zone wants some cooling.  It's cold outside, but the ODB happens to be a little warmer than the setpoint required to meet the mixed air setpoint (this setpoint may be a separate issue).  What happens currently is the HX comes on 100% and then the DX coil comes on to get rid of everything the HX did.

Looking at 01/23 15:20
VAV_POD_3_OA-VAV_POD_3_CoolCNode (mixed air node) setpoint temp = 14.6275
ODB = 3.5
VAV_Pod_3 Heat Recovery Outlet Node (HX sup outlet) setpoint temp = 3.3752
VAV_Pod_3_OARelief Node (HX secondary inlet node) temp = 23.9

Seems the economizer should have opened up rather than setpointmanager:outdoorairpretreat asking for air that is colder than ODB.  But either way, if this set of conditions occur, it seems the HX should stay off rather than overheat.

**Comment by mjwitte** [comment] 2015-03-27 18:40
@rraustad  Still looking at 01/23 15:20, it seems the HX should have been bypassing

VAV_POD_3:Air System Outdoor Air Economizer Status [](Each Call) = 1
VAV_POD_3:Air System Outdoor Air Heat Recovery Bypass Status [](Each Call) = 0
VAV_POD_3:Air System Outdoor Air Flow Fraction [](Each Call) = 0.441047543
VAV_POD_3:Air System Outdoor Air Minimum Flow Fraction [](Each Call) = 0.405427698

So, OA Frac > Min OA Frac, so why isnt the HX bypass active?

**Comment by rraustad** [comment] 2015-03-27 20:36
I intend to investigate tonight.

**Comment by rraustad** [comment] 2015-03-28 19:26
Controller:OutdoorAir,    
    VAV_POD_3_OA_Controller,    !- Name
    NoLockout,                !- Lockout Type

**Comment by rraustad** [comment] 2015-03-28 19:45
No, not the OA controller, the HX has a lockout input field which is not included in the input file. The default is Yes, so I'll check to see if it's actually set as Yes when the input field is missing.

HeatExchanger:AirToAir:SensibleAndLatent,
  A10;\field Economizer Lockout
      \type choice
      \key Yes
      \key No
      \default Yes
      \note Yes means that the heat exchanger will be locked out (off)
      \note when the economizer is operating or high humidity control is active

**Comment by rraustad** [comment] 2015-03-28 19:49
Yes, HX lockout gets set to Yes if the field is missing.

**Comment by rraustad** [comment] 2015-03-28 19:58
It's working correctly, rotary HX's don't bypass, they modulate wheel speed. The HX cooling/heating rate variables or the HX effectiveness variables should show inactive operation.

HeatExchanger:AirToAir:SensibleAndLatent,
    VAV_Pod_3 OA Heat Recovery,    !- Name
    Yes,                      !- Supply Air Outlet Temperature Control
    Rotary,                   !- Heat Exchanger Type

**Comment by rraustad** [comment] 2015-03-28 21:35
To clarify:
VAV_POD_3:Air System Outdoor Air Economizer Status = 1
VAV_POD_3:Air System Outdoor Air Heat Recovery Bypass Status = 0
VAV_POD_3:Air System Outdoor Air Flow Fraction = 0.441047543
VAV_POD_3:Air System Outdoor Air Minimum Flow Fraction = 0.405427698

The bypass status will not equal economizer status when economizer turns on the air loop heating coil. If the air loop heating coil turns on when economizer is active, the HX will turn on to minimize heating energy.

**Comment by mjwitte** [comment] 2015-03-29 00:25
@rraustad OK, so the silly heating coil was running at 1W or less.  Added a second defect file that lowers the heating coil setpoint 0.1C below the cooling coil setpoint to get rid of this kind of noise.  So, now the heating coil shows zero output, but the HX is still running.  What do I look for next?  Earlier that same day the bypass flag = 1 and the HX is off.  Then at 11:36:40 is flips for some reason.

**Comment by mjwitte** [comment] 2015-03-29 00:31
@rraustad Interesting to note that the heating coil does operate for two time steps starting at 11:36:40 then is off the rest of the day.  Wondering if the HeatingActiveFlag is not getting reset?  After the system is off overnight, then the bypass flag works as expected again.

**Comment by rraustad** [comment] 2015-03-30 02:09
PR #4833

**Comment by rraustad** [comment] 2015-03-30 13:43
All these get reset at the top of SimHVAC()

if ( AirLoopInputsFilled ) {
	// Reset air loop control info for cooling coil active flag (used in TU's for reheat air flow control)
	AirLoopControlInfo.CoolingActiveFlag() = false;
	// Reset air loop control info for heating coil active flag (used in OA controller for HX control)
	AirLoopControlInfo.HeatingActiveFlag() = false;
	// reset outside air system HX to off first time through
	AirLoopControlInfo.HeatRecoveryBypass() = true;
	// set HX check status flag to check for custom control in MixedAir.cc
	AirLoopControlInfo.CheckHeatRecoveryBypassStatus() = true;
	// set OA comp simulated flag to false
	AirLoopControlInfo.OASysComponentsSimulated() = false;
	// set economizer flow locked flag to false, will reset if custom HX control is used
	AirLoopControlInfo.EconomizerFlowLocked() = false;
	// set air loop resim flags for when heat recovery is used and air loop needs another iteration
	AirLoopControlInfo.HeatRecoveryResimFlag() = true;
	AirLoopControlInfo.HeatRecoveryResimFlag2() = false;
	AirLoopControlInfo.ResimAirLoopFlag() = false;
}

**Comment by mjwitte** [comment] 2015-04-22 02:36
@rraustad Code has been merged, but I'm leaving the issue open pending some doc updates to clarify how the revised setpoint control works.

**Comment by rraustad** [comment] 2015-04-22 11:52
@Myoldmopar which documents are we to change now? The EngRef.doc file has not been updated, so I assume there are (markup?) docs elsewhere.

**Comment by rraustad** [comment] 2015-05-07 16:51
@mjwitte #4873 addressed documentation. Closing issue.

**Closed by rraustad** 2015-05-07 16:51 UTC
Labels: EnergyPlus, Priority, S2 - Medium
