### ISSUE TITLE
ReadVarsEso launched from energyplus commandline does not work for folders with spaces in path

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#7310] opened 2019-05-24 17:38 UTC
Issue overview
--------------
When rvi/mvi file path has blank spaces (e.g. c:\Desktop\New folder\in.idf), ReadVarsEso executed with -r switch in Energyplus.exe commandline does not work.

```
std::string const readVarsRviCommand = "\"" + readVarsPath + "\"" + " " + RVIfile + " unlimited";
std::string const readVarsMviCommand = "\"" + readVarsPath + "\"" + " " + MVIfile + " unlimited";

systemCall(readVarsRviCommand);
systemCall(readVarsMviCommand);
```
It seems that RVIfile should also be quoted though I am not sure if this additional problem will arise if doing so:
[https://stackoverflow.com/questions/9964865/c-system-not-working-when-there-are-spaces-in-two-different-parameters](https://stackoverflow.com/questions/9964865/c-system-not-working-when-there-are-spaces-in-two-different-parameters)

**Comment by jmarrec** [comment] 2019-05-28 09:20
@ecoeficiente I am unable to reproduce the problem on Windows 10 using Energyplus 9.1.0. Are you running this from outside the "New folder" directory? Or is it the rvi/idf file itself that has spaces and not the folder?

```
C:\Users\julien>cd "C:\Users\julien\Software\Others\EnergyPlusDevSupport\DefectFiles\7000s\7310\A folder with spaces"

C:\Users\julien\Software\Others\EnergyPlusDevSupport\DefectFiles\7000s\7310\A folder with spaces> dir

 Directory of C:\Users\julien\Software\Others\EnergyPlusDevSupport\DefectFiles\7000s\7310\A folder with spaces

05/28/2019  11:11 AM            19,513 1ZoneUncontrolled.idf
05/28/2019  11:11 AM               272 1ZoneUncontrolled.rvi
05/28/2019  11:12 AM         1,648,753 chig.epw

C:\Users\julien\Software\Others\EnergyPlusDevSupport\DefectFiles\7000s\7310\A folder with spaces>C:\EnergyPlusV9-1-0\energyplus.exe -r -d out -w chig.epw 1ZoneUncontrolled.idf
[...]
 ReadVarsESO program starting.
 ReadVars Run Time=00hr 00min  0.89sec
 ReadVarsESO program completed successfully.
 ReadVarsESO program starting.
 ReadVars Run Time=00hr 00min  0.44sec
 ReadVarsESO program completed successfully.

C:\Users\julien\Software\Others\EnergyPlusDevSupport\DefectFiles\7000s\7310\A folder with spaces>ls out
eplusmtr.csv    eplusout.csv  eplusout.end  eplusout.mdd  eplusout.rdd      eplustbl.csv  eplustbl.txt
eplusout.audit  eplusout.dxf  eplusout.err  eplusout.mtd  eplusout.rvaudit  eplustbl.htm  eplustbl.xml
eplusout.bnd    eplusout.eio  eplusout.eso  eplusout.mtr  eplusout.shd      eplustbl.tab  sqlite.err
```

**Comment by ecoeficiente** [comment] 2019-05-28 09:35
Hi @jmarrec, you have given me the solution with your question. I was running it from inside the folder but using the full path, when it is not necessary. Well, actually I was running it from a .Net Process class setting for the Working Directory the folder of the idf file but using the full path in the arguments. I have confirmed that setting the Working Directory as that, you can use only the filename in the arguments and it runs fine.

The problem was using the full path of the file, which had spaces.

**Comment by jmarrec** [comment] 2019-05-28 09:58
Ok thank you for the feedback, and happy that you have already a workable workaround. It should still run fine with the full path specified, so I will investigate a fix for this.

**Comment by jmarrec** [comment] 2019-05-28 10:03
I can reproduce the error now.

```
C:\Users\julien\Software\Others\EnergyPlusDevSupport\DefectFiles\7000s\7310>C:\EnergyPlusV9-1-0\energyplus.exe -r -d "A folder with spaces/out" -w C:\EnergyPlusV9-1-0\WeatherData\USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw "A folder with spaces\1ZoneUncontrolled.idf"

 ReadVarsESO program starting.
 Requested Report Variable input file=A
 does not exist.  Check eplusout.err file for possible explanations.
 ReadVarsESO program terminated.
 ReadVarsESO program starting.
 Requested Report Variable input file=A
 does not exist.  Check eplusout.err file for possible explanations.
 ReadVarsESO program terminated.
```

**Closed as completed** 2019-06-05 15:23 UTC
