### ISSUE TITLE
HeatExchanger:FluidToFluid with CoolingDifferentialOnOff gets stuck in off mode

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4959] opened 2015-06-03 20:57 UTC
Helpdesk ticket 10505
User file with fluid coolers and waterside economizer using HeatExchanger:FluidToFluid with CoolingDifferentialOnOff operates as expected Jan 1 thru Mar 2, then is off most of the time, coming on briefly on Apr 23, May 23, and July 19, but then is off the remainder of the year, even though it should start operating again in November-December.

If the run periods are broken up into, say Jan, Apr, Jul, and December, then the HX is operating in December.
Run with Vienna AUT weather.

**Comment by EnergyArchmage** [comment] 2015-11-27 21:00
The problem is that once the loop on the demand side warms up to the point where the HX control turns off (as it should because deltaT drops below tolerance), that loop never gets a chance to run again to see what the fluid coolers might be able to do were they to run.  These are often connected to the same condenser loop that the chillers use so there is flow requested by other components but in the defect file the HX is the only device on the loop to demand any flow.  No flow, no fluid cooler operation and no updated loop temperature values so it gets stuck.  

There needs to be a trial to see what temperature the HX demand side inlet might achieve.  This is the sort of fundamental problem that FirstHVACIteration is used to deal with.  Added FirstHVACIteration argument to simulation call and carried into control routine and used in logic to request demand side flow and that seems to solve the problem.  
Problem is not just for CoolingDifferentialOnOff; other control methods would have the same problem so added the logic to nearly all the controls that need to consider the demand side inlet temperature to see if HX can function.  Trial fix in branch called 4959-plant-HX-CoolDifferential-stuck-Off

**Comment by nilexan** [comment] 2016-02-22 13:12
What is the current situation?

**Comment by EnergyArchmage** [comment] 2016-02-22 14:14
A fix was drafted out in this branch, https://github.com/NREL/EnergyPlus/tree/4959-plant-HX-CoolDifferential-stuck-Off      Unfortunately I cannot think of way to devise a unit test.

**Comment by nilexan** [comment] 2016-02-22 14:49
Ok, thanks for your answer. What does that mean exactly? What happens now and when do you think will the fix available?

**Comment by EnergyArchmage** [comment] 2016-02-26 19:01
Unit test completed and pull request is ready for this.  
https://github.com/NREL/EnergyPlus/pull/5511

**Comment by Myoldmopar** [comment] 2016-03-03 21:08
Closed via #5511

**Closed as completed by Myoldmopar** 2016-03-03 21:08 UTC
Labels: SeverityMedium, PriorityLow
