### ISSUE TITLE
Alpha9_2 memory consumption

### ISSUE THREAD

**Issue by tijcolem** [NREL/EnergyPlus#7516] opened 2019-09-20 17:22 UTC
This could be an issue related to Alpha9_2 release and it's ready being addressed but 
@jmarrec discovered a process consuming excessive memory that you may want to take a look at. Here is comments by Julien. 

 I don't know what's going on, suddenly airterminal_fourpipebeam_osm (and _rb) are failling. energyplus uses all of my RAM (16GB on this machine) while running a single simulation, I don't think I've seen this ever before...
I've got a eplusout.dbg in the run folder which shouldn't happen.
Could the Alpha2 asset be a debug build of E+ or something?
Lookig at the in.idf that's generated, there's some funky business witht eh Table Objects
```
Table:IndependentVariable,
  CapModFuncOfWaterFlow 7_IndependentVariable_0, !- Name
  Cubic,                                  !- Interpolation Method
  Constant,                               !- Extrapolation Method
  0,                                      !- Minimum Value {BasedOnField A4}
  1.333333,                               !- Maximum Value {BasedOnField A4}
  ,                                       !- Normalization Reference Value {BasedOnField A4}
  Dimensionless,                          !- Unit Type
  ,                                       !- External File Name
  ,                                       !- External File Column Number
  ,                                       !- External File Starting Row Number
  0&#44000000,                            !- Value 1
  0&#44050000,                            !- Value 2
  0&#44333330,                            !- Value 3
  0&#44500000,                            !- Value 4
  0&#44666667,                            !- Value 5
  0&#44833333,                            !- Value 6
  1&#44000000,                            !- Value 7
  1&#44333333;                            !- Value 8
```
running the very similar airterminal_cooledbeam_osm test takes 120 MB of memory...
I  am using the binary posted by CI on Ubuntu 18.04.

**Comment by Myoldmopar** [comment] 2019-09-20 18:06
Can you attach an IDF so I can try to reproduce?

And yeah, it looks like maybe the OS forward translator has an issue with the new table structure, that might be causing the input processor to fail?  Just guessing at this point.  

FYI @mbadams5  @kbenne

**Comment by tijcolem** [comment] 2019-09-20 18:12
tagging @jmarrec to provide the sample file of his run.

**Comment by jmarrec** [comment] 2019-09-20 18:16
I'll upload it in a few minutes. Mind that the fact the IDF has these weird values is on openstudio's side... Openstudio model has correct numeric value, something weird is going on in the Forward Translation to OSM probably

**Comment by jmarrec** [comment] 2019-09-20 18:19
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3637231/in.idf.txt)

[in.osm.txt](https://github.com/NREL/EnergyPlus/files/3637232/in.osm.txt)

**Comment by tijcolem** [comment] 2019-09-20 18:26
thanks for providing that, Julien.  Correct me if I'm wrong, but this was an e+ process consuming the excess memory, right?   My mistake if not.

**Comment by jmarrec** [comment] 2019-09-20 19:03
Yes, it's definitly energyplus that hogging RAM like crazy. But we are feeding E+ gibberrish (it still shouldn't go crazy though...)

**Comment by mbadams5** [comment] 2019-09-20 19:09
The input parser is getting into an infinite loop. I'm looking into it right now.
However, that will just make EnergyPlus not get into an infinite loop, finish parsing, and report an error that those are not numbers. So you still need to figure out why the numbers are being output from the forward translator in that fashion.

**Comment by jmarrec** [comment] 2019-09-20 20:04
Good to know you caught the infinite loop. I'm fully aware that the real fix for this specific issue is OS's side yes, looking into it

**Comment by jmarrec** [comment] 2019-09-20 20:38
ok caught OpenStudio's problem in https://github.com/NREL/OpenStudio/commit/b730bb24c37ef07cd1941e0f5e56f06566eda57a (and the following commit where I caught a typo)

**Closed as completed** 2019-09-20 23:29 UTC
