### ISSUE TITLE
 Error while running energyplus from external interface

### ISSUE THREAD

**Issue by gopal86** [NREL/EnergyPlus#7820] opened 2020-02-27 04:40 UTC
Issue overview
--------------
While running energy plus from an external interface, I get the following severe error:

>ExternalInterface: Received end of simulation flag at time = 120.00 hours

I am running the IDF for 5 days i.e. 120 hours. Can anyone help me solve it? 
Also, If I do simulation without external interface, in the output I get 4 CSV files, but while I run from the external interface, I get only 2 CSV files as output. Is it also because I am getting a severe error as mentioned above? 

### Details
Some additional details for this issue:
 - Platform (Operating system, Ubuntu 18.04)
 - Version of EnergyPlus: 8.7 
 - [Unmethours link](https://unmethours.com/question/43040/error-while-running-energyplus-from-external-interface/)

**Comment by jmarrec** [comment] 2020-12-08 11:05
I doubt this is a question anyone will pick up since it it seems pretty specific to the BCTVB, and we have no files to reproduce it anyways.

If you aren't satisfied with the answer you got on https://unmethours.com/question/43040/error-while-running-energyplus-from-external-interface/, I suggest emailing https://groups.google.com/group/bcvtb (see https://simulationresearch.lbl.gov/bcvtb/Help)

So I'm going to close it.

**Closed as completed by jmarrec** 2020-12-08 11:05 UTC
