### ISSUE TITLE
Pump causing buggy output

### ISSUE THREAD

**Issue by ejhw** [NREL/EnergyPlus#5139] opened 2015-08-24 16:14 UTC
I am seeing `-1.#IND00000000000E+000` during one hour of hourly output (*.csv). The hourly output is then zero for the rest of the year. I also see `************` and `-1.#J` values in several meters and tables in *Table.csv. These values are associated with pump object `GSHPPump_2`. 

Defect idf, csv, and Table.csv: https://gist.github.com/ejhw/18d50ca70df34e90ea58

I have two identical zones with identical systems (ground source heat pumps). `GSHPPump_2` shows the issue, but `GSHPPump_1` does not. 

Seen in Version 8.3.0-6d97d074ea and Version 8.3.4-beb553b6cd.

**Comment by Myoldmopar** [comment] 2015-08-24 16:18
Ummm, more info please.  Asterisks are expected to be there in the err file, for example, and there are some 20 output files possible from E+ plus stdout and stderr.

**Comment by ejhw** [comment] 2015-08-24 16:19
Sorry, I hit enter prematurely. Working on it.

**Comment by Myoldmopar** [comment] 2015-08-24 16:19
Ah, OK.  Carry on  :smile:

**Comment by ejhw** [comment] 2015-08-24 18:20
Updated with a new name, description, and defect files. cc @Myoldmopar @nmerket

**Comment by JasonGlazer** [comment] 2016-02-11 20:31
@ejhw when I try to rerun the test IDF file provided on the gist I get an error. It looks like the file is truncated at line 35701. Could you please just email the files to jglazer@gard.com? I will put the test files in the repo that we put files related to individual issues.

**Comment by ejhw** [comment] 2016-02-11 21:45
@JasonGlazer – okay sent. Not sure how it got truncated, but I was able to find the original in the gist revision history (luckily).

**Comment by JasonGlazer** [comment] 2016-02-12 16:49
@ejhw Thanks I was able to reproduce this issue.

**Comment by JasonGlazer** [comment] 2016-02-12 16:56
The same issue occurs in the release version of 8.4.0

**Comment by JasonGlazer** [comment] 2016-02-12 19:35
Looks like it is not an issue with the output routines but with some calculation:

http://stackoverflow.com/questions/7476177/why-the-return-value-of-double-is-1-ind

**Comment by Myoldmopar** [comment] 2016-02-26 14:46
Closed via #5486

**Closed as completed by Myoldmopar** 2016-02-26 14:46 UTC
Labels: Defect

**Comment by mjwitte** [comment] 2016-03-10 23:01
A workaround has been found for this.  The file uses a custom glycol:
```
  FluidProperties:GlycolConcentration,
    GLHXFluid,               !- Name
    PropyleneGlycol,         !- Glycol Type
    ,                        !- User Defined Glycol Name
    0.3;                     !- Glycol Concentration

  CondenserLoop,
    Chilled Water Condenser Loop_2,  !- Name
    UserDefinedFluidType,    !- Fluid Type
    GLHXFluid,               !- User Defined Fluid Type
```
Based on the IDD reference/object-list tags, this needs an additional object.
```
FluidProperties:Name,
  PropyleneGlycol30Percent, !- Fluid Name
  Glycol; !- Fluid Type
```
Not sure why this does not report an error.  And not sure why this is necessary, but it avoids the bug.

**Comment by mjwitte** [comment] 2016-03-10 23:03
Never mind - that does not get past the bug.
