### ISSUE TITLE
Update LCC using NIST 135

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9551] opened 2022-07-20 11:49 UTC
Issue overview
--------------
The last update for the energy cost price escalation was LCCusePriceEscalationDataSet2019.idf. The 2020, 2021, and 2022 updates should be added based on NIST 135 annual supplements. See #7218 for the last update

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment] 2022-07-26 13:07
Duplicate of #9153 (I'll close the older one).

**Closed as completed** 2022-07-28 23:38 UTC
Labels: Defect
