### ISSUE TITLE
Ideal loads sizing and/or cooling capacity limit issue

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7109] opened 2018-12-20 20:40 UTC
Issue overview
--------------
Unable to get the max value of "Zone Ideal Loads Supply Air Total Cooling Rate" to match the autosized value for "Design Size Maximum Total Cooling Capacity" when running the design day simulations. Note how the zone temperature in Space1-1 goes a little above the setpoint in the afternoon.  There appears to be an issue with the way the capacity limit is applied when using ConstantSensibleHeatRatio dehumidification type. And there may be an issue with the autosizing calc? The capacity vs max load is fairly close for zones 1, 2, and 4, but zone 3 is off by 10%.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.0.1
 - [Unmethours 35469](https://unmethours.com/question/35469/ashrae-sizing-zone-sensible-cooling-and-zonehvacidealloadsairsystem/)
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached:
[HVACTemplate-5ZonePurchAir-Autosized-Sizex1-exp.idf.txt](https://github.com/NREL/EnergyPlus/files/2700459/HVACTemplate-5ZonePurchAir-Autosized-Sizex1-exp.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by YanfeiNREL** [comment] 2019-07-24 16:52
The issue is related with PurchasedAirManager.cc. It looks like the source code only handles the option: Dehumidification-Control-Type=Humidistat. However, for other options: ConstantSensibleHeatRatio, None, or ConstantSupplyHumidityRatio, the source code doesn't implement the logic.
For Space1-1, the Dehumidification-Control-Type=ConstantSensibleHeatRatio, the same with Space2-1,  and Space4-1 (Surprisingly there is no cap issue for those zones).
 I will test and see whether my speculation is correct.  @mjwitte

**Comment by YanfeiNREL** [comment] 2019-08-13 21:53
i tried to revise the options for Dehumidification-Control-Type. It is still the same issue. looks like my initial speculation is not correct. @mjwitte

**Comment by YanfeiNREL** [comment] 2019-09-20 17:01
It seems like the issue was caused by time resolution. The issue reporter used the hourly time resolution for outputs. 

To recreate the issue (Boulder CO weather file), i got the following figures:
(1.1) Zone Peak Cooling Load (**Hourly timestep**):
        zone-1: 3954.73, 15:00 PM, 7/21
        zone-2: 3875.76, 11:00 AM, 7/21 ==> off 7%
        zone-3: 6255.91, 09:00 AM, 7/21 ==> off 13%
        zone-4: 4189.02, 18:00 PM, 7/21 ==> off 7%
        zone-5: 7139.94, 16:00 PM, 7/21
        The simulation results shown in the table: 
![TableSimulationHourResolution](https://user-images.githubusercontent.com/43475933/65349186-0fedbe00-dba0-11e9-92b1-9da2c120864f.PNG)
(1.2) The zone-1 temperature is also shown:
![SummerDesignDayTempZone1Hourly](https://user-images.githubusercontent.com/43475933/65349683-437d1800-dba1-11e9-8d57-0b490701cc85.PNG)
(1.3) The simulation outputs has some severe error shown below (cooling related limits should be specified in IDF):
      ![ErrorSummary](https://user-images.githubusercontent.com/43475933/65350299-a1f6c600-dba2-11e9-9812-051468811225.PNG)

From the figures and numbers, we can see Zone-3 has 10% off for max cooling load.
zone-1 temp has 0.35 celsius degree off comparing with setpoints.
***********************************************************************************************************
    *************     Below are outputs for time resolution to 15 minutes    **************
***********************************************************************************************************
(2.1)The zone-1 temperature (timestep 15minutes) is shown in Figure1:
![SummerDesignDayTempZone1](https://user-images.githubusercontent.com/43475933/65344784-da43d780-db95-11e9-96c8-26a795cd6a6d.PNG)
![WinterDesignDayTempZone1](https://user-images.githubusercontent.com/43475933/65344787-ddd75e80-db95-11e9-9e5c-ca4665025502.PNG)

(2.2)The zone total cooling load (timestep 15minutes) is shown in Figure2:
![ZoneTotalCoolingLoad](https://user-images.githubusercontent.com/43475933/65347492-5a6d3b80-db9c-11e9-8696-44fb4f40f86a.PNG)

(2.3)The Sizing Summary of Zone total Cooling Load (EnergyPlus simulation outputs, timestep 15minutes) is shown in Figure3:
![TableSimulation](https://user-images.githubusercontent.com/43475933/65347500-61944980-db9c-11e9-9138-f8869d5ffb54.PNG)

Thus, It looks okay zone-1 still has 0.35 degree off comparing to the setpoint.
Zone Peak Cooling Load(15 minutes timestep) are okay too (especially zone-3): 
        zone-1: 4037.357, 15:00 PM, 7/21
        zone-2: 3939.223, 10:15 AM, 7/21 ==> off 7%
        zone-3: 7157.890, 08:15 AM, 7/21 ==> off 0.5%
        zone-4: 4249.170, 17:15 PM, 7/21 ==> off 7%
        zone-5: 7196.143, 15:00 PM, 7/21

***********************************************************************************************************
***********************************************************************************************************
Overall, i think the issue was because of the time resolution of outputs. I didn't see logic drawbacks in the source code.
I am closing it now, unless more similar issues occur in the future.
The input file(IDF, v9.1) and Outputs are both attached, if further investigation were needed.
Boulder, CO weather file.
[7109.zip](https://github.com/NREL/EnergyPlus/files/3637295/7109.zip)

**Closed as completed** 2019-09-20 18:44 UTC
Labels: Defect
