### ISSUE TITLE
CurveFitTool.xlm is not calculating the function of flow fraction curves correctly

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4546] opened 2014-10-18 01:06 UTC
Helpdesk Ticket 9928

Found bug in CurveFitTool.xlm

 From the source code (DXcoils.cc) it can be seen that the curves as a function of flow must be established using the fraction of flow relative to rated flow, i.e. "AirMassFlowRatioRated" and not the not the flowrate in m3/s. I think this is a carry over from the chiller curve setup. After amending this, I get the rating capacities of calculated by energyplus to match my spreadsheet calcs.

 TotCapFlowModFac = CurveValue( DXCoil( DXCoilNum ).CCapFFlow( 1 ), AirMassFlowRatioRated );
 TotCapTempModFac = CurveValue( DXCoil( DXCoilNum ).CCapFTemp( 1 ), CoolingCoilInletAirWetBulbTempRated, OutdoorUnitInletAirDryBulbTempRated );

**Comment by jeannieboef** [comment] 2015-02-23 11:21
Please also check/consider that the datasets curves for dx coils is consistant in this manner.

**Comment by Nigusse** [comment] 2015-03-13 13:50
It is true that the CurveTool uses volume ratio instead of mass flow ratio to generate the capacity and EIR correction curves for flow variation. The reason is that the volume and mass flow ratios are identical if the actual and rated volume flow rates were measured (evaluated) at the rated temperatures (DB and WB).  Here is how I interpreted the concept of using temperature and flow correction curves in the formulation of Capacity and EIR calculation.  Let us look at the Capacity calculation formulation for this discussion:

CAP(twb, tdb, ff) = CAP(Rated) * CAPFT(twb, tdb) *  CAPFF(FF)

Decoupling the temperature and flow correction entails inherent assumption that the CAPFF is only function of flow, i.e., the curve accounts for capacity variation with flow every other thing being at the rated condition.  And it is for this reason that only the data points (capacity and power) evaluated at the rated condition but different flow rates were used to generate the curve. If this is the underlying assumption when formulating the equation for DX coil Capacity and Electric Power use calculation, then the volume and mass flow ratio are identical.  Also since manufacturers publish volume flow rates (CFM) data, I ended ups using volume flow ratio instead of mass flow ratio because they are the same. Simply, the density cancels out.

This is the basis of the DX coil Capacity calculating equation formulation, as I understood it. I think it is true for all other equations in EnergyPlus that decouples temperature and flow corrections; otherwise, if we try to account the effect of temperature on the flow variation, then the premise of decoupling in the model formulation is violated.  That is my understanding of the model and the curve generation reflects that fact. Therefore, the use of volume flow ratio is correct.

**Comment by mjwitte** [comment] 2015-03-13 14:59
@jeannieboef See Bereket's comments above.  To expand on this, in EnergyPlus, all volume flow rates (as inputs from the idf or calculated from autosizing) are converted to mass flow rates using the standard air density for the location elevation.  So, to EnergyPlus, volume flow ratio and mass flow ratios will be identical.  That raises a new question - are the volume flow rates in the manufacturer's data stated in standard CFM (constant density) or not?

**Comment by jeannieboef** [comment] 2015-03-14 06:20
Firstly, I think Bereket is correct. I have learnt a lot since this
ticket was raised and can see no reason to doubt the logic. My
personal sheet also has made leaps and bounds since then and I can now
verify the e+ rating calculations for the single speed constant fan
coil exactly for all the rating values EER, IEER, SEER, etc.

At the time of the ticket I had set up a sheet to regress the curves
based on volume ratios. The
curves matched those of the CurveFitTool, but  my full load capacity
calculation did not match that of the e+ simulation using these curves.

After looking in the code, I saw that the curve expects massflow rate
as an input so I changed my sheet to calculate the density
(using e+ psychometric routines) and massflow at each performance data
point and then regressed the curves again using the massflows. The
curves did not match those of the CurveFitTool, but when used in the e
+ simulation, the full load capacity result from e+ matched my
calculation.

Hence my conclusion.

IMPORTANT
1) You will notice straight away that something is not right in that
the curve limits are in m³/s, instead of kg/s. I controlled this again
this morning. Can you reproduce this?
2) The constant coefficient is also looking far too big. The curves
are being produced in such a way as to require volume flow rate as
input. This is inconsistant in how e+ uses the mass flow rate to feed
into them in the simulation.

**Comment by Nigusse** [comment] 2015-03-14 16:24
@jeannieboef (1) which curve limits are you talking about?  The capacity and EIR modifier curves input (flow fraction) and curve output are dimensionless.  This curves are normalized curves.  So, the curve limits should also be dimensionless.  I will look into this.

(2) Which constant coefficients are you talking about? are you talking about the significant digits of the curve coefficients?  The inputs (to the CurveFitTool) are specified in m3/s or CFM because manufacturers are providing volume flow rates, so we did not see any point in asking the user to convert them to kg/s (it is unnessary burden to the user) if the results are the same. Note that most input fields (e.g. rated supply and outdoor air flow rates) in EnergyPlus objects are volume flow rate (m3/s) even though mass flow rates are used internally in the model calculation.  I do not see this as inconsistency.

**Comment by jeannieboef** [comment] 2015-03-14 21:21
1) yes I mean the FFF curves.

2) by contant term, I mean the first coefficient of the curve formula  
that is not multiplied by anything.

3) I agree that it should not be nessesary. e+ correctly converts the  
volume flow rate to mass flowrate and injects the mass flowrate into  
the curve. But if the curve is incorrect, in that it has been setup to  
accept a volume flowrate and instead of a mass flowrate, this is  
inconsistant.

The e+ program works great and is consistent, but the FFF curves  
obtained from the HVACCurveFitTool are not consistsnt with what the  
program expects. e+ will pass the FFF curves mass flow rates.

I only have cell phone Internet this weekend, otherwise I could send  
an example, but you only need to try it to see. Try make the CAPFFF  
and EIRFFF cubic curves for cooling. You will see by the curve x and y  
term limits and the constant coeffs. that they are not mass flows  
which they should be, but volume flow rates. The curve output limits  
should be dimensionless as you say.
>

**Comment by jeannieboef** [comment] 2015-03-15 20:46
clarification to earlier email:
1) "and injects the mass flowrate", should read and injects the mass
flowrate ratio (i.e. mass flowrate / rated mass flow rate...which should
also be equal to volume flowrate / rated volume flowrate as you stated).
2) What I'm saying is that the curve tool does not use normilized flow, but
absolute flow to regress the curves.

Included is a very old and full of mistakes spreadsheet, that I validated
gave the same curves as the curve tool. at the time. On the "CAPFF & EIRFF"
you can clearly see how I regressed at the time. And this matched the
tool's curves. If you need it, I can send a copy of my up to date sheet
that calculates everything correctly and is validated against e+.

Just to be absolutely clear: this attachment is an incorrect calculation,
that gives the same curves as the curve tool. As a fix suggestion, I would
guess that you'd just have to get the nomilization of the flows sorted out.
The rest works fine as far as I can tell.

As a last comment, I would like to be assured that the curves in the
databank set are correct. A quick glance looks good, but I don't know how
they were created.



2015-03-14 17:24 GMT+01:00 Bereket Nigusse <notifications@github.com>:

**Comment by Nigusse** [comment] 2015-03-16 13:08
"2) What I'm saying is that the curve tool does not use normalized flow, but absolute flow to regress the curves."
THIS IS INCORRECT STATEMENT.  The CurveFitTool input data is in m3/s (CFM) curve but internally the VBA code first converts the volume flow rate (m3/s) into volume flow ratio (==mass flow ratio), normalizes the capacity and EIR, then finally generates the coefficients.  I developed the curve generation tool, so I know that the tool uses normalized independent and dependent variables to generate the curve coefficients.  I do not understand how you came up to the conclusion that the tool uses absolute volume flow rates to generate the curves. What do you mean that you validated your results against EnergyPlus?  I do not have the resources to study your tool but I am glad if you point out how you found out that the curve tool uses absolute flow rates instead of flow fraction?

I think some of the data sets (latest ones) were generated using this tool and I believe that they are correct.  The person who generated the latest curve coefficients had used the same CurveFitTool.

**Comment by jeannieboef** [comment] 2015-03-16 17:35
CurveTool:
Go into Module "Main".
On line 761, character position 43, replace the capital "M" with a  
lowercase "m" so that the program goes into the if statement and  
normilizes the flow as it should do.

That should do the trick. I will verify later when I have time.

PS. I wish my programming was as eligant as your work. Please don't be  
offended.

Mit freundlichen Grüßen- Sent from my iPhone (excuse the brevity)

i. A.
Jean Marais
b.i.g. bechtold
Tel.   +49 30 6706662-23

**Comment by Nigusse** [comment] 2015-03-16 17:59
@jeannieboef You are correct the normalization calculation jumps the flow rate normalization step if the volume flow rate input data unit is m3/s, instead of M3/s. I see the problem now.  This a bug in the code and will be fixed to allow both smaller and upper cases. Thank you.

**Comment by jeannieboef** [comment] 2015-03-16 18:11
No worries. As a non-programmer, I'm always afraid to look at other  
people's programs. This was the first time I looked at the Tool's  
macro code. You asked how I found this...well during the making of my  
spreadsheet, I was incorrectly not normalizing the flowrates, but  
getting the same curves as the Tool.

My goal was to calculate the rating values. Then I studied the  
documentation and changed my sheet to reflect it, at which point I  
could predict the full load efficiencies exactly. ..with curves  
different to those of the Tool.

Mit freundlichen Grüßen- Sent from my iPhone (excuse the brevity)

i. A.
Jean Marais
b.i.g. bechtold
Tel.   +49 30 6706662-23

**Comment by Nigusse** [comment] 2015-03-16 19:31
The input processor calculation skips volume flow rate normalization step if the volume flow rate input data unit is m3/s, instead of M3/s. The VBA code bug has been fixed. Also a defective or old Curve Fit Tool spreadsheet along with test case data is placed in defect folder  #4546 for reference.

**Comment by Myoldmopar** [comment] 2015-03-19 15:19
@Nigusse So this should be closed now, right?

**Comment by Nigusse** [comment] 2015-03-19 15:34
Yes.  I am not sure if there is a need for someone else to verify the fix.

**Closed** 2015-03-19 15:43 UTC
Labels: EnergyPlus, Priority, S1 - High

**Comment by mjwitte** [comment] 2015-03-19 15:50
@Myoldmopar Would be good for this to get on the change list.

**Comment by Myoldmopar** [comment] 2015-03-19 16:13
Good point, @mjwitte, I'll open a dummy branch/PR that points to this issue to get it included.
